// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package browse_test

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSnippetLister creates a new instance of MockSnippetLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnippetLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnippetLister {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSnippetLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSnippetLister is an autogenerated mock type for the SnippetLister type
type MockSnippetLister struct {
	mock.Mock
}

type MockSnippetLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnippetLister) EXPECT() *MockSnippetLister_Expecter {
	return &MockSnippetLister_Expecter{mock: &_m.Mock}
}

// ListInFolder provides a mock function for the type MockSnippetLister
func (_mock *MockSnippetLister) ListInFolder(ctx context.Context, folderID domain.FolderID) ([]domain.Snippet, error) {
	ret := _mock.Called(ctx, folderID)

	if len(ret) == 0 {
		panic("no return value specified for ListInFolder")
	}

	var r0 []domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) ([]domain.Snippet, error)); ok {
		return returnFunc(ctx, folderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) []domain.Snippet); ok {
		r0 = returnFunc(ctx, folderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Snippet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FolderID) error); ok {
		r1 = returnFunc(ctx, folderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnippetLister_ListInFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInFolder'
type MockSnippetLister_ListInFolder_Call struct {
	*mock.Call
}

// ListInFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - folderID domain.FolderID
func (_e *MockSnippetLister_Expecter) ListInFolder(ctx any, folderID any) *MockSnippetLister_ListInFolder_Call {
	return &MockSnippetLister_ListInFolder_Call{Call: _e.mock.On("ListInFolder", ctx, folderID)}
}

func (_c *MockSnippetLister_ListInFolder_Call) Run(run func(ctx context.Context, folderID domain.FolderID)) *MockSnippetLister_ListInFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FolderID
		if args[1] != nil {
			arg1 = args[1].(domain.FolderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnippetLister_ListInFolder_Call) Return(snippets []domain.Snippet, err error) *MockSnippetLister_ListInFolder_Call {
	_c.Call.Return(snippets, err)
	return _c
}

func (_c *MockSnippetLister_ListInFolder_Call) RunAndReturn(run func(ctx context.Context, folderID domain.FolderID) ([]domain.Snippet, error)) *MockSnippetLister_ListInFolder_Call {
	_c.Call.Return(run)
	return _c
}
