// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package browse_test

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFolderLister creates a new instance of MockFolderLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFolderLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFolderLister {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFolderLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFolderLister is an autogenerated mock type for the FolderLister type
type MockFolderLister struct {
	mock.Mock
}

type MockFolderLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFolderLister) EXPECT() *MockFolderLister_Expecter {
	return &MockFolderLister_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockFolderLister
func (_mock *MockFolderLister) List(ctx context.Context) ([]domain.Folder, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Folder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Folder, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Folder); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Folder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFolderLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFolderLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFolderLister_Expecter) List(ctx any) *MockFolderLister_List_Call {
	return &MockFolderLister_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockFolderLister_List_Call) Run(run func(ctx context.Context)) *MockFolderLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFolderLister_List_Call) Return(folders []domain.Folder, err error) *MockFolderLister_List_Call {
	_c.Call.Return(folders, err)
	return _c
}

func (_c *MockFolderLister_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Folder, error)) *MockFolderLister_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnippetCounter creates a new instance of MockSnippetCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnippetCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnippetCounter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSnippetCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSnippetCounter is an autogenerated mock type for the SnippetCounter type
type MockSnippetCounter struct {
	mock.Mock
}

type MockSnippetCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnippetCounter) EXPECT() *MockSnippetCounter_Expecter {
	return &MockSnippetCounter_Expecter{mock: &_m.Mock}
}

// CountByFolder provides a mock function for the type MockSnippetCounter
func (_mock *MockSnippetCounter) CountByFolder(ctx context.Context) (map[domain.FolderID]int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountByFolder")
	}

	var r0 map[domain.FolderID]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[domain.FolderID]int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[domain.FolderID]int); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.FolderID]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnippetCounter_CountByFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByFolder'
type MockSnippetCounter_CountByFolder_Call struct {
	*mock.Call
}

// CountByFolder is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSnippetCounter_Expecter) CountByFolder(ctx any) *MockSnippetCounter_CountByFolder_Call {
	return &MockSnippetCounter_CountByFolder_Call{Call: _e.mock.On("CountByFolder", ctx)}
}

func (_c *MockSnippetCounter_CountByFolder_Call) Run(run func(ctx context.Context)) *MockSnippetCounter_CountByFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSnippetCounter_CountByFolder_Call) Return(folderIDToInt map[domain.FolderID]int, err error) *MockSnippetCounter_CountByFolder_Call {
	_c.Call.Return(folderIDToInt, err)
	return _c
}

func (_c *MockSnippetCounter_CountByFolder_Call) RunAndReturn(run func(ctx context.Context) (map[domain.FolderID]int, error)) *MockSnippetCounter_CountByFolder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnippetLister creates a new instance of MockSnippetLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnippetLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnippetLister {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSnippetLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSnippetLister is an autogenerated mock type for the SnippetLister type
type MockSnippetLister struct {
	mock.Mock
}

type MockSnippetLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnippetLister) EXPECT() *MockSnippetLister_Expecter {
	return &MockSnippetLister_Expecter{mock: &_m.Mock}
}

// ListInFolder provides a mock function for the type MockSnippetLister
func (_mock *MockSnippetLister) ListInFolder(ctx context.Context, folderID domain.FolderID, order domain.SortOrder) ([]domain.Snippet, error) {
	ret := _mock.Called(ctx, folderID, order)

	if len(ret) == 0 {
		panic("no return value specified for ListInFolder")
	}

	var r0 []domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID, domain.SortOrder) ([]domain.Snippet, error)); ok {
		return returnFunc(ctx, folderID, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID, domain.SortOrder) []domain.Snippet); ok {
		r0 = returnFunc(ctx, folderID, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Snippet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FolderID, domain.SortOrder) error); ok {
		r1 = returnFunc(ctx, folderID, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnippetLister_ListInFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInFolder'
type MockSnippetLister_ListInFolder_Call struct {
	*mock.Call
}

// ListInFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - folderID domain.FolderID
//   - order domain.SortOrder
func (_e *MockSnippetLister_Expecter) ListInFolder(ctx any, folderID any, order any) *MockSnippetLister_ListInFolder_Call {
	return &MockSnippetLister_ListInFolder_Call{Call: _e.mock.On("ListInFolder", ctx, folderID, order)}
}

func (_c *MockSnippetLister_ListInFolder_Call) Run(run func(ctx context.Context, folderID domain.FolderID, order domain.SortOrder)) *MockSnippetLister_ListInFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FolderID
		if args[1] != nil {
			arg1 = args[1].(domain.FolderID)
		}
		var arg2 domain.SortOrder
		if args[2] != nil {
			arg2 = args[2].(domain.SortOrder)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSnippetLister_ListInFolder_Call) Return(snippets []domain.Snippet, err error) *MockSnippetLister_ListInFolder_Call {
	_c.Call.Return(snippets, err)
	return _c
}

func (_c *MockSnippetLister_ListInFolder_Call) RunAndReturn(run func(ctx context.Context, folderID domain.FolderID, order domain.SortOrder) ([]domain.Snippet, error)) *MockSnippetLister_ListInFolder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagLister creates a new instance of MockTagLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagLister {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTagLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTagLister is an autogenerated mock type for the TagLister type
type MockTagLister struct {
	mock.Mock
}

type MockTagLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagLister) EXPECT() *MockTagLister_Expecter {
	return &MockTagLister_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockTagLister
func (_mock *MockTagLister) List(ctx context.Context) ([]domain.Tag, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Tag, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Tag); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTagLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTagLister_Expecter) List(ctx any) *MockTagLister_List_Call {
	return &MockTagLister_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTagLister_List_Call) Run(run func(ctx context.Context)) *MockTagLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagLister_List_Call) Return(tags []domain.Tag, err error) *MockTagLister_List_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagLister_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Tag, error)) *MockTagLister_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagSnippetCounter creates a new instance of MockTagSnippetCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagSnippetCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagSnippetCounter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTagSnippetCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTagSnippetCounter is an autogenerated mock type for the TagSnippetCounter type
type MockTagSnippetCounter struct {
	mock.Mock
}

type MockTagSnippetCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagSnippetCounter) EXPECT() *MockTagSnippetCounter_Expecter {
	return &MockTagSnippetCounter_Expecter{mock: &_m.Mock}
}

// CountByTag provides a mock function for the type MockTagSnippetCounter
func (_mock *MockTagSnippetCounter) CountByTag(ctx context.Context) (map[domain.TagID]int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountByTag")
	}

	var r0 map[domain.TagID]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[domain.TagID]int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[domain.TagID]int); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.TagID]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagSnippetCounter_CountByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByTag'
type MockTagSnippetCounter_CountByTag_Call struct {
	*mock.Call
}

// CountByTag is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTagSnippetCounter_Expecter) CountByTag(ctx any) *MockTagSnippetCounter_CountByTag_Call {
	return &MockTagSnippetCounter_CountByTag_Call{Call: _e.mock.On("CountByTag", ctx)}
}

func (_c *MockTagSnippetCounter_CountByTag_Call) Run(run func(ctx context.Context)) *MockTagSnippetCounter_CountByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagSnippetCounter_CountByTag_Call) Return(tagIDToInt map[domain.TagID]int, err error) *MockTagSnippetCounter_CountByTag_Call {
	_c.Call.Return(tagIDToInt, err)
	return _c
}

func (_c *MockTagSnippetCounter_CountByTag_Call) RunAndReturn(run func(ctx context.Context) (map[domain.TagID]int, error)) *MockTagSnippetCounter_CountByTag_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagSnippetLister creates a new instance of MockTagSnippetLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagSnippetLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagSnippetLister {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTagSnippetLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTagSnippetLister is an autogenerated mock type for the TagSnippetLister type
type MockTagSnippetLister struct {
	mock.Mock
}

type MockTagSnippetLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagSnippetLister) EXPECT() *MockTagSnippetLister_Expecter {
	return &MockTagSnippetLister_Expecter{mock: &_m.Mock}
}

// ListWithTag provides a mock function for the type MockTagSnippetLister
func (_mock *MockTagSnippetLister) ListWithTag(ctx context.Context, tagID domain.TagID, order domain.SortOrder) ([]domain.Snippet, error) {
	ret := _mock.Called(ctx, tagID, order)

	if len(ret) == 0 {
		panic("no return value specified for ListWithTag")
	}

	var r0 []domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TagID, domain.SortOrder) ([]domain.Snippet, error)); ok {
		return returnFunc(ctx, tagID, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TagID, domain.SortOrder) []domain.Snippet); ok {
		r0 = returnFunc(ctx, tagID, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Snippet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.TagID, domain.SortOrder) error); ok {
		r1 = returnFunc(ctx, tagID, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagSnippetLister_ListWithTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithTag'
type MockTagSnippetLister_ListWithTag_Call struct {
	*mock.Call
}

// ListWithTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID domain.TagID
//   - order domain.SortOrder
func (_e *MockTagSnippetLister_Expecter) ListWithTag(ctx any, tagID any, order any) *MockTagSnippetLister_ListWithTag_Call {
	return &MockTagSnippetLister_ListWithTag_Call{Call: _e.mock.On("ListWithTag", ctx, tagID, order)}
}

func (_c *MockTagSnippetLister_ListWithTag_Call) Run(run func(ctx context.Context, tagID domain.TagID, order domain.SortOrder)) *MockTagSnippetLister_ListWithTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TagID
		if args[1] != nil {
			arg1 = args[1].(domain.TagID)
		}
		var arg2 domain.SortOrder
		if args[2] != nil {
			arg2 = args[2].(domain.SortOrder)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagSnippetLister_ListWithTag_Call) Return(snippets []domain.Snippet, err error) *MockTagSnippetLister_ListWithTag_Call {
	_c.Call.Return(snippets, err)
	return _c
}

func (_c *MockTagSnippetLister_ListWithTag_Call) RunAndReturn(run func(ctx context.Context, tagID domain.TagID, order domain.SortOrder) ([]domain.Snippet, error)) *MockTagSnippetLister_ListWithTag_Call {
	_c.Call.Return(run)
	return _c
}
