log-level: warn
template: testify
dir: "{{.InterfaceDir}}"
filename: mocks_test.go
pkgname: "{{.SrcPackageName}}_test"
packages:
  github.com/DannyFestor/TuiSnip/internal/app/snippet:
    interfaces:
      Inserter: {}
      Finder: {}
      Copier: {}
  github.com/DannyFestor/TuiSnip/internal/app/search:
    interfaces:
      Searcher: {}
  github.com/DannyFestor/TuiSnip/internal/adapters/memsearch:
    interfaces:
      SnippetLister: {}
