log-level: warn
template: testify
dir: "{{.InterfaceDir}}"
filename: mocks_test.go
pkgname: "{{.SrcPackageName}}_test"
packages:
  github.com/DannyFestor/TuiSnip/internal/app/snippet:
    interfaces:
      Inserter: {}
      Finder: {}
      Copier: {}
  github.com/DannyFestor/TuiSnip/internal/app/folder:
    interfaces:
      CreateRepository: {}
      RenameRepository: {}
      PreviewDeleteRepository: {}
      Deleter: {}
  github.com/DannyFestor/TuiSnip/internal/app/search:
    interfaces:
      Searcher: {}
  github.com/DannyFestor/TuiSnip/internal/app/browse:
    interfaces:
      SnippetLister: {}
      FolderLister: {}
      SnippetCounter: {}
  github.com/DannyFestor/TuiSnip/internal/adapters/tui:
    interfaces:
      FolderSnippetsLister: {}
      FolderTreeLister: {}
      SnippetCopier: {}
      SnippetCreator: {}
      SnippetSearcher: {}
      FolderCreator: {}
      FolderRenamer: {}
      FolderDeletePreviewer: {}
      FolderDeleter: {}
  github.com/DannyFestor/TuiSnip/internal/adapters/tui/overlay:
    interfaces:
      Overlay: {}
      Parent: {}
      Base: {}
  github.com/DannyFestor/TuiSnip/internal/adapters/memsearch:
    interfaces:
      SnippetLister: {}
