// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tui_test

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/adapters/tui"
	"github.com/DannyFestor/TuiSnip/internal/app/browse"
	"github.com/DannyFestor/TuiSnip/internal/app/folder"
	"github.com/DannyFestor/TuiSnip/internal/app/search"
	"github.com/DannyFestor/TuiSnip/internal/app/snippet"
	"github.com/DannyFestor/TuiSnip/internal/app/tag"
	"github.com/DannyFestor/TuiSnip/internal/domain"
	"github.com/DannyFestor/TuiSnip/internal/domain/value"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCollapsedFoldersSaver creates a new instance of MockCollapsedFoldersSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollapsedFoldersSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollapsedFoldersSaver {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCollapsedFoldersSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCollapsedFoldersSaver is an autogenerated mock type for the CollapsedFoldersSaver type
type MockCollapsedFoldersSaver struct {
	mock.Mock
}

type MockCollapsedFoldersSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollapsedFoldersSaver) EXPECT() *MockCollapsedFoldersSaver_Expecter {
	return &MockCollapsedFoldersSaver_Expecter{mock: &_m.Mock}
}

// SaveCollapsedFolders provides a mock function for the type MockCollapsedFoldersSaver
func (_mock *MockCollapsedFoldersSaver) SaveCollapsedFolders(ctx context.Context, ids []domain.FolderID) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for SaveCollapsedFolders")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.FolderID) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCollapsedFoldersSaver_SaveCollapsedFolders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCollapsedFolders'
type MockCollapsedFoldersSaver_SaveCollapsedFolders_Call struct {
	*mock.Call
}

// SaveCollapsedFolders is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []domain.FolderID
func (_e *MockCollapsedFoldersSaver_Expecter) SaveCollapsedFolders(ctx any, ids any) *MockCollapsedFoldersSaver_SaveCollapsedFolders_Call {
	return &MockCollapsedFoldersSaver_SaveCollapsedFolders_Call{Call: _e.mock.On("SaveCollapsedFolders", ctx, ids)}
}

func (_c *MockCollapsedFoldersSaver_SaveCollapsedFolders_Call) Run(run func(ctx context.Context, ids []domain.FolderID)) *MockCollapsedFoldersSaver_SaveCollapsedFolders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.FolderID
		if args[1] != nil {
			arg1 = args[1].([]domain.FolderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCollapsedFoldersSaver_SaveCollapsedFolders_Call) Return(err error) *MockCollapsedFoldersSaver_SaveCollapsedFolders_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCollapsedFoldersSaver_SaveCollapsedFolders_Call) RunAndReturn(run func(ctx context.Context, ids []domain.FolderID) error) *MockCollapsedFoldersSaver_SaveCollapsedFolders_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExternalEditor creates a new instance of MockExternalEditor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExternalEditor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExternalEditor {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockExternalEditor{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockExternalEditor is an autogenerated mock type for the ExternalEditor type
type MockExternalEditor struct {
	mock.Mock
}

type MockExternalEditor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExternalEditor) EXPECT() *MockExternalEditor_Expecter {
	return &MockExternalEditor_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type MockExternalEditor
func (_mock *MockExternalEditor) Open(ctx context.Context, fileName string, content string) (tui.EditorRun, error) {
	ret := _mock.Called(ctx, fileName, content)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 tui.EditorRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (tui.EditorRun, error)); ok {
		return returnFunc(ctx, fileName, content)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) tui.EditorRun); ok {
		r0 = returnFunc(ctx, fileName, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tui.EditorRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, fileName, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExternalEditor_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockExternalEditor_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - fileName string
//   - content string
func (_e *MockExternalEditor_Expecter) Open(ctx any, fileName any, content any) *MockExternalEditor_Open_Call {
	return &MockExternalEditor_Open_Call{Call: _e.mock.On("Open", ctx, fileName, content)}
}

func (_c *MockExternalEditor_Open_Call) Run(run func(ctx context.Context, fileName string, content string)) *MockExternalEditor_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExternalEditor_Open_Call) Return(editorRun tui.EditorRun, err error) *MockExternalEditor_Open_Call {
	_c.Call.Return(editorRun, err)
	return _c
}

func (_c *MockExternalEditor_Open_Call) RunAndReturn(run func(ctx context.Context, fileName string, content string) (tui.EditorRun, error)) *MockExternalEditor_Open_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFolderCreator creates a new instance of MockFolderCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFolderCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFolderCreator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFolderCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFolderCreator is an autogenerated mock type for the FolderCreator type
type MockFolderCreator struct {
	mock.Mock
}

type MockFolderCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFolderCreator) EXPECT() *MockFolderCreator_Expecter {
	return &MockFolderCreator_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockFolderCreator
func (_mock *MockFolderCreator) Run(ctx context.Context, in folder.CreateInput) (domain.Folder, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 domain.Folder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, folder.CreateInput) (domain.Folder, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, folder.CreateInput) domain.Folder); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Folder)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, folder.CreateInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFolderCreator_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockFolderCreator_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in folder.CreateInput
func (_e *MockFolderCreator_Expecter) Run(ctx any, in any) *MockFolderCreator_Run_Call {
	return &MockFolderCreator_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockFolderCreator_Run_Call) Run(run func(ctx context.Context, in folder.CreateInput)) *MockFolderCreator_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 folder.CreateInput
		if args[1] != nil {
			arg1 = args[1].(folder.CreateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFolderCreator_Run_Call) Return(folder1 domain.Folder, err error) *MockFolderCreator_Run_Call {
	_c.Call.Return(folder1, err)
	return _c
}

func (_c *MockFolderCreator_Run_Call) RunAndReturn(run func(ctx context.Context, in folder.CreateInput) (domain.Folder, error)) *MockFolderCreator_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFolderDefaultLanguageSetter creates a new instance of MockFolderDefaultLanguageSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFolderDefaultLanguageSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFolderDefaultLanguageSetter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFolderDefaultLanguageSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFolderDefaultLanguageSetter is an autogenerated mock type for the FolderDefaultLanguageSetter type
type MockFolderDefaultLanguageSetter struct {
	mock.Mock
}

type MockFolderDefaultLanguageSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFolderDefaultLanguageSetter) EXPECT() *MockFolderDefaultLanguageSetter_Expecter {
	return &MockFolderDefaultLanguageSetter_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockFolderDefaultLanguageSetter
func (_mock *MockFolderDefaultLanguageSetter) Run(ctx context.Context, in folder.SetDefaultLanguageInput) (domain.Folder, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 domain.Folder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, folder.SetDefaultLanguageInput) (domain.Folder, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, folder.SetDefaultLanguageInput) domain.Folder); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Folder)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, folder.SetDefaultLanguageInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFolderDefaultLanguageSetter_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockFolderDefaultLanguageSetter_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in folder.SetDefaultLanguageInput
func (_e *MockFolderDefaultLanguageSetter_Expecter) Run(ctx any, in any) *MockFolderDefaultLanguageSetter_Run_Call {
	return &MockFolderDefaultLanguageSetter_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockFolderDefaultLanguageSetter_Run_Call) Run(run func(ctx context.Context, in folder.SetDefaultLanguageInput)) *MockFolderDefaultLanguageSetter_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 folder.SetDefaultLanguageInput
		if args[1] != nil {
			arg1 = args[1].(folder.SetDefaultLanguageInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFolderDefaultLanguageSetter_Run_Call) Return(folder1 domain.Folder, err error) *MockFolderDefaultLanguageSetter_Run_Call {
	_c.Call.Return(folder1, err)
	return _c
}

func (_c *MockFolderDefaultLanguageSetter_Run_Call) RunAndReturn(run func(ctx context.Context, in folder.SetDefaultLanguageInput) (domain.Folder, error)) *MockFolderDefaultLanguageSetter_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFolderDeletePreviewer creates a new instance of MockFolderDeletePreviewer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFolderDeletePreviewer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFolderDeletePreviewer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFolderDeletePreviewer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFolderDeletePreviewer is an autogenerated mock type for the FolderDeletePreviewer type
type MockFolderDeletePreviewer struct {
	mock.Mock
}

type MockFolderDeletePreviewer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFolderDeletePreviewer) EXPECT() *MockFolderDeletePreviewer_Expecter {
	return &MockFolderDeletePreviewer_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockFolderDeletePreviewer
func (_mock *MockFolderDeletePreviewer) Run(ctx context.Context, in folder.PreviewDeleteInput) (folder.DeletePreview, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 folder.DeletePreview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, folder.PreviewDeleteInput) (folder.DeletePreview, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, folder.PreviewDeleteInput) folder.DeletePreview); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(folder.DeletePreview)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, folder.PreviewDeleteInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFolderDeletePreviewer_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockFolderDeletePreviewer_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in folder.PreviewDeleteInput
func (_e *MockFolderDeletePreviewer_Expecter) Run(ctx any, in any) *MockFolderDeletePreviewer_Run_Call {
	return &MockFolderDeletePreviewer_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockFolderDeletePreviewer_Run_Call) Run(run func(ctx context.Context, in folder.PreviewDeleteInput)) *MockFolderDeletePreviewer_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 folder.PreviewDeleteInput
		if args[1] != nil {
			arg1 = args[1].(folder.PreviewDeleteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFolderDeletePreviewer_Run_Call) Return(deletePreview folder.DeletePreview, err error) *MockFolderDeletePreviewer_Run_Call {
	_c.Call.Return(deletePreview, err)
	return _c
}

func (_c *MockFolderDeletePreviewer_Run_Call) RunAndReturn(run func(ctx context.Context, in folder.PreviewDeleteInput) (folder.DeletePreview, error)) *MockFolderDeletePreviewer_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFolderDeleter creates a new instance of MockFolderDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFolderDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFolderDeleter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFolderDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFolderDeleter is an autogenerated mock type for the FolderDeleter type
type MockFolderDeleter struct {
	mock.Mock
}

type MockFolderDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFolderDeleter) EXPECT() *MockFolderDeleter_Expecter {
	return &MockFolderDeleter_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockFolderDeleter
func (_mock *MockFolderDeleter) Run(ctx context.Context, in folder.DeleteInput) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, folder.DeleteInput) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFolderDeleter_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockFolderDeleter_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in folder.DeleteInput
func (_e *MockFolderDeleter_Expecter) Run(ctx any, in any) *MockFolderDeleter_Run_Call {
	return &MockFolderDeleter_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockFolderDeleter_Run_Call) Run(run func(ctx context.Context, in folder.DeleteInput)) *MockFolderDeleter_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 folder.DeleteInput
		if args[1] != nil {
			arg1 = args[1].(folder.DeleteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFolderDeleter_Run_Call) Return(err error) *MockFolderDeleter_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFolderDeleter_Run_Call) RunAndReturn(run func(ctx context.Context, in folder.DeleteInput) error) *MockFolderDeleter_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFolderMover creates a new instance of MockFolderMover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFolderMover(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFolderMover {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFolderMover{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFolderMover is an autogenerated mock type for the FolderMover type
type MockFolderMover struct {
	mock.Mock
}

type MockFolderMover_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFolderMover) EXPECT() *MockFolderMover_Expecter {
	return &MockFolderMover_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockFolderMover
func (_mock *MockFolderMover) Run(ctx context.Context, in folder.MoveInput) (domain.Folder, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 domain.Folder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, folder.MoveInput) (domain.Folder, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, folder.MoveInput) domain.Folder); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Folder)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, folder.MoveInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFolderMover_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockFolderMover_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in folder.MoveInput
func (_e *MockFolderMover_Expecter) Run(ctx any, in any) *MockFolderMover_Run_Call {
	return &MockFolderMover_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockFolderMover_Run_Call) Run(run func(ctx context.Context, in folder.MoveInput)) *MockFolderMover_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 folder.MoveInput
		if args[1] != nil {
			arg1 = args[1].(folder.MoveInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFolderMover_Run_Call) Return(folder1 domain.Folder, err error) *MockFolderMover_Run_Call {
	_c.Call.Return(folder1, err)
	return _c
}

func (_c *MockFolderMover_Run_Call) RunAndReturn(run func(ctx context.Context, in folder.MoveInput) (domain.Folder, error)) *MockFolderMover_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFolderRenamer creates a new instance of MockFolderRenamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFolderRenamer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFolderRenamer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFolderRenamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFolderRenamer is an autogenerated mock type for the FolderRenamer type
type MockFolderRenamer struct {
	mock.Mock
}

type MockFolderRenamer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFolderRenamer) EXPECT() *MockFolderRenamer_Expecter {
	return &MockFolderRenamer_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockFolderRenamer
func (_mock *MockFolderRenamer) Run(ctx context.Context, in folder.RenameInput) (domain.Folder, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 domain.Folder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, folder.RenameInput) (domain.Folder, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, folder.RenameInput) domain.Folder); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Folder)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, folder.RenameInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFolderRenamer_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockFolderRenamer_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in folder.RenameInput
func (_e *MockFolderRenamer_Expecter) Run(ctx any, in any) *MockFolderRenamer_Run_Call {
	return &MockFolderRenamer_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockFolderRenamer_Run_Call) Run(run func(ctx context.Context, in folder.RenameInput)) *MockFolderRenamer_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 folder.RenameInput
		if args[1] != nil {
			arg1 = args[1].(folder.RenameInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFolderRenamer_Run_Call) Return(folder1 domain.Folder, err error) *MockFolderRenamer_Run_Call {
	_c.Call.Return(folder1, err)
	return _c
}

func (_c *MockFolderRenamer_Run_Call) RunAndReturn(run func(ctx context.Context, in folder.RenameInput) (domain.Folder, error)) *MockFolderRenamer_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFolderSnippetsLister creates a new instance of MockFolderSnippetsLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFolderSnippetsLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFolderSnippetsLister {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFolderSnippetsLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFolderSnippetsLister is an autogenerated mock type for the FolderSnippetsLister type
type MockFolderSnippetsLister struct {
	mock.Mock
}

type MockFolderSnippetsLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFolderSnippetsLister) EXPECT() *MockFolderSnippetsLister_Expecter {
	return &MockFolderSnippetsLister_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockFolderSnippetsLister
func (_mock *MockFolderSnippetsLister) Run(ctx context.Context, in browse.SnippetsInFolderInput) ([]domain.Snippet, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 []domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, browse.SnippetsInFolderInput) ([]domain.Snippet, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, browse.SnippetsInFolderInput) []domain.Snippet); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Snippet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, browse.SnippetsInFolderInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFolderSnippetsLister_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockFolderSnippetsLister_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in browse.SnippetsInFolderInput
func (_e *MockFolderSnippetsLister_Expecter) Run(ctx any, in any) *MockFolderSnippetsLister_Run_Call {
	return &MockFolderSnippetsLister_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockFolderSnippetsLister_Run_Call) Run(run func(ctx context.Context, in browse.SnippetsInFolderInput)) *MockFolderSnippetsLister_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 browse.SnippetsInFolderInput
		if args[1] != nil {
			arg1 = args[1].(browse.SnippetsInFolderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFolderSnippetsLister_Run_Call) Return(snippets []domain.Snippet, err error) *MockFolderSnippetsLister_Run_Call {
	_c.Call.Return(snippets, err)
	return _c
}

func (_c *MockFolderSnippetsLister_Run_Call) RunAndReturn(run func(ctx context.Context, in browse.SnippetsInFolderInput) ([]domain.Snippet, error)) *MockFolderSnippetsLister_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFolderTreeLister creates a new instance of MockFolderTreeLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFolderTreeLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFolderTreeLister {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFolderTreeLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFolderTreeLister is an autogenerated mock type for the FolderTreeLister type
type MockFolderTreeLister struct {
	mock.Mock
}

type MockFolderTreeLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFolderTreeLister) EXPECT() *MockFolderTreeLister_Expecter {
	return &MockFolderTreeLister_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockFolderTreeLister
func (_mock *MockFolderTreeLister) Run(ctx context.Context, in browse.FolderTreeInput) (browse.Tree, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 browse.Tree
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, browse.FolderTreeInput) (browse.Tree, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, browse.FolderTreeInput) browse.Tree); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(browse.Tree)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, browse.FolderTreeInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFolderTreeLister_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockFolderTreeLister_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in browse.FolderTreeInput
func (_e *MockFolderTreeLister_Expecter) Run(ctx any, in any) *MockFolderTreeLister_Run_Call {
	return &MockFolderTreeLister_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockFolderTreeLister_Run_Call) Run(run func(ctx context.Context, in browse.FolderTreeInput)) *MockFolderTreeLister_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 browse.FolderTreeInput
		if args[1] != nil {
			arg1 = args[1].(browse.FolderTreeInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFolderTreeLister_Run_Call) Return(tree browse.Tree, err error) *MockFolderTreeLister_Run_Call {
	_c.Call.Return(tree, err)
	return _c
}

func (_c *MockFolderTreeLister_Run_Call) RunAndReturn(run func(ctx context.Context, in browse.FolderTreeInput) (browse.Tree, error)) *MockFolderTreeLister_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnippetCapturer creates a new instance of MockSnippetCapturer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnippetCapturer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnippetCapturer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSnippetCapturer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSnippetCapturer is an autogenerated mock type for the SnippetCapturer type
type MockSnippetCapturer struct {
	mock.Mock
}

type MockSnippetCapturer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnippetCapturer) EXPECT() *MockSnippetCapturer_Expecter {
	return &MockSnippetCapturer_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockSnippetCapturer
func (_mock *MockSnippetCapturer) Run(ctx context.Context, in snippet.CaptureInput) (value.Content, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 value.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.CaptureInput) (value.Content, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.CaptureInput) value.Content); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(value.Content)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, snippet.CaptureInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnippetCapturer_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockSnippetCapturer_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in snippet.CaptureInput
func (_e *MockSnippetCapturer_Expecter) Run(ctx any, in any) *MockSnippetCapturer_Run_Call {
	return &MockSnippetCapturer_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockSnippetCapturer_Run_Call) Run(run func(ctx context.Context, in snippet.CaptureInput)) *MockSnippetCapturer_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snippet.CaptureInput
		if args[1] != nil {
			arg1 = args[1].(snippet.CaptureInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnippetCapturer_Run_Call) Return(content value.Content, err error) *MockSnippetCapturer_Run_Call {
	_c.Call.Return(content, err)
	return _c
}

func (_c *MockSnippetCapturer_Run_Call) RunAndReturn(run func(ctx context.Context, in snippet.CaptureInput) (value.Content, error)) *MockSnippetCapturer_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnippetCopier creates a new instance of MockSnippetCopier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnippetCopier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnippetCopier {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSnippetCopier{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSnippetCopier is an autogenerated mock type for the SnippetCopier type
type MockSnippetCopier struct {
	mock.Mock
}

type MockSnippetCopier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnippetCopier) EXPECT() *MockSnippetCopier_Expecter {
	return &MockSnippetCopier_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockSnippetCopier
func (_mock *MockSnippetCopier) Run(ctx context.Context, in snippet.CopyInput) (snippet.CopyResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 snippet.CopyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.CopyInput) (snippet.CopyResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.CopyInput) snippet.CopyResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(snippet.CopyResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, snippet.CopyInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnippetCopier_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockSnippetCopier_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in snippet.CopyInput
func (_e *MockSnippetCopier_Expecter) Run(ctx any, in any) *MockSnippetCopier_Run_Call {
	return &MockSnippetCopier_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockSnippetCopier_Run_Call) Run(run func(ctx context.Context, in snippet.CopyInput)) *MockSnippetCopier_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snippet.CopyInput
		if args[1] != nil {
			arg1 = args[1].(snippet.CopyInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnippetCopier_Run_Call) Return(copyResult snippet.CopyResult, err error) *MockSnippetCopier_Run_Call {
	_c.Call.Return(copyResult, err)
	return _c
}

func (_c *MockSnippetCopier_Run_Call) RunAndReturn(run func(ctx context.Context, in snippet.CopyInput) (snippet.CopyResult, error)) *MockSnippetCopier_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnippetCreator creates a new instance of MockSnippetCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnippetCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnippetCreator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSnippetCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSnippetCreator is an autogenerated mock type for the SnippetCreator type
type MockSnippetCreator struct {
	mock.Mock
}

type MockSnippetCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnippetCreator) EXPECT() *MockSnippetCreator_Expecter {
	return &MockSnippetCreator_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockSnippetCreator
func (_mock *MockSnippetCreator) Run(ctx context.Context, in snippet.CreateInput) (domain.Snippet, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.CreateInput) (domain.Snippet, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.CreateInput) domain.Snippet); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Snippet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, snippet.CreateInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnippetCreator_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockSnippetCreator_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in snippet.CreateInput
func (_e *MockSnippetCreator_Expecter) Run(ctx any, in any) *MockSnippetCreator_Run_Call {
	return &MockSnippetCreator_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockSnippetCreator_Run_Call) Run(run func(ctx context.Context, in snippet.CreateInput)) *MockSnippetCreator_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snippet.CreateInput
		if args[1] != nil {
			arg1 = args[1].(snippet.CreateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnippetCreator_Run_Call) Return(snippet1 domain.Snippet, err error) *MockSnippetCreator_Run_Call {
	_c.Call.Return(snippet1, err)
	return _c
}

func (_c *MockSnippetCreator_Run_Call) RunAndReturn(run func(ctx context.Context, in snippet.CreateInput) (domain.Snippet, error)) *MockSnippetCreator_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnippetDeleter creates a new instance of MockSnippetDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnippetDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnippetDeleter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSnippetDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSnippetDeleter is an autogenerated mock type for the SnippetDeleter type
type MockSnippetDeleter struct {
	mock.Mock
}

type MockSnippetDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnippetDeleter) EXPECT() *MockSnippetDeleter_Expecter {
	return &MockSnippetDeleter_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockSnippetDeleter
func (_mock *MockSnippetDeleter) Run(ctx context.Context, in snippet.DeleteInput) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.DeleteInput) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSnippetDeleter_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockSnippetDeleter_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in snippet.DeleteInput
func (_e *MockSnippetDeleter_Expecter) Run(ctx any, in any) *MockSnippetDeleter_Run_Call {
	return &MockSnippetDeleter_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockSnippetDeleter_Run_Call) Run(run func(ctx context.Context, in snippet.DeleteInput)) *MockSnippetDeleter_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snippet.DeleteInput
		if args[1] != nil {
			arg1 = args[1].(snippet.DeleteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnippetDeleter_Run_Call) Return(err error) *MockSnippetDeleter_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSnippetDeleter_Run_Call) RunAndReturn(run func(ctx context.Context, in snippet.DeleteInput) error) *MockSnippetDeleter_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnippetDuplicator creates a new instance of MockSnippetDuplicator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnippetDuplicator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnippetDuplicator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSnippetDuplicator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSnippetDuplicator is an autogenerated mock type for the SnippetDuplicator type
type MockSnippetDuplicator struct {
	mock.Mock
}

type MockSnippetDuplicator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnippetDuplicator) EXPECT() *MockSnippetDuplicator_Expecter {
	return &MockSnippetDuplicator_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockSnippetDuplicator
func (_mock *MockSnippetDuplicator) Run(ctx context.Context, in snippet.DuplicateInput) (domain.Snippet, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.DuplicateInput) (domain.Snippet, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.DuplicateInput) domain.Snippet); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Snippet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, snippet.DuplicateInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnippetDuplicator_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockSnippetDuplicator_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in snippet.DuplicateInput
func (_e *MockSnippetDuplicator_Expecter) Run(ctx any, in any) *MockSnippetDuplicator_Run_Call {
	return &MockSnippetDuplicator_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockSnippetDuplicator_Run_Call) Run(run func(ctx context.Context, in snippet.DuplicateInput)) *MockSnippetDuplicator_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snippet.DuplicateInput
		if args[1] != nil {
			arg1 = args[1].(snippet.DuplicateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnippetDuplicator_Run_Call) Return(snippet1 domain.Snippet, err error) *MockSnippetDuplicator_Run_Call {
	_c.Call.Return(snippet1, err)
	return _c
}

func (_c *MockSnippetDuplicator_Run_Call) RunAndReturn(run func(ctx context.Context, in snippet.DuplicateInput) (domain.Snippet, error)) *MockSnippetDuplicator_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnippetMover creates a new instance of MockSnippetMover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnippetMover(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnippetMover {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSnippetMover{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSnippetMover is an autogenerated mock type for the SnippetMover type
type MockSnippetMover struct {
	mock.Mock
}

type MockSnippetMover_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnippetMover) EXPECT() *MockSnippetMover_Expecter {
	return &MockSnippetMover_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockSnippetMover
func (_mock *MockSnippetMover) Run(ctx context.Context, in snippet.MoveInput) (domain.Snippet, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.MoveInput) (domain.Snippet, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.MoveInput) domain.Snippet); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Snippet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, snippet.MoveInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnippetMover_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockSnippetMover_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in snippet.MoveInput
func (_e *MockSnippetMover_Expecter) Run(ctx any, in any) *MockSnippetMover_Run_Call {
	return &MockSnippetMover_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockSnippetMover_Run_Call) Run(run func(ctx context.Context, in snippet.MoveInput)) *MockSnippetMover_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snippet.MoveInput
		if args[1] != nil {
			arg1 = args[1].(snippet.MoveInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnippetMover_Run_Call) Return(snippet1 domain.Snippet, err error) *MockSnippetMover_Run_Call {
	_c.Call.Return(snippet1, err)
	return _c
}

func (_c *MockSnippetMover_Run_Call) RunAndReturn(run func(ctx context.Context, in snippet.MoveInput) (domain.Snippet, error)) *MockSnippetMover_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnippetSearcher creates a new instance of MockSnippetSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnippetSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnippetSearcher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSnippetSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSnippetSearcher is an autogenerated mock type for the SnippetSearcher type
type MockSnippetSearcher struct {
	mock.Mock
}

type MockSnippetSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnippetSearcher) EXPECT() *MockSnippetSearcher_Expecter {
	return &MockSnippetSearcher_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockSnippetSearcher
func (_mock *MockSnippetSearcher) Run(ctx context.Context, in search.QueryInput) ([]domain.SearchHit, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 []domain.SearchHit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, search.QueryInput) ([]domain.SearchHit, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, search.QueryInput) []domain.SearchHit); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SearchHit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, search.QueryInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnippetSearcher_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockSnippetSearcher_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in search.QueryInput
func (_e *MockSnippetSearcher_Expecter) Run(ctx any, in any) *MockSnippetSearcher_Run_Call {
	return &MockSnippetSearcher_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockSnippetSearcher_Run_Call) Run(run func(ctx context.Context, in search.QueryInput)) *MockSnippetSearcher_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 search.QueryInput
		if args[1] != nil {
			arg1 = args[1].(search.QueryInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnippetSearcher_Run_Call) Return(searchHits []domain.SearchHit, err error) *MockSnippetSearcher_Run_Call {
	_c.Call.Return(searchHits, err)
	return _c
}

func (_c *MockSnippetSearcher_Run_Call) RunAndReturn(run func(ctx context.Context, in search.QueryInput) ([]domain.SearchHit, error)) *MockSnippetSearcher_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnippetUpdater creates a new instance of MockSnippetUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnippetUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnippetUpdater {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSnippetUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSnippetUpdater is an autogenerated mock type for the SnippetUpdater type
type MockSnippetUpdater struct {
	mock.Mock
}

type MockSnippetUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnippetUpdater) EXPECT() *MockSnippetUpdater_Expecter {
	return &MockSnippetUpdater_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockSnippetUpdater
func (_mock *MockSnippetUpdater) Run(ctx context.Context, in snippet.UpdateInput) (domain.Snippet, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.UpdateInput) (domain.Snippet, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.UpdateInput) domain.Snippet); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Snippet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, snippet.UpdateInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnippetUpdater_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockSnippetUpdater_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in snippet.UpdateInput
func (_e *MockSnippetUpdater_Expecter) Run(ctx any, in any) *MockSnippetUpdater_Run_Call {
	return &MockSnippetUpdater_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockSnippetUpdater_Run_Call) Run(run func(ctx context.Context, in snippet.UpdateInput)) *MockSnippetUpdater_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snippet.UpdateInput
		if args[1] != nil {
			arg1 = args[1].(snippet.UpdateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnippetUpdater_Run_Call) Return(snippet1 domain.Snippet, err error) *MockSnippetUpdater_Run_Call {
	_c.Call.Return(snippet1, err)
	return _c
}

func (_c *MockSnippetUpdater_Run_Call) RunAndReturn(run func(ctx context.Context, in snippet.UpdateInput) (domain.Snippet, error)) *MockSnippetUpdater_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSortOrderSaver creates a new instance of MockSortOrderSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSortOrderSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSortOrderSaver {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSortOrderSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSortOrderSaver is an autogenerated mock type for the SortOrderSaver type
type MockSortOrderSaver struct {
	mock.Mock
}

type MockSortOrderSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSortOrderSaver) EXPECT() *MockSortOrderSaver_Expecter {
	return &MockSortOrderSaver_Expecter{mock: &_m.Mock}
}

// SaveSortOrder provides a mock function for the type MockSortOrderSaver
func (_mock *MockSortOrderSaver) SaveSortOrder(ctx context.Context, order domain.SortOrder) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SaveSortOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SortOrder) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSortOrderSaver_SaveSortOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSortOrder'
type MockSortOrderSaver_SaveSortOrder_Call struct {
	*mock.Call
}

// SaveSortOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order domain.SortOrder
func (_e *MockSortOrderSaver_Expecter) SaveSortOrder(ctx any, order any) *MockSortOrderSaver_SaveSortOrder_Call {
	return &MockSortOrderSaver_SaveSortOrder_Call{Call: _e.mock.On("SaveSortOrder", ctx, order)}
}

func (_c *MockSortOrderSaver_SaveSortOrder_Call) Run(run func(ctx context.Context, order domain.SortOrder)) *MockSortOrderSaver_SaveSortOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SortOrder
		if args[1] != nil {
			arg1 = args[1].(domain.SortOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSortOrderSaver_SaveSortOrder_Call) Return(err error) *MockSortOrderSaver_SaveSortOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSortOrderSaver_SaveSortOrder_Call) RunAndReturn(run func(ctx context.Context, order domain.SortOrder) error) *MockSortOrderSaver_SaveSortOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagCreator creates a new instance of MockTagCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagCreator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTagCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTagCreator is an autogenerated mock type for the TagCreator type
type MockTagCreator struct {
	mock.Mock
}

type MockTagCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagCreator) EXPECT() *MockTagCreator_Expecter {
	return &MockTagCreator_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockTagCreator
func (_mock *MockTagCreator) Run(ctx context.Context, in tag.CreateInput) (domain.Tag, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 domain.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tag.CreateInput) (domain.Tag, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, tag.CreateInput) domain.Tag); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Tag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, tag.CreateInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagCreator_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTagCreator_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in tag.CreateInput
func (_e *MockTagCreator_Expecter) Run(ctx any, in any) *MockTagCreator_Run_Call {
	return &MockTagCreator_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockTagCreator_Run_Call) Run(run func(ctx context.Context, in tag.CreateInput)) *MockTagCreator_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tag.CreateInput
		if args[1] != nil {
			arg1 = args[1].(tag.CreateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagCreator_Run_Call) Return(tag1 domain.Tag, err error) *MockTagCreator_Run_Call {
	_c.Call.Return(tag1, err)
	return _c
}

func (_c *MockTagCreator_Run_Call) RunAndReturn(run func(ctx context.Context, in tag.CreateInput) (domain.Tag, error)) *MockTagCreator_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagDeletePreviewer creates a new instance of MockTagDeletePreviewer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagDeletePreviewer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagDeletePreviewer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTagDeletePreviewer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTagDeletePreviewer is an autogenerated mock type for the TagDeletePreviewer type
type MockTagDeletePreviewer struct {
	mock.Mock
}

type MockTagDeletePreviewer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagDeletePreviewer) EXPECT() *MockTagDeletePreviewer_Expecter {
	return &MockTagDeletePreviewer_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockTagDeletePreviewer
func (_mock *MockTagDeletePreviewer) Run(ctx context.Context, in tag.PreviewDeleteInput) (tag.DeletePreview, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 tag.DeletePreview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tag.PreviewDeleteInput) (tag.DeletePreview, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, tag.PreviewDeleteInput) tag.DeletePreview); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(tag.DeletePreview)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, tag.PreviewDeleteInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagDeletePreviewer_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTagDeletePreviewer_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in tag.PreviewDeleteInput
func (_e *MockTagDeletePreviewer_Expecter) Run(ctx any, in any) *MockTagDeletePreviewer_Run_Call {
	return &MockTagDeletePreviewer_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockTagDeletePreviewer_Run_Call) Run(run func(ctx context.Context, in tag.PreviewDeleteInput)) *MockTagDeletePreviewer_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tag.PreviewDeleteInput
		if args[1] != nil {
			arg1 = args[1].(tag.PreviewDeleteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagDeletePreviewer_Run_Call) Return(deletePreview tag.DeletePreview, err error) *MockTagDeletePreviewer_Run_Call {
	_c.Call.Return(deletePreview, err)
	return _c
}

func (_c *MockTagDeletePreviewer_Run_Call) RunAndReturn(run func(ctx context.Context, in tag.PreviewDeleteInput) (tag.DeletePreview, error)) *MockTagDeletePreviewer_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagDeleter creates a new instance of MockTagDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagDeleter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTagDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTagDeleter is an autogenerated mock type for the TagDeleter type
type MockTagDeleter struct {
	mock.Mock
}

type MockTagDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagDeleter) EXPECT() *MockTagDeleter_Expecter {
	return &MockTagDeleter_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockTagDeleter
func (_mock *MockTagDeleter) Run(ctx context.Context, in tag.DeleteInput) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tag.DeleteInput) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagDeleter_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTagDeleter_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in tag.DeleteInput
func (_e *MockTagDeleter_Expecter) Run(ctx any, in any) *MockTagDeleter_Run_Call {
	return &MockTagDeleter_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockTagDeleter_Run_Call) Run(run func(ctx context.Context, in tag.DeleteInput)) *MockTagDeleter_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tag.DeleteInput
		if args[1] != nil {
			arg1 = args[1].(tag.DeleteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagDeleter_Run_Call) Return(err error) *MockTagDeleter_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagDeleter_Run_Call) RunAndReturn(run func(ctx context.Context, in tag.DeleteInput) error) *MockTagDeleter_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagLister creates a new instance of MockTagLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagLister {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTagLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTagLister is an autogenerated mock type for the TagLister type
type MockTagLister struct {
	mock.Mock
}

type MockTagLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagLister) EXPECT() *MockTagLister_Expecter {
	return &MockTagLister_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockTagLister
func (_mock *MockTagLister) Run(ctx context.Context, in browse.TagListInput) ([]browse.TagCount, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 []browse.TagCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, browse.TagListInput) ([]browse.TagCount, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, browse.TagListInput) []browse.TagCount); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]browse.TagCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, browse.TagListInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagLister_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTagLister_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in browse.TagListInput
func (_e *MockTagLister_Expecter) Run(ctx any, in any) *MockTagLister_Run_Call {
	return &MockTagLister_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockTagLister_Run_Call) Run(run func(ctx context.Context, in browse.TagListInput)) *MockTagLister_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 browse.TagListInput
		if args[1] != nil {
			arg1 = args[1].(browse.TagListInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagLister_Run_Call) Return(tagCounts []browse.TagCount, err error) *MockTagLister_Run_Call {
	_c.Call.Return(tagCounts, err)
	return _c
}

func (_c *MockTagLister_Run_Call) RunAndReturn(run func(ctx context.Context, in browse.TagListInput) ([]browse.TagCount, error)) *MockTagLister_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagRenamer creates a new instance of MockTagRenamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagRenamer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagRenamer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTagRenamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTagRenamer is an autogenerated mock type for the TagRenamer type
type MockTagRenamer struct {
	mock.Mock
}

type MockTagRenamer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagRenamer) EXPECT() *MockTagRenamer_Expecter {
	return &MockTagRenamer_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockTagRenamer
func (_mock *MockTagRenamer) Run(ctx context.Context, in tag.RenameInput) (domain.Tag, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 domain.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tag.RenameInput) (domain.Tag, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, tag.RenameInput) domain.Tag); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Tag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, tag.RenameInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagRenamer_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTagRenamer_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in tag.RenameInput
func (_e *MockTagRenamer_Expecter) Run(ctx any, in any) *MockTagRenamer_Run_Call {
	return &MockTagRenamer_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockTagRenamer_Run_Call) Run(run func(ctx context.Context, in tag.RenameInput)) *MockTagRenamer_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tag.RenameInput
		if args[1] != nil {
			arg1 = args[1].(tag.RenameInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagRenamer_Run_Call) Return(tag1 domain.Tag, err error) *MockTagRenamer_Run_Call {
	_c.Call.Return(tag1, err)
	return _c
}

func (_c *MockTagRenamer_Run_Call) RunAndReturn(run func(ctx context.Context, in tag.RenameInput) (domain.Tag, error)) *MockTagRenamer_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagSnippetsLister creates a new instance of MockTagSnippetsLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagSnippetsLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagSnippetsLister {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTagSnippetsLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTagSnippetsLister is an autogenerated mock type for the TagSnippetsLister type
type MockTagSnippetsLister struct {
	mock.Mock
}

type MockTagSnippetsLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagSnippetsLister) EXPECT() *MockTagSnippetsLister_Expecter {
	return &MockTagSnippetsLister_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockTagSnippetsLister
func (_mock *MockTagSnippetsLister) Run(ctx context.Context, in browse.SnippetsWithTagInput) ([]domain.Snippet, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 []domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, browse.SnippetsWithTagInput) ([]domain.Snippet, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, browse.SnippetsWithTagInput) []domain.Snippet); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Snippet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, browse.SnippetsWithTagInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagSnippetsLister_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTagSnippetsLister_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in browse.SnippetsWithTagInput
func (_e *MockTagSnippetsLister_Expecter) Run(ctx any, in any) *MockTagSnippetsLister_Run_Call {
	return &MockTagSnippetsLister_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockTagSnippetsLister_Run_Call) Run(run func(ctx context.Context, in browse.SnippetsWithTagInput)) *MockTagSnippetsLister_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 browse.SnippetsWithTagInput
		if args[1] != nil {
			arg1 = args[1].(browse.SnippetsWithTagInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagSnippetsLister_Run_Call) Return(snippets []domain.Snippet, err error) *MockTagSnippetsLister_Run_Call {
	_c.Call.Return(snippets, err)
	return _c
}

func (_c *MockTagSnippetsLister_Run_Call) RunAndReturn(run func(ctx context.Context, in browse.SnippetsWithTagInput) ([]domain.Snippet, error)) *MockTagSnippetsLister_Run_Call {
	_c.Call.Return(run)
	return _c
}
