// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tui_test

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/app/browse"
	"github.com/DannyFestor/TuiSnip/internal/app/snippet"
	"github.com/DannyFestor/TuiSnip/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFolderSnippetsLister creates a new instance of MockFolderSnippetsLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFolderSnippetsLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFolderSnippetsLister {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFolderSnippetsLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFolderSnippetsLister is an autogenerated mock type for the FolderSnippetsLister type
type MockFolderSnippetsLister struct {
	mock.Mock
}

type MockFolderSnippetsLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFolderSnippetsLister) EXPECT() *MockFolderSnippetsLister_Expecter {
	return &MockFolderSnippetsLister_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockFolderSnippetsLister
func (_mock *MockFolderSnippetsLister) Run(ctx context.Context, in browse.SnippetsInFolderInput) ([]domain.Snippet, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 []domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, browse.SnippetsInFolderInput) ([]domain.Snippet, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, browse.SnippetsInFolderInput) []domain.Snippet); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Snippet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, browse.SnippetsInFolderInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFolderSnippetsLister_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockFolderSnippetsLister_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in browse.SnippetsInFolderInput
func (_e *MockFolderSnippetsLister_Expecter) Run(ctx any, in any) *MockFolderSnippetsLister_Run_Call {
	return &MockFolderSnippetsLister_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockFolderSnippetsLister_Run_Call) Run(run func(ctx context.Context, in browse.SnippetsInFolderInput)) *MockFolderSnippetsLister_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 browse.SnippetsInFolderInput
		if args[1] != nil {
			arg1 = args[1].(browse.SnippetsInFolderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFolderSnippetsLister_Run_Call) Return(snippets []domain.Snippet, err error) *MockFolderSnippetsLister_Run_Call {
	_c.Call.Return(snippets, err)
	return _c
}

func (_c *MockFolderSnippetsLister_Run_Call) RunAndReturn(run func(ctx context.Context, in browse.SnippetsInFolderInput) ([]domain.Snippet, error)) *MockFolderSnippetsLister_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnippetCopier creates a new instance of MockSnippetCopier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnippetCopier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnippetCopier {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSnippetCopier{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSnippetCopier is an autogenerated mock type for the SnippetCopier type
type MockSnippetCopier struct {
	mock.Mock
}

type MockSnippetCopier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnippetCopier) EXPECT() *MockSnippetCopier_Expecter {
	return &MockSnippetCopier_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockSnippetCopier
func (_mock *MockSnippetCopier) Run(ctx context.Context, in snippet.CopyInput) (snippet.CopyResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 snippet.CopyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.CopyInput) (snippet.CopyResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, snippet.CopyInput) snippet.CopyResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(snippet.CopyResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, snippet.CopyInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnippetCopier_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockSnippetCopier_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in snippet.CopyInput
func (_e *MockSnippetCopier_Expecter) Run(ctx any, in any) *MockSnippetCopier_Run_Call {
	return &MockSnippetCopier_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockSnippetCopier_Run_Call) Run(run func(ctx context.Context, in snippet.CopyInput)) *MockSnippetCopier_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snippet.CopyInput
		if args[1] != nil {
			arg1 = args[1].(snippet.CopyInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnippetCopier_Run_Call) Return(copyResult snippet.CopyResult, err error) *MockSnippetCopier_Run_Call {
	_c.Call.Return(copyResult, err)
	return _c
}

func (_c *MockSnippetCopier_Run_Call) RunAndReturn(run func(ctx context.Context, in snippet.CopyInput) (snippet.CopyResult, error)) *MockSnippetCopier_Run_Call {
	_c.Call.Return(run)
	return _c
}
