// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package snippet_test

import (
	"context"
	"time"

	"github.com/DannyFestor/TuiSnip/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClipboardReader creates a new instance of MockClipboardReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClipboardReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClipboardReader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockClipboardReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockClipboardReader is an autogenerated mock type for the ClipboardReader type
type MockClipboardReader struct {
	mock.Mock
}

type MockClipboardReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClipboardReader) EXPECT() *MockClipboardReader_Expecter {
	return &MockClipboardReader_Expecter{mock: &_m.Mock}
}

// ReadClipboard provides a mock function for the type MockClipboardReader
func (_mock *MockClipboardReader) ReadClipboard(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadClipboard")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClipboardReader_ReadClipboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadClipboard'
type MockClipboardReader_ReadClipboard_Call struct {
	*mock.Call
}

// ReadClipboard is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClipboardReader_Expecter) ReadClipboard(ctx any) *MockClipboardReader_ReadClipboard_Call {
	return &MockClipboardReader_ReadClipboard_Call{Call: _e.mock.On("ReadClipboard", ctx)}
}

func (_c *MockClipboardReader_ReadClipboard_Call) Run(run func(ctx context.Context)) *MockClipboardReader_ReadClipboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClipboardReader_ReadClipboard_Call) Return(s string, err error) *MockClipboardReader_ReadClipboard_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClipboardReader_ReadClipboard_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockClipboardReader_ReadClipboard_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCopier creates a new instance of MockCopier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCopier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCopier {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCopier{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCopier is an autogenerated mock type for the Copier type
type MockCopier struct {
	mock.Mock
}

type MockCopier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCopier) EXPECT() *MockCopier_Expecter {
	return &MockCopier_Expecter{mock: &_m.Mock}
}

// Copy provides a mock function for the type MockCopier
func (_mock *MockCopier) Copy(ctx context.Context, text string) (domain.CopyDelivery, error) {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 domain.CopyDelivery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.CopyDelivery, error)); ok {
		return returnFunc(ctx, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.CopyDelivery); ok {
		r0 = returnFunc(ctx, text)
	} else {
		r0 = ret.Get(0).(domain.CopyDelivery)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCopier_Copy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Copy'
type MockCopier_Copy_Call struct {
	*mock.Call
}

// Copy is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockCopier_Expecter) Copy(ctx any, text any) *MockCopier_Copy_Call {
	return &MockCopier_Copy_Call{Call: _e.mock.On("Copy", ctx, text)}
}

func (_c *MockCopier_Copy_Call) Run(run func(ctx context.Context, text string)) *MockCopier_Copy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCopier_Copy_Call) Return(copyDelivery domain.CopyDelivery, err error) *MockCopier_Copy_Call {
	_c.Call.Return(copyDelivery, err)
	return _c
}

func (_c *MockCopier_Copy_Call) RunAndReturn(run func(ctx context.Context, text string) (domain.CopyDelivery, error)) *MockCopier_Copy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleter creates a new instance of MockDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDeleter is an autogenerated mock type for the Deleter type
type MockDeleter struct {
	mock.Mock
}

type MockDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleter) EXPECT() *MockDeleter_Expecter {
	return &MockDeleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockDeleter
func (_mock *MockDeleter) Delete(ctx context.Context, id domain.SnippetID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SnippetID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.SnippetID
func (_e *MockDeleter_Expecter) Delete(ctx any, id any) *MockDeleter_Delete_Call {
	return &MockDeleter_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDeleter_Delete_Call) Run(run func(ctx context.Context, id domain.SnippetID)) *MockDeleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SnippetID
		if args[1] != nil {
			arg1 = args[1].(domain.SnippetID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeleter_Delete_Call) Return(err error) *MockDeleter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeleter_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.SnippetID) error) *MockDeleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDuplicateRepository creates a new instance of MockDuplicateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDuplicateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDuplicateRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDuplicateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDuplicateRepository is an autogenerated mock type for the DuplicateRepository type
type MockDuplicateRepository struct {
	mock.Mock
}

type MockDuplicateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDuplicateRepository) EXPECT() *MockDuplicateRepository_Expecter {
	return &MockDuplicateRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockDuplicateRepository
func (_mock *MockDuplicateRepository) Find(ctx context.Context, id domain.SnippetID) (domain.Snippet, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SnippetID) (domain.Snippet, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SnippetID) domain.Snippet); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Snippet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SnippetID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDuplicateRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockDuplicateRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.SnippetID
func (_e *MockDuplicateRepository_Expecter) Find(ctx any, id any) *MockDuplicateRepository_Find_Call {
	return &MockDuplicateRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockDuplicateRepository_Find_Call) Run(run func(ctx context.Context, id domain.SnippetID)) *MockDuplicateRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SnippetID
		if args[1] != nil {
			arg1 = args[1].(domain.SnippetID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDuplicateRepository_Find_Call) Return(snippet domain.Snippet, err error) *MockDuplicateRepository_Find_Call {
	_c.Call.Return(snippet, err)
	return _c
}

func (_c *MockDuplicateRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id domain.SnippetID) (domain.Snippet, error)) *MockDuplicateRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockDuplicateRepository
func (_mock *MockDuplicateRepository) Insert(ctx context.Context, snippet domain.Snippet) error {
	ret := _mock.Called(ctx, snippet)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Snippet) error); ok {
		r0 = returnFunc(ctx, snippet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDuplicateRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockDuplicateRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - snippet domain.Snippet
func (_e *MockDuplicateRepository_Expecter) Insert(ctx any, snippet any) *MockDuplicateRepository_Insert_Call {
	return &MockDuplicateRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, snippet)}
}

func (_c *MockDuplicateRepository_Insert_Call) Run(run func(ctx context.Context, snippet domain.Snippet)) *MockDuplicateRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Snippet
		if args[1] != nil {
			arg1 = args[1].(domain.Snippet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDuplicateRepository_Insert_Call) Return(err error) *MockDuplicateRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDuplicateRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, snippet domain.Snippet) error) *MockDuplicateRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFinder creates a new instance of MockFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFinder {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFinder is an autogenerated mock type for the Finder type
type MockFinder struct {
	mock.Mock
}

type MockFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFinder) EXPECT() *MockFinder_Expecter {
	return &MockFinder_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockFinder
func (_mock *MockFinder) Find(ctx context.Context, id domain.SnippetID) (domain.Snippet, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SnippetID) (domain.Snippet, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SnippetID) domain.Snippet); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Snippet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SnippetID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFinder_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockFinder_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.SnippetID
func (_e *MockFinder_Expecter) Find(ctx any, id any) *MockFinder_Find_Call {
	return &MockFinder_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockFinder_Find_Call) Run(run func(ctx context.Context, id domain.SnippetID)) *MockFinder_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SnippetID
		if args[1] != nil {
			arg1 = args[1].(domain.SnippetID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFinder_Find_Call) Return(snippet domain.Snippet, err error) *MockFinder_Find_Call {
	_c.Call.Return(snippet, err)
	return _c
}

func (_c *MockFinder_Find_Call) RunAndReturn(run func(ctx context.Context, id domain.SnippetID) (domain.Snippet, error)) *MockFinder_Find_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInserter creates a new instance of MockInserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInserter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockInserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockInserter is an autogenerated mock type for the Inserter type
type MockInserter struct {
	mock.Mock
}

type MockInserter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInserter) EXPECT() *MockInserter_Expecter {
	return &MockInserter_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function for the type MockInserter
func (_mock *MockInserter) Insert(ctx context.Context, snippet domain.Snippet) error {
	ret := _mock.Called(ctx, snippet)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Snippet) error); ok {
		r0 = returnFunc(ctx, snippet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInserter_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockInserter_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - snippet domain.Snippet
func (_e *MockInserter_Expecter) Insert(ctx any, snippet any) *MockInserter_Insert_Call {
	return &MockInserter_Insert_Call{Call: _e.mock.On("Insert", ctx, snippet)}
}

func (_c *MockInserter_Insert_Call) Run(run func(ctx context.Context, snippet domain.Snippet)) *MockInserter_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Snippet
		if args[1] != nil {
			arg1 = args[1].(domain.Snippet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInserter_Insert_Call) Return(err error) *MockInserter_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInserter_Insert_Call) RunAndReturn(run func(ctx context.Context, snippet domain.Snippet) error) *MockInserter_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMoveRepository creates a new instance of MockMoveRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMoveRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMoveRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockMoveRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockMoveRepository is an autogenerated mock type for the MoveRepository type
type MockMoveRepository struct {
	mock.Mock
}

type MockMoveRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMoveRepository) EXPECT() *MockMoveRepository_Expecter {
	return &MockMoveRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockMoveRepository
func (_mock *MockMoveRepository) Find(ctx context.Context, id domain.SnippetID) (domain.Snippet, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SnippetID) (domain.Snippet, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SnippetID) domain.Snippet); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Snippet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SnippetID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMoveRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockMoveRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.SnippetID
func (_e *MockMoveRepository_Expecter) Find(ctx any, id any) *MockMoveRepository_Find_Call {
	return &MockMoveRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockMoveRepository_Find_Call) Run(run func(ctx context.Context, id domain.SnippetID)) *MockMoveRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SnippetID
		if args[1] != nil {
			arg1 = args[1].(domain.SnippetID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMoveRepository_Find_Call) Return(snippet domain.Snippet, err error) *MockMoveRepository_Find_Call {
	_c.Call.Return(snippet, err)
	return _c
}

func (_c *MockMoveRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id domain.SnippetID) (domain.Snippet, error)) *MockMoveRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Move provides a mock function for the type MockMoveRepository
func (_mock *MockMoveRepository) Move(ctx context.Context, snippet domain.Snippet) error {
	ret := _mock.Called(ctx, snippet)

	if len(ret) == 0 {
		panic("no return value specified for Move")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Snippet) error); ok {
		r0 = returnFunc(ctx, snippet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMoveRepository_Move_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Move'
type MockMoveRepository_Move_Call struct {
	*mock.Call
}

// Move is a helper method to define mock.On call
//   - ctx context.Context
//   - snippet domain.Snippet
func (_e *MockMoveRepository_Expecter) Move(ctx any, snippet any) *MockMoveRepository_Move_Call {
	return &MockMoveRepository_Move_Call{Call: _e.mock.On("Move", ctx, snippet)}
}

func (_c *MockMoveRepository_Move_Call) Run(run func(ctx context.Context, snippet domain.Snippet)) *MockMoveRepository_Move_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Snippet
		if args[1] != nil {
			arg1 = args[1].(domain.Snippet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMoveRepository_Move_Call) Return(err error) *MockMoveRepository_Move_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMoveRepository_Move_Call) RunAndReturn(run func(ctx context.Context, snippet domain.Snippet) error) *MockMoveRepository_Move_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateRepository creates a new instance of MockUpdateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockUpdateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockUpdateRepository is an autogenerated mock type for the UpdateRepository type
type MockUpdateRepository struct {
	mock.Mock
}

type MockUpdateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateRepository) EXPECT() *MockUpdateRepository_Expecter {
	return &MockUpdateRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockUpdateRepository
func (_mock *MockUpdateRepository) Find(ctx context.Context, id domain.SnippetID) (domain.Snippet, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SnippetID) (domain.Snippet, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SnippetID) domain.Snippet); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Snippet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SnippetID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockUpdateRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.SnippetID
func (_e *MockUpdateRepository_Expecter) Find(ctx any, id any) *MockUpdateRepository_Find_Call {
	return &MockUpdateRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockUpdateRepository_Find_Call) Run(run func(ctx context.Context, id domain.SnippetID)) *MockUpdateRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SnippetID
		if args[1] != nil {
			arg1 = args[1].(domain.SnippetID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpdateRepository_Find_Call) Return(snippet domain.Snippet, err error) *MockUpdateRepository_Find_Call {
	_c.Call.Return(snippet, err)
	return _c
}

func (_c *MockUpdateRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id domain.SnippetID) (domain.Snippet, error)) *MockUpdateRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUpdateRepository
func (_mock *MockUpdateRepository) Update(ctx context.Context, snippet domain.Snippet, loadedUpdatedAt time.Time) error {
	ret := _mock.Called(ctx, snippet, loadedUpdatedAt)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Snippet, time.Time) error); ok {
		r0 = returnFunc(ctx, snippet, loadedUpdatedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUpdateRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUpdateRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - snippet domain.Snippet
//   - loadedUpdatedAt time.Time
func (_e *MockUpdateRepository_Expecter) Update(ctx any, snippet any, loadedUpdatedAt any) *MockUpdateRepository_Update_Call {
	return &MockUpdateRepository_Update_Call{Call: _e.mock.On("Update", ctx, snippet, loadedUpdatedAt)}
}

func (_c *MockUpdateRepository_Update_Call) Run(run func(ctx context.Context, snippet domain.Snippet, loadedUpdatedAt time.Time)) *MockUpdateRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Snippet
		if args[1] != nil {
			arg1 = args[1].(domain.Snippet)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUpdateRepository_Update_Call) Return(err error) *MockUpdateRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUpdateRepository_Update_Call) RunAndReturn(run func(ctx context.Context, snippet domain.Snippet, loadedUpdatedAt time.Time) error) *MockUpdateRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
