// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package snippet_test

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCopier creates a new instance of MockCopier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCopier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCopier {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCopier{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCopier is an autogenerated mock type for the Copier type
type MockCopier struct {
	mock.Mock
}

type MockCopier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCopier) EXPECT() *MockCopier_Expecter {
	return &MockCopier_Expecter{mock: &_m.Mock}
}

// Copy provides a mock function for the type MockCopier
func (_mock *MockCopier) Copy(ctx context.Context, text string) (domain.CopyDelivery, error) {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 domain.CopyDelivery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.CopyDelivery, error)); ok {
		return returnFunc(ctx, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.CopyDelivery); ok {
		r0 = returnFunc(ctx, text)
	} else {
		r0 = ret.Get(0).(domain.CopyDelivery)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCopier_Copy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Copy'
type MockCopier_Copy_Call struct {
	*mock.Call
}

// Copy is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockCopier_Expecter) Copy(ctx any, text any) *MockCopier_Copy_Call {
	return &MockCopier_Copy_Call{Call: _e.mock.On("Copy", ctx, text)}
}

func (_c *MockCopier_Copy_Call) Run(run func(ctx context.Context, text string)) *MockCopier_Copy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCopier_Copy_Call) Return(copyDelivery domain.CopyDelivery, err error) *MockCopier_Copy_Call {
	_c.Call.Return(copyDelivery, err)
	return _c
}

func (_c *MockCopier_Copy_Call) RunAndReturn(run func(ctx context.Context, text string) (domain.CopyDelivery, error)) *MockCopier_Copy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFinder creates a new instance of MockFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFinder {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFinder is an autogenerated mock type for the Finder type
type MockFinder struct {
	mock.Mock
}

type MockFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFinder) EXPECT() *MockFinder_Expecter {
	return &MockFinder_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockFinder
func (_mock *MockFinder) Find(ctx context.Context, id domain.SnippetID) (domain.Snippet, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Snippet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SnippetID) (domain.Snippet, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SnippetID) domain.Snippet); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Snippet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SnippetID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFinder_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockFinder_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.SnippetID
func (_e *MockFinder_Expecter) Find(ctx any, id any) *MockFinder_Find_Call {
	return &MockFinder_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockFinder_Find_Call) Run(run func(ctx context.Context, id domain.SnippetID)) *MockFinder_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SnippetID
		if args[1] != nil {
			arg1 = args[1].(domain.SnippetID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFinder_Find_Call) Return(snippet domain.Snippet, err error) *MockFinder_Find_Call {
	_c.Call.Return(snippet, err)
	return _c
}

func (_c *MockFinder_Find_Call) RunAndReturn(run func(ctx context.Context, id domain.SnippetID) (domain.Snippet, error)) *MockFinder_Find_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInserter creates a new instance of MockInserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInserter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockInserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockInserter is an autogenerated mock type for the Inserter type
type MockInserter struct {
	mock.Mock
}

type MockInserter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInserter) EXPECT() *MockInserter_Expecter {
	return &MockInserter_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function for the type MockInserter
func (_mock *MockInserter) Insert(ctx context.Context, snippet domain.Snippet) error {
	ret := _mock.Called(ctx, snippet)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Snippet) error); ok {
		r0 = returnFunc(ctx, snippet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInserter_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockInserter_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - snippet domain.Snippet
func (_e *MockInserter_Expecter) Insert(ctx any, snippet any) *MockInserter_Insert_Call {
	return &MockInserter_Insert_Call{Call: _e.mock.On("Insert", ctx, snippet)}
}

func (_c *MockInserter_Insert_Call) Run(run func(ctx context.Context, snippet domain.Snippet)) *MockInserter_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Snippet
		if args[1] != nil {
			arg1 = args[1].(domain.Snippet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInserter_Insert_Call) Return(err error) *MockInserter_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInserter_Insert_Call) RunAndReturn(run func(ctx context.Context, snippet domain.Snippet) error) *MockInserter_Insert_Call {
	_c.Call.Return(run)
	return _c
}
