// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tag_test

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeleter creates a new instance of MockDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDeleter is an autogenerated mock type for the Deleter type
type MockDeleter struct {
	mock.Mock
}

type MockDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleter) EXPECT() *MockDeleter_Expecter {
	return &MockDeleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockDeleter
func (_mock *MockDeleter) Delete(ctx context.Context, id domain.TagID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TagID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.TagID
func (_e *MockDeleter_Expecter) Delete(ctx any, id any) *MockDeleter_Delete_Call {
	return &MockDeleter_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDeleter_Delete_Call) Run(run func(ctx context.Context, id domain.TagID)) *MockDeleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TagID
		if args[1] != nil {
			arg1 = args[1].(domain.TagID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeleter_Delete_Call) Return(err error) *MockDeleter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeleter_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.TagID) error) *MockDeleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInserter creates a new instance of MockInserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInserter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockInserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockInserter is an autogenerated mock type for the Inserter type
type MockInserter struct {
	mock.Mock
}

type MockInserter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInserter) EXPECT() *MockInserter_Expecter {
	return &MockInserter_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function for the type MockInserter
func (_mock *MockInserter) Insert(ctx context.Context, tag domain.Tag) error {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Tag) error); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInserter_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockInserter_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - tag domain.Tag
func (_e *MockInserter_Expecter) Insert(ctx any, tag any) *MockInserter_Insert_Call {
	return &MockInserter_Insert_Call{Call: _e.mock.On("Insert", ctx, tag)}
}

func (_c *MockInserter_Insert_Call) Run(run func(ctx context.Context, tag domain.Tag)) *MockInserter_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Tag
		if args[1] != nil {
			arg1 = args[1].(domain.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInserter_Insert_Call) Return(err error) *MockInserter_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInserter_Insert_Call) RunAndReturn(run func(ctx context.Context, tag domain.Tag) error) *MockInserter_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPreviewDeleteRepository creates a new instance of MockPreviewDeleteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPreviewDeleteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPreviewDeleteRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPreviewDeleteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPreviewDeleteRepository is an autogenerated mock type for the PreviewDeleteRepository type
type MockPreviewDeleteRepository struct {
	mock.Mock
}

type MockPreviewDeleteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPreviewDeleteRepository) EXPECT() *MockPreviewDeleteRepository_Expecter {
	return &MockPreviewDeleteRepository_Expecter{mock: &_m.Mock}
}

// CountSnippets provides a mock function for the type MockPreviewDeleteRepository
func (_mock *MockPreviewDeleteRepository) CountSnippets(ctx context.Context, id domain.TagID) (int, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountSnippets")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TagID) (int, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TagID) int); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.TagID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPreviewDeleteRepository_CountSnippets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSnippets'
type MockPreviewDeleteRepository_CountSnippets_Call struct {
	*mock.Call
}

// CountSnippets is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.TagID
func (_e *MockPreviewDeleteRepository_Expecter) CountSnippets(ctx any, id any) *MockPreviewDeleteRepository_CountSnippets_Call {
	return &MockPreviewDeleteRepository_CountSnippets_Call{Call: _e.mock.On("CountSnippets", ctx, id)}
}

func (_c *MockPreviewDeleteRepository_CountSnippets_Call) Run(run func(ctx context.Context, id domain.TagID)) *MockPreviewDeleteRepository_CountSnippets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TagID
		if args[1] != nil {
			arg1 = args[1].(domain.TagID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPreviewDeleteRepository_CountSnippets_Call) Return(n int, err error) *MockPreviewDeleteRepository_CountSnippets_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPreviewDeleteRepository_CountSnippets_Call) RunAndReturn(run func(ctx context.Context, id domain.TagID) (int, error)) *MockPreviewDeleteRepository_CountSnippets_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockPreviewDeleteRepository
func (_mock *MockPreviewDeleteRepository) Find(ctx context.Context, id domain.TagID) (domain.Tag, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TagID) (domain.Tag, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TagID) domain.Tag); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Tag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.TagID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPreviewDeleteRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockPreviewDeleteRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.TagID
func (_e *MockPreviewDeleteRepository_Expecter) Find(ctx any, id any) *MockPreviewDeleteRepository_Find_Call {
	return &MockPreviewDeleteRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockPreviewDeleteRepository_Find_Call) Run(run func(ctx context.Context, id domain.TagID)) *MockPreviewDeleteRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TagID
		if args[1] != nil {
			arg1 = args[1].(domain.TagID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPreviewDeleteRepository_Find_Call) Return(tag domain.Tag, err error) *MockPreviewDeleteRepository_Find_Call {
	_c.Call.Return(tag, err)
	return _c
}

func (_c *MockPreviewDeleteRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id domain.TagID) (domain.Tag, error)) *MockPreviewDeleteRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRenameRepository creates a new instance of MockRenameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRenameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRenameRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRenameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRenameRepository is an autogenerated mock type for the RenameRepository type
type MockRenameRepository struct {
	mock.Mock
}

type MockRenameRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRenameRepository) EXPECT() *MockRenameRepository_Expecter {
	return &MockRenameRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockRenameRepository
func (_mock *MockRenameRepository) Find(ctx context.Context, id domain.TagID) (domain.Tag, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TagID) (domain.Tag, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TagID) domain.Tag); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Tag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.TagID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRenameRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockRenameRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.TagID
func (_e *MockRenameRepository_Expecter) Find(ctx any, id any) *MockRenameRepository_Find_Call {
	return &MockRenameRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockRenameRepository_Find_Call) Run(run func(ctx context.Context, id domain.TagID)) *MockRenameRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TagID
		if args[1] != nil {
			arg1 = args[1].(domain.TagID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRenameRepository_Find_Call) Return(tag domain.Tag, err error) *MockRenameRepository_Find_Call {
	_c.Call.Return(tag, err)
	return _c
}

func (_c *MockRenameRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id domain.TagID) (domain.Tag, error)) *MockRenameRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockRenameRepository
func (_mock *MockRenameRepository) Rename(ctx context.Context, tag domain.Tag) (domain.Tag, error) {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 domain.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Tag) (domain.Tag, error)); ok {
		return returnFunc(ctx, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Tag) domain.Tag); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		r0 = ret.Get(0).(domain.Tag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Tag) error); ok {
		r1 = returnFunc(ctx, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRenameRepository_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockRenameRepository_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - ctx context.Context
//   - tag domain.Tag
func (_e *MockRenameRepository_Expecter) Rename(ctx any, tag any) *MockRenameRepository_Rename_Call {
	return &MockRenameRepository_Rename_Call{Call: _e.mock.On("Rename", ctx, tag)}
}

func (_c *MockRenameRepository_Rename_Call) Run(run func(ctx context.Context, tag domain.Tag)) *MockRenameRepository_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Tag
		if args[1] != nil {
			arg1 = args[1].(domain.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRenameRepository_Rename_Call) Return(tag1 domain.Tag, err error) *MockRenameRepository_Rename_Call {
	_c.Call.Return(tag1, err)
	return _c
}

func (_c *MockRenameRepository_Rename_Call) RunAndReturn(run func(ctx context.Context, tag domain.Tag) (domain.Tag, error)) *MockRenameRepository_Rename_Call {
	_c.Call.Return(run)
	return _c
}
