package binding

//nolint:dupl // a table of Binding names that dupl matches against the label table in row.go; no logic repeats.
const (
	Quit         = "quit"
	Help         = "help"
	Search       = "search"
	Zoom         = "zoom"
	NewSnippet   = "new_snippet"
	Capture      = "capture"
	FocusNext    = "focus_next"
	FocusPrev    = "focus_prev"
	FocusRight   = "focus_right"
	FocusLeft    = "focus_left"
	FocusFolders = "focus_folders"
	FocusTags    = "focus_tags"
	FocusList    = "focus_list"
	FocusSnippet = "focus_snippet"
	Open         = "open"
	Back         = "back"
	Down         = "down"
	Up           = "up"
	Top          = "top"
	Bottom       = "bottom"
	PageDown     = "page_down"
	PageUp       = "page_up"
	NewFolder    = "new_folder"
	NewTag       = "new_tag"
	Rename       = "rename"
	Move         = "move"
	Delete       = "delete"
	Collapse     = "collapse"
	Language     = "language"
	Copy         = "copy"
	Edit         = "edit"
	Duplicate    = "duplicate"
	CycleSort    = "cycle_sort"
	Wrap         = "wrap"
	OpenInEditor = "open_in_editor"
	Save         = "save"
	Cancel       = "cancel"
	NextField    = "next_field"
	PrevField    = "prev_field"
	OpenField    = "open_field"
	PickLanguage = "pick_language"
	EditTags     = "edit_tags"
	Leave        = "leave"
	Indent       = "indent"
	Dedent       = "dedent"
	Accept       = "accept"
	Yes          = "yes"
	No           = "no"

	ShowAllLanguages = "show_all_languages"
)
