package binding

const (
	Quit         = "quit"
	Help         = "help"
	Search       = "search"
	Zoom         = "zoom"
	NewSnippet   = "new_snippet"
	Capture      = "capture"
	FocusNext    = "focus_next"
	FocusPrev    = "focus_prev"
	FocusRight   = "focus_right"
	FocusLeft    = "focus_left"
	FocusFolders = "focus_folders"
	FocusTags    = "focus_tags"
	FocusList    = "focus_list"
	FocusSnippet = "focus_snippet"
	Open         = "open"
	Back         = "back"
	Down         = "down"
	Up           = "up"
	Top          = "top"
	Bottom       = "bottom"
	PageDown     = "page_down"
	PageUp       = "page_up"
	NewFolder    = "new_folder"
	Rename       = "rename"
	Delete       = "delete"
	Collapse     = "collapse"
	Copy         = "copy"
	CycleSort    = "cycle_sort"
	OpenInEditor = "open_in_editor"
	Save         = "save"
	Cancel       = "cancel"
	NextField    = "next_field"
	PrevField    = "prev_field"
	OpenField    = "open_field"
	Leave        = "leave"
	Accept       = "accept"
	Yes          = "yes"
	No           = "no"
)
