// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package sqlcgen

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/adapters/sqlite/sqltype"
)

const getFolder = `-- name: GetFolder :one
SELECT id, parent_id, name, default_language, created_at, updated_at
FROM folders
WHERE id = ?
`

func (q *Queries) GetFolder(ctx context.Context, id sqltype.ID) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.DefaultLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFolder = `-- name: InsertFolder :exec
INSERT INTO folders (id, parent_id, name, default_language, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertFolderParams struct {
	ID              sqltype.ID
	ParentID        *sqltype.ID
	Name            string
	DefaultLanguage string
	CreatedAt       sqltype.Timestamp
	UpdatedAt       sqltype.Timestamp
}

func (q *Queries) InsertFolder(ctx context.Context, arg InsertFolderParams) error {
	_, err := q.db.ExecContext(ctx, insertFolder,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.DefaultLanguage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listFolders = `-- name: ListFolders :many
SELECT id, parent_id, name, default_language, created_at, updated_at
FROM folders
`

func (q *Queries) ListFolders(ctx context.Context) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.DefaultLanguage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFolder = `-- name: UpdateFolder :execrows
UPDATE folders
SET name = ?, default_language = ?, updated_at = ?
WHERE id = ?
`

type UpdateFolderParams struct {
	Name            string
	DefaultLanguage string
	UpdatedAt       sqltype.Timestamp
	ID              sqltype.ID
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFolder,
		arg.Name,
		arg.DefaultLanguage,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
