// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fragments.sql

package sqlcgen

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/adapters/sqlite/sqltype"
)

const insertFragment = `-- name: InsertFragment :exec
INSERT INTO fragments (id, snippet_id, position, language, content, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertFragmentParams struct {
	ID        sqltype.ID
	SnippetID sqltype.ID
	Position  int64
	Language  string
	Content   string
	CreatedAt sqltype.Timestamp
	UpdatedAt sqltype.Timestamp
}

func (q *Queries) InsertFragment(ctx context.Context, arg InsertFragmentParams) error {
	_, err := q.db.ExecContext(ctx, insertFragment,
		arg.ID,
		arg.SnippetID,
		arg.Position,
		arg.Language,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listFragments = `-- name: ListFragments :many
SELECT id, snippet_id, position, language, content, created_at, updated_at
FROM fragments
ORDER BY snippet_id, position
`

func (q *Queries) ListFragments(ctx context.Context) ([]Fragment, error) {
	rows, err := q.db.QueryContext(ctx, listFragments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fragment{}
	for rows.Next() {
		var i Fragment
		if err := rows.Scan(
			&i.ID,
			&i.SnippetID,
			&i.Position,
			&i.Language,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFragmentsBySnippet = `-- name: ListFragmentsBySnippet :many
SELECT id, snippet_id, position, language, content, created_at, updated_at
FROM fragments
WHERE snippet_id = ?
ORDER BY position
`

func (q *Queries) ListFragmentsBySnippet(ctx context.Context, snippetID sqltype.ID) ([]Fragment, error) {
	rows, err := q.db.QueryContext(ctx, listFragmentsBySnippet, snippetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fragment{}
	for rows.Next() {
		var i Fragment
		if err := rows.Scan(
			&i.ID,
			&i.SnippetID,
			&i.Position,
			&i.Language,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFragmentsInFolder = `-- name: ListFragmentsInFolder :many
SELECT fragments.id, fragments.snippet_id, fragments.position, fragments.language, fragments.content,
       fragments.created_at, fragments.updated_at
FROM fragments
JOIN snippets ON snippets.id = fragments.snippet_id
WHERE snippets.folder_id IS ?1
ORDER BY fragments.snippet_id, fragments.position
`

func (q *Queries) ListFragmentsInFolder(ctx context.Context, folderID *sqltype.ID) ([]Fragment, error) {
	rows, err := q.db.QueryContext(ctx, listFragmentsInFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fragment{}
	for rows.Next() {
		var i Fragment
		if err := rows.Scan(
			&i.ID,
			&i.SnippetID,
			&i.Position,
			&i.Language,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFragmentsWithTag = `-- name: ListFragmentsWithTag :many
SELECT fragments.id, fragments.snippet_id, fragments.position, fragments.language, fragments.content,
       fragments.created_at, fragments.updated_at
FROM fragments
JOIN snippet_tag ON snippet_tag.snippet_id = fragments.snippet_id
WHERE snippet_tag.tag_id = ?1
ORDER BY fragments.snippet_id, fragments.position
`

func (q *Queries) ListFragmentsWithTag(ctx context.Context, tagID sqltype.ID) ([]Fragment, error) {
	rows, err := q.db.QueryContext(ctx, listFragmentsWithTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fragment{}
	for rows.Next() {
		var i Fragment
		if err := rows.Scan(
			&i.ID,
			&i.SnippetID,
			&i.Position,
			&i.Language,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
