// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/DannyFestor/TuiSnip/internal/adapters/sqlite/sqltype"
)

type Folder struct {
	ID              sqltype.ID
	ParentID        *sqltype.ID
	Name            string
	DefaultLanguage string
	CreatedAt       sqltype.Timestamp
	UpdatedAt       sqltype.Timestamp
}

type Fragment struct {
	ID        sqltype.ID
	SnippetID sqltype.ID
	Position  int64
	Language  string
	Content   string
	CreatedAt sqltype.Timestamp
	UpdatedAt sqltype.Timestamp
}

type Snippet struct {
	ID          sqltype.ID
	FolderID    *sqltype.ID
	Title       string
	Description string
	CreatedAt   sqltype.Timestamp
	UpdatedAt   sqltype.Timestamp
}

type SnippetTag struct {
	SnippetID sqltype.ID
	TagID     sqltype.ID
}

type Tag struct {
	ID        sqltype.ID
	Name      string
	NameKey   string
	CreatedAt sqltype.Timestamp
	UpdatedAt sqltype.Timestamp
}
