// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snippet_tag.sql

package sqlcgen

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/adapters/sqlite/sqltype"
)

const countSnippetsByTag = `-- name: CountSnippetsByTag :many
SELECT tag_id, COUNT(*) AS snippet_count
FROM snippet_tag
GROUP BY tag_id
`

type CountSnippetsByTagRow struct {
	TagID        sqltype.ID
	SnippetCount int64
}

func (q *Queries) CountSnippetsByTag(ctx context.Context) ([]CountSnippetsByTagRow, error) {
	rows, err := q.db.QueryContext(ctx, countSnippetsByTag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSnippetsByTagRow{}
	for rows.Next() {
		var i CountSnippetsByTagRow
		if err := rows.Scan(&i.TagID, &i.SnippetCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSnippetTag = `-- name: InsertSnippetTag :exec
INSERT INTO snippet_tag (snippet_id, tag_id)
VALUES (?, ?)
`

type InsertSnippetTagParams struct {
	SnippetID sqltype.ID
	TagID     sqltype.ID
}

func (q *Queries) InsertSnippetTag(ctx context.Context, arg InsertSnippetTagParams) error {
	_, err := q.db.ExecContext(ctx, insertSnippetTag, arg.SnippetID, arg.TagID)
	return err
}
