// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snippets.sql

package sqlcgen

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/adapters/sqlite/sqltype"
)

const countSnippetsByFolder = `-- name: CountSnippetsByFolder :many
SELECT folder_id, COUNT(*) AS snippet_count
FROM snippets
GROUP BY folder_id
`

type CountSnippetsByFolderRow struct {
	FolderID     *sqltype.ID
	SnippetCount int64
}

func (q *Queries) CountSnippetsByFolder(ctx context.Context) ([]CountSnippetsByFolderRow, error) {
	rows, err := q.db.QueryContext(ctx, countSnippetsByFolder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSnippetsByFolderRow{}
	for rows.Next() {
		var i CountSnippetsByFolderRow
		if err := rows.Scan(&i.FolderID, &i.SnippetCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnippet = `-- name: GetSnippet :one
SELECT id, folder_id, title, description, created_at, updated_at
FROM snippets
WHERE id = ?
`

func (q *Queries) GetSnippet(ctx context.Context, id sqltype.ID) (Snippet, error) {
	row := q.db.QueryRowContext(ctx, getSnippet, id)
	var i Snippet
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSnippet = `-- name: InsertSnippet :exec
INSERT INTO snippets (id, folder_id, title, description, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSnippetParams struct {
	ID          sqltype.ID
	FolderID    *sqltype.ID
	Title       string
	Description string
	CreatedAt   sqltype.Timestamp
	UpdatedAt   sqltype.Timestamp
}

func (q *Queries) InsertSnippet(ctx context.Context, arg InsertSnippetParams) error {
	_, err := q.db.ExecContext(ctx, insertSnippet,
		arg.ID,
		arg.FolderID,
		arg.Title,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listSnippets = `-- name: ListSnippets :many
SELECT id, folder_id, title, description, created_at, updated_at
FROM snippets
`

func (q *Queries) ListSnippets(ctx context.Context) ([]Snippet, error) {
	rows, err := q.db.QueryContext(ctx, listSnippets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snippet{}
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnippetsInFolderByCreated = `-- name: ListSnippetsInFolderByCreated :many
SELECT id, folder_id, title, description, created_at, updated_at
FROM snippets
WHERE folder_id IS ?1
ORDER BY created_at DESC, title COLLATE NOCASE, id
`

func (q *Queries) ListSnippetsInFolderByCreated(ctx context.Context, folderID *sqltype.ID) ([]Snippet, error) {
	rows, err := q.db.QueryContext(ctx, listSnippetsInFolderByCreated, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snippet{}
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnippetsInFolderByTitle = `-- name: ListSnippetsInFolderByTitle :many
SELECT id, folder_id, title, description, created_at, updated_at
FROM snippets
WHERE folder_id IS ?1
ORDER BY title COLLATE NOCASE, id
`

func (q *Queries) ListSnippetsInFolderByTitle(ctx context.Context, folderID *sqltype.ID) ([]Snippet, error) {
	rows, err := q.db.QueryContext(ctx, listSnippetsInFolderByTitle, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snippet{}
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnippetsInFolderByUpdated = `-- name: ListSnippetsInFolderByUpdated :many
SELECT id, folder_id, title, description, created_at, updated_at
FROM snippets
WHERE folder_id IS ?1
ORDER BY updated_at DESC, title COLLATE NOCASE, id
`

func (q *Queries) ListSnippetsInFolderByUpdated(ctx context.Context, folderID *sqltype.ID) ([]Snippet, error) {
	rows, err := q.db.QueryContext(ctx, listSnippetsInFolderByUpdated, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snippet{}
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnippetsWithTagByCreated = `-- name: ListSnippetsWithTagByCreated :many
SELECT snippets.id, snippets.folder_id, snippets.title, snippets.description, snippets.created_at, snippets.updated_at
FROM snippets
JOIN snippet_tag ON snippet_tag.snippet_id = snippets.id
WHERE snippet_tag.tag_id = ?1
ORDER BY snippets.created_at DESC, snippets.title COLLATE NOCASE, snippets.id
`

func (q *Queries) ListSnippetsWithTagByCreated(ctx context.Context, tagID sqltype.ID) ([]Snippet, error) {
	rows, err := q.db.QueryContext(ctx, listSnippetsWithTagByCreated, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snippet{}
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnippetsWithTagByTitle = `-- name: ListSnippetsWithTagByTitle :many
SELECT snippets.id, snippets.folder_id, snippets.title, snippets.description, snippets.created_at, snippets.updated_at
FROM snippets
JOIN snippet_tag ON snippet_tag.snippet_id = snippets.id
WHERE snippet_tag.tag_id = ?1
ORDER BY snippets.title COLLATE NOCASE, snippets.id
`

func (q *Queries) ListSnippetsWithTagByTitle(ctx context.Context, tagID sqltype.ID) ([]Snippet, error) {
	rows, err := q.db.QueryContext(ctx, listSnippetsWithTagByTitle, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snippet{}
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnippetsWithTagByUpdated = `-- name: ListSnippetsWithTagByUpdated :many
SELECT snippets.id, snippets.folder_id, snippets.title, snippets.description, snippets.created_at, snippets.updated_at
FROM snippets
JOIN snippet_tag ON snippet_tag.snippet_id = snippets.id
WHERE snippet_tag.tag_id = ?1
ORDER BY snippets.updated_at DESC, snippets.title COLLATE NOCASE, snippets.id
`

func (q *Queries) ListSnippetsWithTagByUpdated(ctx context.Context, tagID sqltype.ID) ([]Snippet, error) {
	rows, err := q.db.QueryContext(ctx, listSnippetsWithTagByUpdated, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snippet{}
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
