// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snippets.sql

package sqlcgen

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/adapters/sqlite/sqltype"
)

const countSnippetsByFolder = `-- name: CountSnippetsByFolder :many
SELECT folder_id, COUNT(*) AS snippet_count
FROM snippets
GROUP BY folder_id
`

type CountSnippetsByFolderRow struct {
	FolderID     *sqltype.ID
	SnippetCount int64
}

func (q *Queries) CountSnippetsByFolder(ctx context.Context) ([]CountSnippetsByFolderRow, error) {
	rows, err := q.db.QueryContext(ctx, countSnippetsByFolder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSnippetsByFolderRow{}
	for rows.Next() {
		var i CountSnippetsByFolderRow
		if err := rows.Scan(&i.FolderID, &i.SnippetCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnippet = `-- name: GetSnippet :one
SELECT id, folder_id, title, description, created_at, updated_at
FROM snippets
WHERE id = ?
`

func (q *Queries) GetSnippet(ctx context.Context, id sqltype.ID) (Snippet, error) {
	row := q.db.QueryRowContext(ctx, getSnippet, id)
	var i Snippet
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSnippet = `-- name: InsertSnippet :exec
INSERT INTO snippets (id, folder_id, title, description, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSnippetParams struct {
	ID          sqltype.ID
	FolderID    *sqltype.ID
	Title       string
	Description string
	CreatedAt   sqltype.Timestamp
	UpdatedAt   sqltype.Timestamp
}

func (q *Queries) InsertSnippet(ctx context.Context, arg InsertSnippetParams) error {
	_, err := q.db.ExecContext(ctx, insertSnippet,
		arg.ID,
		arg.FolderID,
		arg.Title,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listSnippets = `-- name: ListSnippets :many
SELECT id, folder_id, title, description, created_at, updated_at
FROM snippets
`

func (q *Queries) ListSnippets(ctx context.Context) ([]Snippet, error) {
	rows, err := q.db.QueryContext(ctx, listSnippets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snippet{}
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnippetsInFolder = `-- name: ListSnippetsInFolder :many
SELECT id, folder_id, title, description, created_at, updated_at
FROM snippets
WHERE folder_id IS ?1
ORDER BY title COLLATE NOCASE, id
`

func (q *Queries) ListSnippetsInFolder(ctx context.Context, folderID *sqltype.ID) ([]Snippet, error) {
	rows, err := q.db.QueryContext(ctx, listSnippetsInFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snippet{}
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
