// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snippet_tag.sql

package sqlcgen

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/adapters/sqlite/sqltype"
)

const countSnippetsByTag = `-- name: CountSnippetsByTag :many
SELECT tag_id, COUNT(*) AS snippet_count
FROM snippet_tag
GROUP BY tag_id
`

type CountSnippetsByTagRow struct {
	TagID        sqltype.ID
	SnippetCount int64
}

func (q *Queries) CountSnippetsByTag(ctx context.Context) ([]CountSnippetsByTagRow, error) {
	rows, err := q.db.QueryContext(ctx, countSnippetsByTag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSnippetsByTagRow{}
	for rows.Next() {
		var i CountSnippetsByTagRow
		if err := rows.Scan(&i.TagID, &i.SnippetCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSnippetsWithTag = `-- name: CountSnippetsWithTag :one
SELECT COUNT(*)
FROM snippet_tag
WHERE tag_id = ?
`

func (q *Queries) CountSnippetsWithTag(ctx context.Context, tagID sqltype.ID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSnippetsWithTag, tagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSnippetTags = `-- name: DeleteSnippetTags :exec
DELETE FROM snippet_tag
WHERE snippet_id = ?
`

func (q *Queries) DeleteSnippetTags(ctx context.Context, snippetID sqltype.ID) error {
	_, err := q.db.ExecContext(ctx, deleteSnippetTags, snippetID)
	return err
}

const insertSnippetTag = `-- name: InsertSnippetTag :exec
INSERT INTO snippet_tag (snippet_id, tag_id)
VALUES (?, ?)
`

type InsertSnippetTagParams struct {
	SnippetID sqltype.ID
	TagID     sqltype.ID
}

func (q *Queries) InsertSnippetTag(ctx context.Context, arg InsertSnippetTagParams) error {
	_, err := q.db.ExecContext(ctx, insertSnippetTag, arg.SnippetID, arg.TagID)
	return err
}

const moveSnippetTags = `-- name: MoveSnippetTags :exec
INSERT OR IGNORE INTO snippet_tag (snippet_id, tag_id)
SELECT moved.snippet_id, ?1
FROM snippet_tag AS moved
WHERE moved.tag_id = ?2
`

type MoveSnippetTagsParams struct {
	ToTagID   sqltype.ID
	FromTagID sqltype.ID
}

func (q *Queries) MoveSnippetTags(ctx context.Context, arg MoveSnippetTagsParams) error {
	_, err := q.db.ExecContext(ctx, moveSnippetTags, arg.ToTagID, arg.FromTagID)
	return err
}
