// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlcgen

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/adapters/sqlite/sqltype"
)

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags
WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id sqltype.ID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTag, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTag = `-- name: GetTag :one
SELECT id, name, name_key, created_at, updated_at
FROM tags
WHERE id = ?
`

func (q *Queries) GetTag(ctx context.Context, id sqltype.ID) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :exec
INSERT INTO tags (id, name, name_key, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertTagParams struct {
	ID        sqltype.ID
	Name      string
	NameKey   string
	CreatedAt sqltype.Timestamp
	UpdatedAt sqltype.Timestamp
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) error {
	_, err := q.db.ExecContext(ctx, insertTag,
		arg.ID,
		arg.Name,
		arg.NameKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listOtherTagsWithNameKey = `-- name: ListOtherTagsWithNameKey :many
SELECT id, name, name_key, created_at, updated_at
FROM tags
WHERE name_key = ?1 AND id <> ?2
`

type ListOtherTagsWithNameKeyParams struct {
	NameKey string
	ID      sqltype.ID
}

func (q *Queries) ListOtherTagsWithNameKey(ctx context.Context, arg ListOtherTagsWithNameKeyParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listOtherTagsWithNameKey, arg.NameKey, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnippetTags = `-- name: ListSnippetTags :many
SELECT snippet_tag.snippet_id, tags.id, tags.name, tags.name_key, tags.created_at, tags.updated_at
FROM snippet_tag
JOIN tags ON tags.id = snippet_tag.tag_id
`

type ListSnippetTagsRow struct {
	SnippetID sqltype.ID
	Tag       Tag
}

func (q *Queries) ListSnippetTags(ctx context.Context) ([]ListSnippetTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSnippetTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnippetTagsRow{}
	for rows.Next() {
		var i ListSnippetTagsRow
		if err := rows.Scan(
			&i.SnippetID,
			&i.Tag.ID,
			&i.Tag.Name,
			&i.Tag.NameKey,
			&i.Tag.CreatedAt,
			&i.Tag.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnippetTagsBySnippet = `-- name: ListSnippetTagsBySnippet :many
SELECT snippet_tag.snippet_id, tags.id, tags.name, tags.name_key, tags.created_at, tags.updated_at
FROM snippet_tag
JOIN tags ON tags.id = snippet_tag.tag_id
WHERE snippet_tag.snippet_id = ?
`

type ListSnippetTagsBySnippetRow struct {
	SnippetID sqltype.ID
	Tag       Tag
}

func (q *Queries) ListSnippetTagsBySnippet(ctx context.Context, snippetID sqltype.ID) ([]ListSnippetTagsBySnippetRow, error) {
	rows, err := q.db.QueryContext(ctx, listSnippetTagsBySnippet, snippetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnippetTagsBySnippetRow{}
	for rows.Next() {
		var i ListSnippetTagsBySnippetRow
		if err := rows.Scan(
			&i.SnippetID,
			&i.Tag.ID,
			&i.Tag.Name,
			&i.Tag.NameKey,
			&i.Tag.CreatedAt,
			&i.Tag.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnippetTagsInFolder = `-- name: ListSnippetTagsInFolder :many
SELECT snippet_tag.snippet_id, tags.id, tags.name, tags.name_key, tags.created_at, tags.updated_at
FROM snippet_tag
JOIN tags ON tags.id = snippet_tag.tag_id
JOIN snippets ON snippets.id = snippet_tag.snippet_id
WHERE snippets.folder_id IS ?1
`

type ListSnippetTagsInFolderRow struct {
	SnippetID sqltype.ID
	Tag       Tag
}

func (q *Queries) ListSnippetTagsInFolder(ctx context.Context, folderID *sqltype.ID) ([]ListSnippetTagsInFolderRow, error) {
	rows, err := q.db.QueryContext(ctx, listSnippetTagsInFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnippetTagsInFolderRow{}
	for rows.Next() {
		var i ListSnippetTagsInFolderRow
		if err := rows.Scan(
			&i.SnippetID,
			&i.Tag.ID,
			&i.Tag.Name,
			&i.Tag.NameKey,
			&i.Tag.CreatedAt,
			&i.Tag.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnippetTagsWithTag = `-- name: ListSnippetTagsWithTag :many
SELECT snippet_tag.snippet_id, tags.id, tags.name, tags.name_key, tags.created_at, tags.updated_at
FROM snippet_tag
JOIN tags ON tags.id = snippet_tag.tag_id
WHERE snippet_tag.snippet_id IN (SELECT carrying.snippet_id FROM snippet_tag AS carrying WHERE carrying.tag_id = ?1)
`

type ListSnippetTagsWithTagRow struct {
	SnippetID sqltype.ID
	Tag       Tag
}

func (q *Queries) ListSnippetTagsWithTag(ctx context.Context, tagID sqltype.ID) ([]ListSnippetTagsWithTagRow, error) {
	rows, err := q.db.QueryContext(ctx, listSnippetTagsWithTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnippetTagsWithTagRow{}
	for rows.Next() {
		var i ListSnippetTagsWithTagRow
		if err := rows.Scan(
			&i.SnippetID,
			&i.Tag.ID,
			&i.Tag.Name,
			&i.Tag.NameKey,
			&i.Tag.CreatedAt,
			&i.Tag.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, name_key, created_at, updated_at
FROM tags
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :execrows
UPDATE tags
SET name = ?, name_key = ?, updated_at = ?
WHERE id = ?
`

type UpdateTagParams struct {
	Name      string
	NameKey   string
	UpdatedAt sqltype.Timestamp
	ID        sqltype.ID
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTag,
		arg.Name,
		arg.NameKey,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
