package main

import (
	"bytes"
	"fmt"
	"go/format"
	"slices"
	"text/template"

	"github.com/alecthomas/chroma/v2/lexers"
)

const sourceTemplate = `// Code generated by languagegen from chroma's lexer registry. DO NOT EDIT.

package value

func chromaLanguageNames() []string {
	return []string{
{{- range .}}
		{{printf "%q" .}},
{{- end}}
	}
}
`

func languageNames() []string {
	names := lexers.Names(false)
	slices.Sort(names)

	return slices.Compact(names)
}

func renderSource(names []string) ([]byte, error) {
	parsed, err := template.New("languages").Parse(sourceTemplate)
	if err != nil {
		return nil, fmt.Errorf("languagegen: %w", err)
	}

	var rendered bytes.Buffer

	err = parsed.Execute(&rendered, names)
	if err != nil {
		return nil, fmt.Errorf("languagegen: %w", err)
	}

	formatted, err := format.Source(rendered.Bytes())
	if err != nil {
		return nil, fmt.Errorf("languagegen: %w", err)
	}

	return formatted, nil
}
