// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package folder_test

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateRepository creates a new instance of MockCreateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCreateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCreateRepository is an autogenerated mock type for the CreateRepository type
type MockCreateRepository struct {
	mock.Mock
}

type MockCreateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateRepository) EXPECT() *MockCreateRepository_Expecter {
	return &MockCreateRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockCreateRepository
func (_mock *MockCreateRepository) Find(ctx context.Context, id domain.FolderID) (domain.Folder, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Folder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) (domain.Folder, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) domain.Folder); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Folder)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FolderID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCreateRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.FolderID
func (_e *MockCreateRepository_Expecter) Find(ctx any, id any) *MockCreateRepository_Find_Call {
	return &MockCreateRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockCreateRepository_Find_Call) Run(run func(ctx context.Context, id domain.FolderID)) *MockCreateRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FolderID
		if args[1] != nil {
			arg1 = args[1].(domain.FolderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateRepository_Find_Call) Return(folder domain.Folder, err error) *MockCreateRepository_Find_Call {
	_c.Call.Return(folder, err)
	return _c
}

func (_c *MockCreateRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id domain.FolderID) (domain.Folder, error)) *MockCreateRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockCreateRepository
func (_mock *MockCreateRepository) Insert(ctx context.Context, folder domain.Folder) error {
	ret := _mock.Called(ctx, folder)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Folder) error); ok {
		r0 = returnFunc(ctx, folder)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreateRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCreateRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - folder domain.Folder
func (_e *MockCreateRepository_Expecter) Insert(ctx any, folder any) *MockCreateRepository_Insert_Call {
	return &MockCreateRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, folder)}
}

func (_c *MockCreateRepository_Insert_Call) Run(run func(ctx context.Context, folder domain.Folder)) *MockCreateRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Folder
		if args[1] != nil {
			arg1 = args[1].(domain.Folder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateRepository_Insert_Call) Return(err error) *MockCreateRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreateRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, folder domain.Folder) error) *MockCreateRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleter creates a new instance of MockDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDeleter is an autogenerated mock type for the Deleter type
type MockDeleter struct {
	mock.Mock
}

type MockDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleter) EXPECT() *MockDeleter_Expecter {
	return &MockDeleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockDeleter
func (_mock *MockDeleter) Delete(ctx context.Context, id domain.FolderID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.FolderID
func (_e *MockDeleter_Expecter) Delete(ctx any, id any) *MockDeleter_Delete_Call {
	return &MockDeleter_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDeleter_Delete_Call) Run(run func(ctx context.Context, id domain.FolderID)) *MockDeleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FolderID
		if args[1] != nil {
			arg1 = args[1].(domain.FolderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeleter_Delete_Call) Return(err error) *MockDeleter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeleter_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.FolderID) error) *MockDeleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEditRepository creates a new instance of MockEditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEditRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockEditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockEditRepository is an autogenerated mock type for the EditRepository type
type MockEditRepository struct {
	mock.Mock
}

type MockEditRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEditRepository) EXPECT() *MockEditRepository_Expecter {
	return &MockEditRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockEditRepository
func (_mock *MockEditRepository) Find(ctx context.Context, id domain.FolderID) (domain.Folder, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Folder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) (domain.Folder, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) domain.Folder); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Folder)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FolderID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEditRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockEditRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.FolderID
func (_e *MockEditRepository_Expecter) Find(ctx any, id any) *MockEditRepository_Find_Call {
	return &MockEditRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockEditRepository_Find_Call) Run(run func(ctx context.Context, id domain.FolderID)) *MockEditRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FolderID
		if args[1] != nil {
			arg1 = args[1].(domain.FolderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEditRepository_Find_Call) Return(folder domain.Folder, err error) *MockEditRepository_Find_Call {
	_c.Call.Return(folder, err)
	return _c
}

func (_c *MockEditRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id domain.FolderID) (domain.Folder, error)) *MockEditRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockEditRepository
func (_mock *MockEditRepository) Update(ctx context.Context, folder domain.Folder) error {
	ret := _mock.Called(ctx, folder)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Folder) error); ok {
		r0 = returnFunc(ctx, folder)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEditRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEditRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - folder domain.Folder
func (_e *MockEditRepository_Expecter) Update(ctx any, folder any) *MockEditRepository_Update_Call {
	return &MockEditRepository_Update_Call{Call: _e.mock.On("Update", ctx, folder)}
}

func (_c *MockEditRepository_Update_Call) Run(run func(ctx context.Context, folder domain.Folder)) *MockEditRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Folder
		if args[1] != nil {
			arg1 = args[1].(domain.Folder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEditRepository_Update_Call) Return(err error) *MockEditRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEditRepository_Update_Call) RunAndReturn(run func(ctx context.Context, folder domain.Folder) error) *MockEditRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPreviewDeleteRepository creates a new instance of MockPreviewDeleteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPreviewDeleteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPreviewDeleteRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPreviewDeleteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPreviewDeleteRepository is an autogenerated mock type for the PreviewDeleteRepository type
type MockPreviewDeleteRepository struct {
	mock.Mock
}

type MockPreviewDeleteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPreviewDeleteRepository) EXPECT() *MockPreviewDeleteRepository_Expecter {
	return &MockPreviewDeleteRepository_Expecter{mock: &_m.Mock}
}

// CountSnippetsInSubtree provides a mock function for the type MockPreviewDeleteRepository
func (_mock *MockPreviewDeleteRepository) CountSnippetsInSubtree(ctx context.Context, id domain.FolderID) (int, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountSnippetsInSubtree")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) (int, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) int); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FolderID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPreviewDeleteRepository_CountSnippetsInSubtree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSnippetsInSubtree'
type MockPreviewDeleteRepository_CountSnippetsInSubtree_Call struct {
	*mock.Call
}

// CountSnippetsInSubtree is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.FolderID
func (_e *MockPreviewDeleteRepository_Expecter) CountSnippetsInSubtree(ctx any, id any) *MockPreviewDeleteRepository_CountSnippetsInSubtree_Call {
	return &MockPreviewDeleteRepository_CountSnippetsInSubtree_Call{Call: _e.mock.On("CountSnippetsInSubtree", ctx, id)}
}

func (_c *MockPreviewDeleteRepository_CountSnippetsInSubtree_Call) Run(run func(ctx context.Context, id domain.FolderID)) *MockPreviewDeleteRepository_CountSnippetsInSubtree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FolderID
		if args[1] != nil {
			arg1 = args[1].(domain.FolderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPreviewDeleteRepository_CountSnippetsInSubtree_Call) Return(n int, err error) *MockPreviewDeleteRepository_CountSnippetsInSubtree_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPreviewDeleteRepository_CountSnippetsInSubtree_Call) RunAndReturn(run func(ctx context.Context, id domain.FolderID) (int, error)) *MockPreviewDeleteRepository_CountSnippetsInSubtree_Call {
	_c.Call.Return(run)
	return _c
}

// CountSubfolders provides a mock function for the type MockPreviewDeleteRepository
func (_mock *MockPreviewDeleteRepository) CountSubfolders(ctx context.Context, id domain.FolderID) (int, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountSubfolders")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) (int, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) int); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FolderID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPreviewDeleteRepository_CountSubfolders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSubfolders'
type MockPreviewDeleteRepository_CountSubfolders_Call struct {
	*mock.Call
}

// CountSubfolders is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.FolderID
func (_e *MockPreviewDeleteRepository_Expecter) CountSubfolders(ctx any, id any) *MockPreviewDeleteRepository_CountSubfolders_Call {
	return &MockPreviewDeleteRepository_CountSubfolders_Call{Call: _e.mock.On("CountSubfolders", ctx, id)}
}

func (_c *MockPreviewDeleteRepository_CountSubfolders_Call) Run(run func(ctx context.Context, id domain.FolderID)) *MockPreviewDeleteRepository_CountSubfolders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FolderID
		if args[1] != nil {
			arg1 = args[1].(domain.FolderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPreviewDeleteRepository_CountSubfolders_Call) Return(n int, err error) *MockPreviewDeleteRepository_CountSubfolders_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPreviewDeleteRepository_CountSubfolders_Call) RunAndReturn(run func(ctx context.Context, id domain.FolderID) (int, error)) *MockPreviewDeleteRepository_CountSubfolders_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockPreviewDeleteRepository
func (_mock *MockPreviewDeleteRepository) Find(ctx context.Context, id domain.FolderID) (domain.Folder, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Folder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) (domain.Folder, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) domain.Folder); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Folder)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FolderID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPreviewDeleteRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockPreviewDeleteRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.FolderID
func (_e *MockPreviewDeleteRepository_Expecter) Find(ctx any, id any) *MockPreviewDeleteRepository_Find_Call {
	return &MockPreviewDeleteRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockPreviewDeleteRepository_Find_Call) Run(run func(ctx context.Context, id domain.FolderID)) *MockPreviewDeleteRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FolderID
		if args[1] != nil {
			arg1 = args[1].(domain.FolderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPreviewDeleteRepository_Find_Call) Return(folder domain.Folder, err error) *MockPreviewDeleteRepository_Find_Call {
	_c.Call.Return(folder, err)
	return _c
}

func (_c *MockPreviewDeleteRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id domain.FolderID) (domain.Folder, error)) *MockPreviewDeleteRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}
