// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package folder_test

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateRepository creates a new instance of MockCreateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCreateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCreateRepository is an autogenerated mock type for the CreateRepository type
type MockCreateRepository struct {
	mock.Mock
}

type MockCreateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateRepository) EXPECT() *MockCreateRepository_Expecter {
	return &MockCreateRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockCreateRepository
func (_mock *MockCreateRepository) Find(ctx context.Context, id domain.FolderID) (domain.Folder, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Folder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) (domain.Folder, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) domain.Folder); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Folder)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FolderID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCreateRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.FolderID
func (_e *MockCreateRepository_Expecter) Find(ctx any, id any) *MockCreateRepository_Find_Call {
	return &MockCreateRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockCreateRepository_Find_Call) Run(run func(ctx context.Context, id domain.FolderID)) *MockCreateRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FolderID
		if args[1] != nil {
			arg1 = args[1].(domain.FolderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateRepository_Find_Call) Return(folder domain.Folder, err error) *MockCreateRepository_Find_Call {
	_c.Call.Return(folder, err)
	return _c
}

func (_c *MockCreateRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id domain.FolderID) (domain.Folder, error)) *MockCreateRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockCreateRepository
func (_mock *MockCreateRepository) Insert(ctx context.Context, folder domain.Folder) error {
	ret := _mock.Called(ctx, folder)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Folder) error); ok {
		r0 = returnFunc(ctx, folder)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreateRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCreateRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - folder domain.Folder
func (_e *MockCreateRepository_Expecter) Insert(ctx any, folder any) *MockCreateRepository_Insert_Call {
	return &MockCreateRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, folder)}
}

func (_c *MockCreateRepository_Insert_Call) Run(run func(ctx context.Context, folder domain.Folder)) *MockCreateRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Folder
		if args[1] != nil {
			arg1 = args[1].(domain.Folder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateRepository_Insert_Call) Return(err error) *MockCreateRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreateRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, folder domain.Folder) error) *MockCreateRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRenameRepository creates a new instance of MockRenameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRenameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRenameRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRenameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRenameRepository is an autogenerated mock type for the RenameRepository type
type MockRenameRepository struct {
	mock.Mock
}

type MockRenameRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRenameRepository) EXPECT() *MockRenameRepository_Expecter {
	return &MockRenameRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockRenameRepository
func (_mock *MockRenameRepository) Find(ctx context.Context, id domain.FolderID) (domain.Folder, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Folder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) (domain.Folder, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FolderID) domain.Folder); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Folder)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FolderID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRenameRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockRenameRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.FolderID
func (_e *MockRenameRepository_Expecter) Find(ctx any, id any) *MockRenameRepository_Find_Call {
	return &MockRenameRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockRenameRepository_Find_Call) Run(run func(ctx context.Context, id domain.FolderID)) *MockRenameRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FolderID
		if args[1] != nil {
			arg1 = args[1].(domain.FolderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRenameRepository_Find_Call) Return(folder domain.Folder, err error) *MockRenameRepository_Find_Call {
	_c.Call.Return(folder, err)
	return _c
}

func (_c *MockRenameRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id domain.FolderID) (domain.Folder, error)) *MockRenameRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRenameRepository
func (_mock *MockRenameRepository) Update(ctx context.Context, folder domain.Folder) error {
	ret := _mock.Called(ctx, folder)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Folder) error); ok {
		r0 = returnFunc(ctx, folder)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRenameRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRenameRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - folder domain.Folder
func (_e *MockRenameRepository_Expecter) Update(ctx any, folder any) *MockRenameRepository_Update_Call {
	return &MockRenameRepository_Update_Call{Call: _e.mock.On("Update", ctx, folder)}
}

func (_c *MockRenameRepository_Update_Call) Run(run func(ctx context.Context, folder domain.Folder)) *MockRenameRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Folder
		if args[1] != nil {
			arg1 = args[1].(domain.Folder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRenameRepository_Update_Call) Return(err error) *MockRenameRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRenameRepository_Update_Call) RunAndReturn(run func(ctx context.Context, folder domain.Folder) error) *MockRenameRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
