// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package overlay_test

import (
	"charm.land/bubbles/v2/key"
	"charm.land/bubbletea/v2"
	"github.com/DannyFestor/TuiSnip/internal/adapters/tui/overlay"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBase creates a new instance of MockBase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBase[O any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBase[O] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBase[O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBase is an autogenerated mock type for the Base type
type MockBase[O any] struct {
	mock.Mock
}

type MockBase_Expecter[O any] struct {
	mock *mock.Mock
}

func (_m *MockBase[O]) EXPECT() *MockBase_Expecter[O] {
	return &MockBase_Expecter[O]{mock: &_m.Mock}
}

// FullHelp provides a mock function for the type MockBase
func (_mock *MockBase[O]) FullHelp() [][]key.Binding {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FullHelp")
	}

	var r0 [][]key.Binding
	if returnFunc, ok := ret.Get(0).(func() [][]key.Binding); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]key.Binding)
		}
	}
	return r0
}

// MockBase_FullHelp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullHelp'
type MockBase_FullHelp_Call[O any] struct {
	*mock.Call
}

// FullHelp is a helper method to define mock.On call
func (_e *MockBase_Expecter[O]) FullHelp() *MockBase_FullHelp_Call[O] {
	return &MockBase_FullHelp_Call[O]{Call: _e.mock.On("FullHelp")}
}

func (_c *MockBase_FullHelp_Call[O]) Run(run func()) *MockBase_FullHelp_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBase_FullHelp_Call[O]) Return(bindingss [][]key.Binding) *MockBase_FullHelp_Call[O] {
	_c.Call.Return(bindingss)
	return _c
}

func (_c *MockBase_FullHelp_Call[O]) RunAndReturn(run func() [][]key.Binding) *MockBase_FullHelp_Call[O] {
	_c.Call.Return(run)
	return _c
}

// ShortHelp provides a mock function for the type MockBase
func (_mock *MockBase[O]) ShortHelp() []key.Binding {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShortHelp")
	}

	var r0 []key.Binding
	if returnFunc, ok := ret.Get(0).(func() []key.Binding); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]key.Binding)
		}
	}
	return r0
}

// MockBase_ShortHelp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShortHelp'
type MockBase_ShortHelp_Call[O any] struct {
	*mock.Call
}

// ShortHelp is a helper method to define mock.On call
func (_e *MockBase_Expecter[O]) ShortHelp() *MockBase_ShortHelp_Call[O] {
	return &MockBase_ShortHelp_Call[O]{Call: _e.mock.On("ShortHelp")}
}

func (_c *MockBase_ShortHelp_Call[O]) Run(run func()) *MockBase_ShortHelp_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBase_ShortHelp_Call[O]) Return(bindings []key.Binding) *MockBase_ShortHelp_Call[O] {
	_c.Call.Return(bindings)
	return _c
}

func (_c *MockBase_ShortHelp_Call[O]) RunAndReturn(run func() []key.Binding) *MockBase_ShortHelp_Call[O] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBase
func (_mock *MockBase[O]) Update(msg tea.Msg) overlay.Step[O] {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 overlay.Step[O]
	if returnFunc, ok := ret.Get(0).(func(tea.Msg) overlay.Step[O]); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Get(0).(overlay.Step[O])
	}
	return r0
}

// MockBase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBase_Update_Call[O any] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - msg tea.Msg
func (_e *MockBase_Expecter[O]) Update(msg any) *MockBase_Update_Call[O] {
	return &MockBase_Update_Call[O]{Call: _e.mock.On("Update", msg)}
}

func (_c *MockBase_Update_Call[O]) Run(run func(msg tea.Msg)) *MockBase_Update_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tea.Msg
		if args[0] != nil {
			arg0 = args[0].(tea.Msg)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBase_Update_Call[O]) Return(step overlay.Step[O]) *MockBase_Update_Call[O] {
	_c.Call.Return(step)
	return _c
}

func (_c *MockBase_Update_Call[O]) RunAndReturn(run func(msg tea.Msg) overlay.Step[O]) *MockBase_Update_Call[O] {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function for the type MockBase
func (_mock *MockBase[O]) View() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBase_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockBase_View_Call[O any] struct {
	*mock.Call
}

// View is a helper method to define mock.On call
func (_e *MockBase_Expecter[O]) View() *MockBase_View_Call[O] {
	return &MockBase_View_Call[O]{Call: _e.mock.On("View")}
}

func (_c *MockBase_View_Call[O]) Run(run func()) *MockBase_View_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBase_View_Call[O]) Return(s string) *MockBase_View_Call[O] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBase_View_Call[O]) RunAndReturn(run func() string) *MockBase_View_Call[O] {
	_c.Call.Return(run)
	return _c
}

// ViewUnder provides a mock function for the type MockBase
func (_mock *MockBase[O]) ViewUnder(hints []key.Binding) string {
	ret := _mock.Called(hints)

	if len(ret) == 0 {
		panic("no return value specified for ViewUnder")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]key.Binding) string); ok {
		r0 = returnFunc(hints)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBase_ViewUnder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViewUnder'
type MockBase_ViewUnder_Call[O any] struct {
	*mock.Call
}

// ViewUnder is a helper method to define mock.On call
//   - hints []key.Binding
func (_e *MockBase_Expecter[O]) ViewUnder(hints any) *MockBase_ViewUnder_Call[O] {
	return &MockBase_ViewUnder_Call[O]{Call: _e.mock.On("ViewUnder", hints)}
}

func (_c *MockBase_ViewUnder_Call[O]) Run(run func(hints []key.Binding)) *MockBase_ViewUnder_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []key.Binding
		if args[0] != nil {
			arg0 = args[0].([]key.Binding)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBase_ViewUnder_Call[O]) Return(s string) *MockBase_ViewUnder_Call[O] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBase_ViewUnder_Call[O]) RunAndReturn(run func(hints []key.Binding) string) *MockBase_ViewUnder_Call[O] {
	_c.Call.Return(run)
	return _c
}

// NewMockOverlay creates a new instance of MockOverlay. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOverlay[O any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOverlay[O] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOverlay[O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOverlay is an autogenerated mock type for the Overlay type
type MockOverlay[O any] struct {
	mock.Mock
}

type MockOverlay_Expecter[O any] struct {
	mock *mock.Mock
}

func (_m *MockOverlay[O]) EXPECT() *MockOverlay_Expecter[O] {
	return &MockOverlay_Expecter[O]{mock: &_m.Mock}
}

// FullHelp provides a mock function for the type MockOverlay
func (_mock *MockOverlay[O]) FullHelp() [][]key.Binding {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FullHelp")
	}

	var r0 [][]key.Binding
	if returnFunc, ok := ret.Get(0).(func() [][]key.Binding); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]key.Binding)
		}
	}
	return r0
}

// MockOverlay_FullHelp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullHelp'
type MockOverlay_FullHelp_Call[O any] struct {
	*mock.Call
}

// FullHelp is a helper method to define mock.On call
func (_e *MockOverlay_Expecter[O]) FullHelp() *MockOverlay_FullHelp_Call[O] {
	return &MockOverlay_FullHelp_Call[O]{Call: _e.mock.On("FullHelp")}
}

func (_c *MockOverlay_FullHelp_Call[O]) Run(run func()) *MockOverlay_FullHelp_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOverlay_FullHelp_Call[O]) Return(bindingss [][]key.Binding) *MockOverlay_FullHelp_Call[O] {
	_c.Call.Return(bindingss)
	return _c
}

func (_c *MockOverlay_FullHelp_Call[O]) RunAndReturn(run func() [][]key.Binding) *MockOverlay_FullHelp_Call[O] {
	_c.Call.Return(run)
	return _c
}

// ShortHelp provides a mock function for the type MockOverlay
func (_mock *MockOverlay[O]) ShortHelp() []key.Binding {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShortHelp")
	}

	var r0 []key.Binding
	if returnFunc, ok := ret.Get(0).(func() []key.Binding); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]key.Binding)
		}
	}
	return r0
}

// MockOverlay_ShortHelp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShortHelp'
type MockOverlay_ShortHelp_Call[O any] struct {
	*mock.Call
}

// ShortHelp is a helper method to define mock.On call
func (_e *MockOverlay_Expecter[O]) ShortHelp() *MockOverlay_ShortHelp_Call[O] {
	return &MockOverlay_ShortHelp_Call[O]{Call: _e.mock.On("ShortHelp")}
}

func (_c *MockOverlay_ShortHelp_Call[O]) Run(run func()) *MockOverlay_ShortHelp_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOverlay_ShortHelp_Call[O]) Return(bindings []key.Binding) *MockOverlay_ShortHelp_Call[O] {
	_c.Call.Return(bindings)
	return _c
}

func (_c *MockOverlay_ShortHelp_Call[O]) RunAndReturn(run func() []key.Binding) *MockOverlay_ShortHelp_Call[O] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOverlay
func (_mock *MockOverlay[O]) Update(msg tea.Msg) overlay.Step[O] {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 overlay.Step[O]
	if returnFunc, ok := ret.Get(0).(func(tea.Msg) overlay.Step[O]); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Get(0).(overlay.Step[O])
	}
	return r0
}

// MockOverlay_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOverlay_Update_Call[O any] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - msg tea.Msg
func (_e *MockOverlay_Expecter[O]) Update(msg any) *MockOverlay_Update_Call[O] {
	return &MockOverlay_Update_Call[O]{Call: _e.mock.On("Update", msg)}
}

func (_c *MockOverlay_Update_Call[O]) Run(run func(msg tea.Msg)) *MockOverlay_Update_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tea.Msg
		if args[0] != nil {
			arg0 = args[0].(tea.Msg)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOverlay_Update_Call[O]) Return(step overlay.Step[O]) *MockOverlay_Update_Call[O] {
	_c.Call.Return(step)
	return _c
}

func (_c *MockOverlay_Update_Call[O]) RunAndReturn(run func(msg tea.Msg) overlay.Step[O]) *MockOverlay_Update_Call[O] {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function for the type MockOverlay
func (_mock *MockOverlay[O]) View() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOverlay_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockOverlay_View_Call[O any] struct {
	*mock.Call
}

// View is a helper method to define mock.On call
func (_e *MockOverlay_Expecter[O]) View() *MockOverlay_View_Call[O] {
	return &MockOverlay_View_Call[O]{Call: _e.mock.On("View")}
}

func (_c *MockOverlay_View_Call[O]) Run(run func()) *MockOverlay_View_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOverlay_View_Call[O]) Return(s string) *MockOverlay_View_Call[O] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOverlay_View_Call[O]) RunAndReturn(run func() string) *MockOverlay_View_Call[O] {
	_c.Call.Return(run)
	return _c
}

// NewMockParent creates a new instance of MockParent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParent[O any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParent[O] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockParent[O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockParent is an autogenerated mock type for the Parent type
type MockParent[O any] struct {
	mock.Mock
}

type MockParent_Expecter[O any] struct {
	mock *mock.Mock
}

func (_m *MockParent[O]) EXPECT() *MockParent_Expecter[O] {
	return &MockParent_Expecter[O]{mock: &_m.Mock}
}

// FullHelp provides a mock function for the type MockParent
func (_mock *MockParent[O]) FullHelp() [][]key.Binding {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FullHelp")
	}

	var r0 [][]key.Binding
	if returnFunc, ok := ret.Get(0).(func() [][]key.Binding); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]key.Binding)
		}
	}
	return r0
}

// MockParent_FullHelp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullHelp'
type MockParent_FullHelp_Call[O any] struct {
	*mock.Call
}

// FullHelp is a helper method to define mock.On call
func (_e *MockParent_Expecter[O]) FullHelp() *MockParent_FullHelp_Call[O] {
	return &MockParent_FullHelp_Call[O]{Call: _e.mock.On("FullHelp")}
}

func (_c *MockParent_FullHelp_Call[O]) Run(run func()) *MockParent_FullHelp_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParent_FullHelp_Call[O]) Return(bindingss [][]key.Binding) *MockParent_FullHelp_Call[O] {
	_c.Call.Return(bindingss)
	return _c
}

func (_c *MockParent_FullHelp_Call[O]) RunAndReturn(run func() [][]key.Binding) *MockParent_FullHelp_Call[O] {
	_c.Call.Return(run)
	return _c
}

// Received provides a mock function for the type MockParent
func (_mock *MockParent[O]) Received(outcome O) overlay.Step[O] {
	ret := _mock.Called(outcome)

	if len(ret) == 0 {
		panic("no return value specified for Received")
	}

	var r0 overlay.Step[O]
	if returnFunc, ok := ret.Get(0).(func(O) overlay.Step[O]); ok {
		r0 = returnFunc(outcome)
	} else {
		r0 = ret.Get(0).(overlay.Step[O])
	}
	return r0
}

// MockParent_Received_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Received'
type MockParent_Received_Call[O any] struct {
	*mock.Call
}

// Received is a helper method to define mock.On call
//   - outcome O
func (_e *MockParent_Expecter[O]) Received(outcome any) *MockParent_Received_Call[O] {
	return &MockParent_Received_Call[O]{Call: _e.mock.On("Received", outcome)}
}

func (_c *MockParent_Received_Call[O]) Run(run func(outcome O)) *MockParent_Received_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 O
		if args[0] != nil {
			arg0 = args[0].(O)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParent_Received_Call[O]) Return(step overlay.Step[O]) *MockParent_Received_Call[O] {
	_c.Call.Return(step)
	return _c
}

func (_c *MockParent_Received_Call[O]) RunAndReturn(run func(outcome O) overlay.Step[O]) *MockParent_Received_Call[O] {
	_c.Call.Return(run)
	return _c
}

// ShortHelp provides a mock function for the type MockParent
func (_mock *MockParent[O]) ShortHelp() []key.Binding {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShortHelp")
	}

	var r0 []key.Binding
	if returnFunc, ok := ret.Get(0).(func() []key.Binding); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]key.Binding)
		}
	}
	return r0
}

// MockParent_ShortHelp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShortHelp'
type MockParent_ShortHelp_Call[O any] struct {
	*mock.Call
}

// ShortHelp is a helper method to define mock.On call
func (_e *MockParent_Expecter[O]) ShortHelp() *MockParent_ShortHelp_Call[O] {
	return &MockParent_ShortHelp_Call[O]{Call: _e.mock.On("ShortHelp")}
}

func (_c *MockParent_ShortHelp_Call[O]) Run(run func()) *MockParent_ShortHelp_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParent_ShortHelp_Call[O]) Return(bindings []key.Binding) *MockParent_ShortHelp_Call[O] {
	_c.Call.Return(bindings)
	return _c
}

func (_c *MockParent_ShortHelp_Call[O]) RunAndReturn(run func() []key.Binding) *MockParent_ShortHelp_Call[O] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockParent
func (_mock *MockParent[O]) Update(msg tea.Msg) overlay.Step[O] {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 overlay.Step[O]
	if returnFunc, ok := ret.Get(0).(func(tea.Msg) overlay.Step[O]); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Get(0).(overlay.Step[O])
	}
	return r0
}

// MockParent_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockParent_Update_Call[O any] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - msg tea.Msg
func (_e *MockParent_Expecter[O]) Update(msg any) *MockParent_Update_Call[O] {
	return &MockParent_Update_Call[O]{Call: _e.mock.On("Update", msg)}
}

func (_c *MockParent_Update_Call[O]) Run(run func(msg tea.Msg)) *MockParent_Update_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tea.Msg
		if args[0] != nil {
			arg0 = args[0].(tea.Msg)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParent_Update_Call[O]) Return(step overlay.Step[O]) *MockParent_Update_Call[O] {
	_c.Call.Return(step)
	return _c
}

func (_c *MockParent_Update_Call[O]) RunAndReturn(run func(msg tea.Msg) overlay.Step[O]) *MockParent_Update_Call[O] {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function for the type MockParent
func (_mock *MockParent[O]) View() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockParent_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockParent_View_Call[O any] struct {
	*mock.Call
}

// View is a helper method to define mock.On call
func (_e *MockParent_Expecter[O]) View() *MockParent_View_Call[O] {
	return &MockParent_View_Call[O]{Call: _e.mock.On("View")}
}

func (_c *MockParent_View_Call[O]) Run(run func()) *MockParent_View_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParent_View_Call[O]) Return(s string) *MockParent_View_Call[O] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockParent_View_Call[O]) RunAndReturn(run func() string) *MockParent_View_Call[O] {
	_c.Call.Return(run)
	return _c
}
