// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package overlay_test

import (
	"charm.land/bubbles/v2/key"
	"charm.land/bubbletea/v2"
	"github.com/DannyFestor/TuiSnip/internal/adapters/tui/overlay"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOverlay creates a new instance of MockOverlay. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOverlay[O any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOverlay[O] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOverlay[O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOverlay is an autogenerated mock type for the Overlay type
type MockOverlay[O any] struct {
	mock.Mock
}

type MockOverlay_Expecter[O any] struct {
	mock *mock.Mock
}

func (_m *MockOverlay[O]) EXPECT() *MockOverlay_Expecter[O] {
	return &MockOverlay_Expecter[O]{mock: &_m.Mock}
}

// Hints provides a mock function for the type MockOverlay
func (_mock *MockOverlay[O]) Hints() []key.Binding {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hints")
	}

	var r0 []key.Binding
	if returnFunc, ok := ret.Get(0).(func() []key.Binding); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]key.Binding)
		}
	}
	return r0
}

// MockOverlay_Hints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hints'
type MockOverlay_Hints_Call[O any] struct {
	*mock.Call
}

// Hints is a helper method to define mock.On call
func (_e *MockOverlay_Expecter[O]) Hints() *MockOverlay_Hints_Call[O] {
	return &MockOverlay_Hints_Call[O]{Call: _e.mock.On("Hints")}
}

func (_c *MockOverlay_Hints_Call[O]) Run(run func()) *MockOverlay_Hints_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOverlay_Hints_Call[O]) Return(bindings []key.Binding) *MockOverlay_Hints_Call[O] {
	_c.Call.Return(bindings)
	return _c
}

func (_c *MockOverlay_Hints_Call[O]) RunAndReturn(run func() []key.Binding) *MockOverlay_Hints_Call[O] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOverlay
func (_mock *MockOverlay[O]) Update(msg tea.Msg) overlay.Step[O] {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 overlay.Step[O]
	if returnFunc, ok := ret.Get(0).(func(tea.Msg) overlay.Step[O]); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Get(0).(overlay.Step[O])
	}
	return r0
}

// MockOverlay_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOverlay_Update_Call[O any] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - msg tea.Msg
func (_e *MockOverlay_Expecter[O]) Update(msg any) *MockOverlay_Update_Call[O] {
	return &MockOverlay_Update_Call[O]{Call: _e.mock.On("Update", msg)}
}

func (_c *MockOverlay_Update_Call[O]) Run(run func(msg tea.Msg)) *MockOverlay_Update_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tea.Msg
		if args[0] != nil {
			arg0 = args[0].(tea.Msg)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOverlay_Update_Call[O]) Return(step overlay.Step[O]) *MockOverlay_Update_Call[O] {
	_c.Call.Return(step)
	return _c
}

func (_c *MockOverlay_Update_Call[O]) RunAndReturn(run func(msg tea.Msg) overlay.Step[O]) *MockOverlay_Update_Call[O] {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function for the type MockOverlay
func (_mock *MockOverlay[O]) View() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOverlay_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockOverlay_View_Call[O any] struct {
	*mock.Call
}

// View is a helper method to define mock.On call
func (_e *MockOverlay_Expecter[O]) View() *MockOverlay_View_Call[O] {
	return &MockOverlay_View_Call[O]{Call: _e.mock.On("View")}
}

func (_c *MockOverlay_View_Call[O]) Run(run func()) *MockOverlay_View_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOverlay_View_Call[O]) Return(s string) *MockOverlay_View_Call[O] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOverlay_View_Call[O]) RunAndReturn(run func() string) *MockOverlay_View_Call[O] {
	_c.Call.Return(run)
	return _c
}

// NewMockParent creates a new instance of MockParent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParent[O any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParent[O] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockParent[O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockParent is an autogenerated mock type for the Parent type
type MockParent[O any] struct {
	mock.Mock
}

type MockParent_Expecter[O any] struct {
	mock *mock.Mock
}

func (_m *MockParent[O]) EXPECT() *MockParent_Expecter[O] {
	return &MockParent_Expecter[O]{mock: &_m.Mock}
}

// Hints provides a mock function for the type MockParent
func (_mock *MockParent[O]) Hints() []key.Binding {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hints")
	}

	var r0 []key.Binding
	if returnFunc, ok := ret.Get(0).(func() []key.Binding); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]key.Binding)
		}
	}
	return r0
}

// MockParent_Hints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hints'
type MockParent_Hints_Call[O any] struct {
	*mock.Call
}

// Hints is a helper method to define mock.On call
func (_e *MockParent_Expecter[O]) Hints() *MockParent_Hints_Call[O] {
	return &MockParent_Hints_Call[O]{Call: _e.mock.On("Hints")}
}

func (_c *MockParent_Hints_Call[O]) Run(run func()) *MockParent_Hints_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParent_Hints_Call[O]) Return(bindings []key.Binding) *MockParent_Hints_Call[O] {
	_c.Call.Return(bindings)
	return _c
}

func (_c *MockParent_Hints_Call[O]) RunAndReturn(run func() []key.Binding) *MockParent_Hints_Call[O] {
	_c.Call.Return(run)
	return _c
}

// Received provides a mock function for the type MockParent
func (_mock *MockParent[O]) Received(outcome O) overlay.Step[O] {
	ret := _mock.Called(outcome)

	if len(ret) == 0 {
		panic("no return value specified for Received")
	}

	var r0 overlay.Step[O]
	if returnFunc, ok := ret.Get(0).(func(O) overlay.Step[O]); ok {
		r0 = returnFunc(outcome)
	} else {
		r0 = ret.Get(0).(overlay.Step[O])
	}
	return r0
}

// MockParent_Received_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Received'
type MockParent_Received_Call[O any] struct {
	*mock.Call
}

// Received is a helper method to define mock.On call
//   - outcome O
func (_e *MockParent_Expecter[O]) Received(outcome any) *MockParent_Received_Call[O] {
	return &MockParent_Received_Call[O]{Call: _e.mock.On("Received", outcome)}
}

func (_c *MockParent_Received_Call[O]) Run(run func(outcome O)) *MockParent_Received_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 O
		if args[0] != nil {
			arg0 = args[0].(O)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParent_Received_Call[O]) Return(step overlay.Step[O]) *MockParent_Received_Call[O] {
	_c.Call.Return(step)
	return _c
}

func (_c *MockParent_Received_Call[O]) RunAndReturn(run func(outcome O) overlay.Step[O]) *MockParent_Received_Call[O] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockParent
func (_mock *MockParent[O]) Update(msg tea.Msg) overlay.Step[O] {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 overlay.Step[O]
	if returnFunc, ok := ret.Get(0).(func(tea.Msg) overlay.Step[O]); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Get(0).(overlay.Step[O])
	}
	return r0
}

// MockParent_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockParent_Update_Call[O any] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - msg tea.Msg
func (_e *MockParent_Expecter[O]) Update(msg any) *MockParent_Update_Call[O] {
	return &MockParent_Update_Call[O]{Call: _e.mock.On("Update", msg)}
}

func (_c *MockParent_Update_Call[O]) Run(run func(msg tea.Msg)) *MockParent_Update_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tea.Msg
		if args[0] != nil {
			arg0 = args[0].(tea.Msg)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParent_Update_Call[O]) Return(step overlay.Step[O]) *MockParent_Update_Call[O] {
	_c.Call.Return(step)
	return _c
}

func (_c *MockParent_Update_Call[O]) RunAndReturn(run func(msg tea.Msg) overlay.Step[O]) *MockParent_Update_Call[O] {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function for the type MockParent
func (_mock *MockParent[O]) View() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockParent_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockParent_View_Call[O any] struct {
	*mock.Call
}

// View is a helper method to define mock.On call
func (_e *MockParent_Expecter[O]) View() *MockParent_View_Call[O] {
	return &MockParent_View_Call[O]{Call: _e.mock.On("View")}
}

func (_c *MockParent_View_Call[O]) Run(run func()) *MockParent_View_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParent_View_Call[O]) Return(s string) *MockParent_View_Call[O] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockParent_View_Call[O]) RunAndReturn(run func() string) *MockParent_View_Call[O] {
	_c.Call.Return(run)
	return _c
}
