// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package overlay_test

import (
	"charm.land/bubbles/v2/key"
	"charm.land/bubbletea/v2"
	"github.com/DannyFestor/TuiSnip/internal/adapters/tui/overlay"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOverlay creates a new instance of MockOverlay. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOverlay(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOverlay {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOverlay{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOverlay is an autogenerated mock type for the Overlay type
type MockOverlay struct {
	mock.Mock
}

type MockOverlay_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOverlay) EXPECT() *MockOverlay_Expecter {
	return &MockOverlay_Expecter{mock: &_m.Mock}
}

// Hints provides a mock function for the type MockOverlay
func (_mock *MockOverlay) Hints() []key.Binding {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hints")
	}

	var r0 []key.Binding
	if returnFunc, ok := ret.Get(0).(func() []key.Binding); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]key.Binding)
		}
	}
	return r0
}

// MockOverlay_Hints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hints'
type MockOverlay_Hints_Call struct {
	*mock.Call
}

// Hints is a helper method to define mock.On call
func (_e *MockOverlay_Expecter) Hints() *MockOverlay_Hints_Call {
	return &MockOverlay_Hints_Call{Call: _e.mock.On("Hints")}
}

func (_c *MockOverlay_Hints_Call) Run(run func()) *MockOverlay_Hints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOverlay_Hints_Call) Return(bindings []key.Binding) *MockOverlay_Hints_Call {
	_c.Call.Return(bindings)
	return _c
}

func (_c *MockOverlay_Hints_Call) RunAndReturn(run func() []key.Binding) *MockOverlay_Hints_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOverlay
func (_mock *MockOverlay) Update(msg tea.Msg) overlay.Step {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 overlay.Step
	if returnFunc, ok := ret.Get(0).(func(tea.Msg) overlay.Step); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Get(0).(overlay.Step)
	}
	return r0
}

// MockOverlay_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOverlay_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - msg tea.Msg
func (_e *MockOverlay_Expecter) Update(msg any) *MockOverlay_Update_Call {
	return &MockOverlay_Update_Call{Call: _e.mock.On("Update", msg)}
}

func (_c *MockOverlay_Update_Call) Run(run func(msg tea.Msg)) *MockOverlay_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tea.Msg
		if args[0] != nil {
			arg0 = args[0].(tea.Msg)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOverlay_Update_Call) Return(step overlay.Step) *MockOverlay_Update_Call {
	_c.Call.Return(step)
	return _c
}

func (_c *MockOverlay_Update_Call) RunAndReturn(run func(msg tea.Msg) overlay.Step) *MockOverlay_Update_Call {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function for the type MockOverlay
func (_mock *MockOverlay) View() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOverlay_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockOverlay_View_Call struct {
	*mock.Call
}

// View is a helper method to define mock.On call
func (_e *MockOverlay_Expecter) View() *MockOverlay_View_Call {
	return &MockOverlay_View_Call{Call: _e.mock.On("View")}
}

func (_c *MockOverlay_View_Call) Run(run func()) *MockOverlay_View_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOverlay_View_Call) Return(s string) *MockOverlay_View_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOverlay_View_Call) RunAndReturn(run func() string) *MockOverlay_View_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockParent creates a new instance of MockParent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParent {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockParent{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockParent is an autogenerated mock type for the Parent type
type MockParent struct {
	mock.Mock
}

type MockParent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParent) EXPECT() *MockParent_Expecter {
	return &MockParent_Expecter{mock: &_m.Mock}
}

// Hints provides a mock function for the type MockParent
func (_mock *MockParent) Hints() []key.Binding {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hints")
	}

	var r0 []key.Binding
	if returnFunc, ok := ret.Get(0).(func() []key.Binding); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]key.Binding)
		}
	}
	return r0
}

// MockParent_Hints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hints'
type MockParent_Hints_Call struct {
	*mock.Call
}

// Hints is a helper method to define mock.On call
func (_e *MockParent_Expecter) Hints() *MockParent_Hints_Call {
	return &MockParent_Hints_Call{Call: _e.mock.On("Hints")}
}

func (_c *MockParent_Hints_Call) Run(run func()) *MockParent_Hints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParent_Hints_Call) Return(bindings []key.Binding) *MockParent_Hints_Call {
	_c.Call.Return(bindings)
	return _c
}

func (_c *MockParent_Hints_Call) RunAndReturn(run func() []key.Binding) *MockParent_Hints_Call {
	_c.Call.Return(run)
	return _c
}

// Received provides a mock function for the type MockParent
func (_mock *MockParent) Received(outcome overlay.Outcome) overlay.Step {
	ret := _mock.Called(outcome)

	if len(ret) == 0 {
		panic("no return value specified for Received")
	}

	var r0 overlay.Step
	if returnFunc, ok := ret.Get(0).(func(overlay.Outcome) overlay.Step); ok {
		r0 = returnFunc(outcome)
	} else {
		r0 = ret.Get(0).(overlay.Step)
	}
	return r0
}

// MockParent_Received_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Received'
type MockParent_Received_Call struct {
	*mock.Call
}

// Received is a helper method to define mock.On call
//   - outcome overlay.Outcome
func (_e *MockParent_Expecter) Received(outcome any) *MockParent_Received_Call {
	return &MockParent_Received_Call{Call: _e.mock.On("Received", outcome)}
}

func (_c *MockParent_Received_Call) Run(run func(outcome overlay.Outcome)) *MockParent_Received_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 overlay.Outcome
		if args[0] != nil {
			arg0 = args[0].(overlay.Outcome)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParent_Received_Call) Return(step overlay.Step) *MockParent_Received_Call {
	_c.Call.Return(step)
	return _c
}

func (_c *MockParent_Received_Call) RunAndReturn(run func(outcome overlay.Outcome) overlay.Step) *MockParent_Received_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockParent
func (_mock *MockParent) Update(msg tea.Msg) overlay.Step {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 overlay.Step
	if returnFunc, ok := ret.Get(0).(func(tea.Msg) overlay.Step); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Get(0).(overlay.Step)
	}
	return r0
}

// MockParent_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockParent_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - msg tea.Msg
func (_e *MockParent_Expecter) Update(msg any) *MockParent_Update_Call {
	return &MockParent_Update_Call{Call: _e.mock.On("Update", msg)}
}

func (_c *MockParent_Update_Call) Run(run func(msg tea.Msg)) *MockParent_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tea.Msg
		if args[0] != nil {
			arg0 = args[0].(tea.Msg)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParent_Update_Call) Return(step overlay.Step) *MockParent_Update_Call {
	_c.Call.Return(step)
	return _c
}

func (_c *MockParent_Update_Call) RunAndReturn(run func(msg tea.Msg) overlay.Step) *MockParent_Update_Call {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function for the type MockParent
func (_mock *MockParent) View() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockParent_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockParent_View_Call struct {
	*mock.Call
}

// View is a helper method to define mock.On call
func (_e *MockParent_Expecter) View() *MockParent_View_Call {
	return &MockParent_View_Call{Call: _e.mock.On("View")}
}

func (_c *MockParent_View_Call) Run(run func()) *MockParent_View_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParent_View_Call) Return(s string) *MockParent_View_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockParent_View_Call) RunAndReturn(run func() string) *MockParent_View_Call {
	_c.Call.Return(run)
	return _c
}
