// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package search_test

import (
	"context"

	"github.com/DannyFestor/TuiSnip/internal/domain"
	"github.com/DannyFestor/TuiSnip/internal/domain/value"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSearcher creates a new instance of MockSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearcher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSearcher is an autogenerated mock type for the Searcher type
type MockSearcher struct {
	mock.Mock
}

type MockSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearcher) EXPECT() *MockSearcher_Expecter {
	return &MockSearcher_Expecter{mock: &_m.Mock}
}

// Search provides a mock function for the type MockSearcher
func (_mock *MockSearcher) Search(ctx context.Context, query value.SearchQuery) ([]domain.SearchHit, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []domain.SearchHit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, value.SearchQuery) ([]domain.SearchHit, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, value.SearchQuery) []domain.SearchHit); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SearchHit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, value.SearchQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearcher_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockSearcher_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query value.SearchQuery
func (_e *MockSearcher_Expecter) Search(ctx any, query any) *MockSearcher_Search_Call {
	return &MockSearcher_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *MockSearcher_Search_Call) Run(run func(ctx context.Context, query value.SearchQuery)) *MockSearcher_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 value.SearchQuery
		if args[1] != nil {
			arg1 = args[1].(value.SearchQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSearcher_Search_Call) Return(searchHits []domain.SearchHit, err error) *MockSearcher_Search_Call {
	_c.Call.Return(searchHits, err)
	return _c
}

func (_c *MockSearcher_Search_Call) RunAndReturn(run func(ctx context.Context, query value.SearchQuery) ([]domain.SearchHit, error)) *MockSearcher_Search_Call {
	_c.Call.Return(run)
	return _c
}
