package agent_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const (
	exitPass = 0
	exitDeny = 2
	exitAsk  = 3

	repoPlaceholder = "{{REPO}}"
	// The stubs log every call here and fail the call whose "<tool> <first arg>" starts
	// with STUB_FAIL.
	stubScript = `#!/bin/sh
echo "$(basename "$0") $*" >> "$STUB_LOG"
if [ -n "$STUB_FAIL" ]; then
	case "$(basename "$0") $1" in "$STUB_FAIL"*) echo "stub: $(basename "$0") $1 failed" >&2; exit 1 ;; esac
fi
`
	generatedHeader = "// Code generated by go-enum. DO NOT EDIT.\n\npackage value\n"
	goFile          = "package clip\n"
	maxBlocks       = 3
)

type result struct {
	code   int
	stdout string
	stderr string
}

type claudeOutput struct {
	HookSpecificOutput struct {
		PermissionDecision string `json:"permissionDecision"`
	} `json:"hookSpecificOutput"`
	SystemMessage string `json:"systemMessage"`
}

type antigravityOutput struct {
	Decision    string  `json:"decision"`
	Reason      *string `json:"reason"`
	InjectSteps []struct {
		EphemeralMessage string `json:"ephemeralMessage"`
	} `json:"injectSteps"`
}

type opencodeToolCall struct {
	Args struct {
		PatchText string `json:"patchText"`
		Command   string `json:"command"`
	} `json:"args"`
}

type sandbox struct {
	repo    string
	stubLog string
	env     []string
}

func newSandbox(t *testing.T) *sandbox {
	t.Helper()

	repo := t.TempDir()
	stubDir := t.TempDir()
	box := &sandbox{repo: repo, stubLog: filepath.Join(stubDir, "calls.log")}

	for _, tool := range []string{"go", "golangci-lint", "go-arch-lint"} {
		writeFile(t, filepath.Join(stubDir, tool), stubScript, 0o755)
	}

	box.env = append(environWithoutGit(),
		"PATH="+stubDir+string(os.PathListSeparator)+os.Getenv("PATH"),
		"STUB_LOG="+box.stubLog,
		"STUB_FAIL=",
		"GIT_CONFIG_GLOBAL=/dev/null",
		"GIT_CONFIG_NOSYSTEM=1",
		"GIT_AUTHOR_NAME=Test", "GIT_AUTHOR_EMAIL=test@example.com",
		"GIT_COMMITTER_NAME=Test", "GIT_COMMITTER_EMAIL=test@example.com",
	)
	box.git(t, "init", "--quiet", "--initial-branch=main")
	writeFile(t, filepath.Join(repo, "README.md"), "# test\n", 0o644)
	box.git(t, "add", ".")
	box.git(t, "commit", "--quiet", "-m", "chore: init")
	box.git(t, "update-ref", "refs/remotes/origin/main", "HEAD")
	box.git(t, "switch", "--quiet", "-c", "feature")

	return box
}

func environWithoutGit() []string {
	return slices.DeleteFunc(os.Environ(), func(entry string) bool {
		return strings.HasPrefix(entry, "GIT_")
	})
}

func (s *sandbox) git(t *testing.T, args ...string) {
	t.Helper()

	cmd := exec.CommandContext(t.Context(), "git", args...) //nolint:gosec // G204: git arguments written by the tests
	cmd.Dir = s.repo
	cmd.Env = s.env

	out, err := cmd.CombinedOutput()
	require.NoError(t, err, string(out))
}

func (s *sandbox) write(t *testing.T, path, content string) {
	t.Helper()

	full := filepath.Join(s.repo, path)
	require.NoError(t, os.MkdirAll(filepath.Dir(full), 0o750))
	writeFile(t, full, content, 0o644)
}

func (s *sandbox) failStub(call string) {
	s.env = append(s.env, "STUB_FAIL="+call)
}

func (s *sandbox) stubCalls(t *testing.T) []string {
	t.Helper()

	log, err := os.ReadFile(s.stubLog)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}

	require.NoError(t, err)

	return strings.Split(strings.TrimSpace(string(log)), "\n")
}

func (s *sandbox) run(t *testing.T, stdin, script string, args ...string) result {
	t.Helper()

	path, err := filepath.Abs(script)
	require.NoError(t, err)

	var stdout, stderr bytes.Buffer

	cmd := exec.CommandContext(t.Context(), path, args...) //nolint:gosec // G204: the scripts under test
	cmd.Dir = s.repo
	cmd.Env = s.env
	cmd.Stdin = strings.NewReader(stdin)
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	var exitErr *exec.ExitError
	if err := cmd.Run(); err != nil && !errors.As(err, &exitErr) {
		require.NoError(t, err)
	}

	return result{code: cmd.ProcessState.ExitCode(), stdout: stdout.String(), stderr: stderr.String()}
}

func (s *sandbox) adapter(t *testing.T, system, event, fixture string) result {
	t.Helper()

	return s.run(t, s.fixture(t, system, fixture), filepath.Join("adapters", system+".sh"), event)
}

func (s *sandbox) fixture(t *testing.T, system, name string) string {
	t.Helper()

	raw, err := os.ReadFile(filepath.Join("testdata", system, name)) //nolint:gosec // G304: fixtures named by the tests
	require.NoError(t, err)

	return strings.ReplaceAll(string(raw), repoPlaceholder, s.repo)
}

func writeFile(t *testing.T, path, content string, mode os.FileMode) {
	t.Helper()

	require.NoError(t, os.WriteFile(path, []byte(content), mode))
}

func decode[T any](t *testing.T, raw string) T {
	t.Helper()

	var decoded T
	require.NoError(t, json.Unmarshal([]byte(raw), &decoded))

	return decoded
}

func TestClaudeAdapter_PreEdit(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name        string
		fixture     string
		wantCode    int
		wantStderr  string
		wantAskJSON bool
	}{
		{
			name:       "denies generator output",
			fixture:    "pre-edit-sqlcgen.json",
			wantCode:   exitDeny,
			wantStderr: "make generate-sql",
		},
		{
			name: "denies a file with a generated header", fixture: "pre-edit-generated-header.json",
			wantCode: exitDeny, wantStderr: "generated-code header",
		},
		{
			name: "denies hand-writing a generated header", fixture: "pre-write-forged-header.json",
			wantCode: exitDeny, wantStderr: "only generators may write one",
		},
		{
			name:        "asks before editing a guardrail",
			fixture:     "pre-edit-lefthook.json",
			wantCode:    exitPass,
			wantAskJSON: true,
		},
		{name: "passes an ordinary file", fixture: "pre-edit-domain.json", wantCode: exitPass},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			box := newSandbox(t)
			box.write(t, "internal/domain/value/state_enum_gen.go", generatedHeader)

			got := box.adapter(t, "claude", "pre-edit", tt.fixture)

			assert.Equal(t, tt.wantCode, got.code, got.stderr)
			assert.Contains(t, got.stderr, tt.wantStderr)

			if !tt.wantAskJSON {
				assert.Empty(t, got.stdout)

				return
			}

			output := decode[claudeOutput](t, got.stdout)
			assert.Equal(t, "ask", output.HookSpecificOutput.PermissionDecision)
		})
	}
}

func TestClaudeAdapter_PreBash(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		fixture    string
		wantCode   int
		wantStderr string
	}{
		{name: "passes a read-only command", fixture: "pre-bash-status.json", wantCode: exitPass},
		{
			name:       "denies a force-push",
			fixture:    "pre-bash-force-push.json",
			wantCode:   exitDeny,
			wantStderr: "Force-pushing",
		},
		{
			name:       "denies a heredoc written to a file",
			fixture:    "pre-bash-heredoc-write.json",
			wantCode:   exitDeny,
			wantStderr: "edit tools",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			box := newSandbox(t)

			got := box.adapter(t, "claude", "pre-bash", tt.fixture)

			assert.Equal(t, tt.wantCode, got.code, got.stderr)
			assert.Contains(t, got.stderr, tt.wantStderr)
		})
	}
}

func TestClaudeAdapter_PostEdit(t *testing.T) {
	t.Parallel()

	t.Run("skips files that are not Go", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)

		got := box.adapter(t, "claude", "post-edit", "post-write-readme.json")

		assert.Equal(t, exitPass, got.code)
		assert.Empty(t, box.stubCalls(t))
	})

	t.Run("formats the file and vets its package", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		box.write(t, "pkg/clip/clip.go", goFile)

		got := box.adapter(t, "claude", "post-edit", "post-edit-go.json")

		assert.Equal(t, exitPass, got.code, got.stderr)
		assert.Equal(
			t,
			[]string{"golangci-lint fmt pkg/clip/clip.go", "go vet -tags feature,e2e ./pkg/clip"},
			box.stubCalls(t),
		)
	})

	t.Run("reports vet findings to the agent", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		box.write(t, "pkg/clip/clip.go", goFile)
		box.failStub("go vet")

		got := box.adapter(t, "claude", "post-edit", "post-edit-go.json")

		assert.Equal(t, exitDeny, got.code)
		assert.Contains(t, got.stderr, "go vet failed")
	})
}

func TestClaudeAdapter_Stop(t *testing.T) {
	t.Parallel()

	t.Run("passes without Go changes and runs nothing", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)

		got := box.adapter(t, "claude", "stop", "stop.json")

		assert.Equal(t, exitPass, got.code)
		assert.Empty(t, box.stubCalls(t))
	})

	t.Run("checks changed packages and skips an unchanged diff", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		box.write(t, "pkg/clip/clip.go", goFile)

		first := box.adapter(t, "claude", "stop", "stop.json")
		second := box.adapter(t, "claude", "stop", "stop.json")

		assert.Equal(t, exitPass, first.code, first.stderr)
		assert.Equal(t, exitPass, second.code, second.stderr)
		assert.Equal(t, []string{
			"go build ./...",
			"go-arch-lint check",
			"golangci-lint run ./pkg/clip",
			"go test -short -race ./pkg/clip",
		}, box.stubCalls(t))
	})

	t.Run("leaves tagged test packages out of go test", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		box.write(t, "test/feature/capture_test.go", "//go:build feature\n\npackage feature_test\n")

		got := box.adapter(t, "claude", "stop", "stop.json")

		assert.Equal(t, exitPass, got.code, got.stderr)
		assert.NotContains(t, box.stubCalls(t), "go test -short -race ./test/feature")
	})

	t.Run("blocks a failing build until the cap, then lets the agent stop", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		box.write(t, "pkg/clip/clip.go", goFile)
		box.failStub("go build")

		for range maxBlocks {
			blocked := box.adapter(t, "claude", "stop", "stop.json")
			require.Equal(t, exitDeny, blocked.code)
			assert.Contains(t, blocked.stderr, "go build failed")
		}

		released := box.adapter(t, "claude", "stop", "stop.json")

		assert.Equal(t, exitPass, released.code)
		assert.Contains(t, decode[claudeOutput](t, released.stdout).SystemMessage, "go build failed")
	})
}

func TestAntigravityAdapter_Pre(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		fixture      string
		wantDecision string
		wantReason   string
	}{
		{
			name:         "denies generator output",
			fixture:      "pre-write-sqlcgen.json",
			wantDecision: "deny",
			wantReason:   "make generate-sql",
		},
		{
			name:         "asks before editing a guardrail",
			fixture:      "pre-replace-mise.json",
			wantDecision: "ask",
			wantReason:   "toolchain",
		},
		{name: "answers ask for a clean command", fixture: "pre-run-command-status.json", wantDecision: "ask"},
		{
			name:         "denies a destructive command",
			fixture:      "pre-run-command-reset.json",
			wantDecision: "deny",
			wantReason:   "reset --hard",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			box := newSandbox(t)

			got := box.adapter(t, "antigravity", "pre", tt.fixture)

			require.Equal(t, exitPass, got.code, got.stderr)

			decision := decode[antigravityOutput](t, got.stdout)
			assert.Equal(t, tt.wantDecision, decision.Decision)

			if tt.wantReason == "" {
				assert.Nil(t, decision.Reason)

				return
			}

			require.NotNil(t, decision.Reason)
			assert.Contains(t, *decision.Reason, tt.wantReason)
		})
	}
}

func TestAntigravityAdapter_PostThenPreInvocation(t *testing.T) {
	t.Parallel()

	box := newSandbox(t)
	box.write(t, "pkg/clip/clip.go", goFile)
	box.failStub("go vet")

	post := box.adapter(t, "antigravity", "post", "post-replace-go.json")
	injected := box.adapter(t, "antigravity", "pre-invocation", "pre-invocation.json")
	drained := box.adapter(t, "antigravity", "pre-invocation", "pre-invocation.json")

	assert.JSONEq(t, "{}", post.stdout)

	steps := decode[antigravityOutput](t, injected.stdout).InjectSteps
	require.Len(t, steps, 1)
	assert.Contains(t, steps[0].EphemeralMessage, "go vet failed")
	assert.JSONEq(t, "{}", drained.stdout)
}

func TestAntigravityAdapter_Stop(t *testing.T) {
	t.Parallel()

	box := newSandbox(t)
	box.write(t, "pkg/clip/clip.go", goFile)
	box.failStub("golangci-lint run")

	got := box.adapter(t, "antigravity", "stop", "stop.json")

	decision := decode[antigravityOutput](t, got.stdout)
	assert.Equal(t, "continue", decision.Decision)
	require.NotNil(t, decision.Reason)
	assert.Contains(t, *decision.Reason, "golangci-lint failed")
}

func TestOpenCodeFixtures(t *testing.T) {
	t.Parallel()

	t.Run("patch-paths lists every path an apply_patch touches", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		call := decode[opencodeToolCall](t, box.fixture(t, "opencode", "apply-patch.json"))

		got := box.run(t, call.Args.PatchText, "patch-paths.sh")

		assert.Equal(t, strings.Join([]string{
			"internal/domain/snippet.go",
			"internal/domain/tag.go",
			"internal/domain/old.go",
			"internal/adapters/sqlite/sqlcgen/old.go",
			"internal/domain/unused.go",
		}, "\n")+"\n", got.stdout)
	})

	t.Run("guard-command denies a bash call that skips hooks", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		call := decode[opencodeToolCall](t, box.fixture(t, "opencode", "bash-no-verify.json"))

		got := box.run(t, call.Args.Command, "guard-command.sh")

		assert.Equal(t, exitDeny, got.code)
		assert.Contains(t, got.stderr, "--no-verify")
	})
}

func TestGuardPath(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		path     string
		wantCode int
	}{
		{name: "denies nested mocks", path: "internal/app/snippet/mocks_test.go", wantCode: exitDeny},
		{name: "denies root mocks", path: "mocks_test.go", wantCode: exitDeny},
		{name: "denies go-enum output", path: "internal/domain/value/sort_enum.go", wantCode: exitDeny},
		{name: "denies go.sum", path: "go.sum", wantCode: exitDeny},
		{name: "denies the generated OpenCode rules", path: "opencode.json", wantCode: exitDeny},
		{
			name:     "denies the generated Language list",
			path:     "internal/domain/value/languages_gen.go",
			wantCode: exitDeny,
		},
		{name: "asks for a workflow", path: ".github/workflows/ci.yml", wantCode: exitAsk},
		{name: "asks for an agent script", path: "scripts/agent/guard-path.sh", wantCode: exitAsk},
		{name: "passes a migration", path: "db/migrations/0001_snippets.sql", wantCode: exitPass},
		{name: "passes a path outside the repo", path: "/etc/hosts", wantCode: exitPass},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			box := newSandbox(t)

			got := box.run(t, "", "guard-path.sh", tt.path)

			assert.Equal(t, tt.wantCode, got.code, got.stderr)
		})
	}
}

func TestGuardCommand(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		command  string
		wantCode int
	}{
		{
			name:     "passes a commit whose message looks like shell",
			command:  `git commit -m "a -> b; --no-verify"`,
			wantCode: exitPass,
		},
		{name: "passes a push to a branch", command: "git add . && git push -u origin feature", wantCode: exitPass},
		{name: "passes stderr redirected to stdout", command: "go test ./... 2>&1 | tail -5", wantCode: exitPass},
		{
			name:     "passes writes to /dev/null and /tmp",
			command:  "echo x >/dev/null; echo y > /tmp/out",
			wantCode: exitPass,
		},
		{name: "passes writes to TMPDIR", command: `echo x >> "$TMPDIR/out"`, wantCode: exitPass},
		{name: "passes a heredoc read by a command", command: "wc -l <<'EOF'\na > b\nEOF", wantCode: exitPass},
		{name: "passes sed without in-place", command: "sed -n 1,5p main.go", wantCode: exitPass},
		{
			name:     "passes an interpreter that only reads",
			command:  `python3 -c 'print(open("go.mod").read())'`,
			wantCode: exitPass,
		},
		{name: "passes reading core.hooksPath", command: "git config --get core.hooksPath", wantCode: exitPass},
		{name: "passes unstaging the whole tree", command: "git restore --staged .", wantCode: exitPass},
		{
			name:     "passes a commit whose message mentions LEFTHOOK",
			command:  `git commit -m "docs: deny LEFTHOOK=0"`,
			wantCode: exitPass,
		},
		{name: "denies LEFTHOOK=0 before a command", command: "LEFTHOOK=0 git commit -m x", wantCode: exitDeny},
		{name: "denies exporting LEFTHOOK", command: "export LEFTHOOK=false && git push", wantCode: exitDeny},
		{
			name:     "denies LEFTHOOK_EXCLUDE through env",
			command:  "env LEFTHOOK_EXCLUDE=lint git push",
			wantCode: exitDeny,
		},
		{
			name:     "denies LEFTHOOK_CONFIG",
			command:  "LEFTHOOK_CONFIG=/tmp/none.yml git commit -m x",
			wantCode: exitDeny,
		},
		{name: "denies commit -n", command: "git commit -nm wip", wantCode: exitDeny},
		{name: "denies --no-verify", command: "git push --no-verify", wantCode: exitDeny},
		{
			name:     "denies overriding core.hooksPath",
			command:  "git -c core.hooksPath=/dev/null commit -m x",
			wantCode: exitDeny,
		},
		{name: "denies setting core.hooksPath", command: "git config core.hooksPath .nohooks", wantCode: exitDeny},
		{name: "denies push -f", command: "git push -f origin feature", wantCode: exitDeny},
		{name: "denies a +refspec", command: "git push origin +feature", wantCode: exitDeny},
		{name: "denies a push to main", command: "git push origin HEAD:main", wantCode: exitDeny},
		{name: "denies reset --hard", command: "git reset --hard", wantCode: exitDeny},
		{name: "denies clean -f", command: "git clean -fdx", wantCode: exitDeny},
		{name: "denies a whole-tree checkout", command: "git checkout -- .", wantCode: exitDeny},
		{name: "denies a whole-tree restore", command: "git restore .", wantCode: exitDeny},
		{name: "denies stash drop", command: "git stash drop", wantCode: exitDeny},
		{name: "denies stash clear", command: "git -C . stash clear", wantCode: exitDeny},
		{name: "denies sed -i", command: "sed -i '' 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies perl -pi", command: "perl -pi -e 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies awk -i inplace", command: "awk -i inplace 1 main.go", wantCode: exitDeny},
		{name: "denies a redirect into the repo", command: "echo x > main.go", wantCode: exitDeny},
		{name: "denies tee into the repo", command: "echo x | tee -a main.go", wantCode: exitDeny},
		{
			name:     "denies an interpreter writing a file",
			command:  "python3 - <<'EOF'\nopen('main.go', 'w').write('x')\nEOF",
			wantCode: exitDeny,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			box := newSandbox(t)

			got := box.run(t, tt.command, "guard-command.sh")

			assert.Equal(t, tt.wantCode, got.code, got.stderr)
		})
	}

	t.Run("denies a bare push from main", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		box.git(t, "switch", "--quiet", "main")

		got := box.run(t, "git push", "guard-command.sh")

		assert.Equal(t, exitDeny, got.code)
	})
}
