package agent_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const (
	exitPass = 0
	exitDeny = 2
	exitAsk  = 3

	repoPlaceholder     = "{{REPO}}"
	worktreePlaceholder = "{{WT}}"
	// The stubs log every call here and fail the call whose "<tool> <first arg>" starts
	// with STUB_FAIL.
	stubScript = `#!/bin/sh
echo "$(basename "$0") $*" >> "$STUB_LOG"
if [ -n "$STUB_FAIL" ]; then
	case "$(basename "$0") $1" in "$STUB_FAIL"*) echo "stub: $(basename "$0") $1 failed" >&2; exit 1 ;; esac
fi
`
	nonASCIIText    = "Grüße 日本語 한국어 😀"
	generatedHeader = "// Code generated by go-enum. DO NOT EDIT.\n\npackage value\n"
	goFile          = "package clip\n"
	maxBlocks       = 3
	worktreeDir     = ".claude/worktrees/wt"
	worktreeBranch  = "agent"

	commentSession  = "session-1"
	commentedPath   = "internal/domain/folder.go"
	restatement     = "// Trim the name."
	selfCheckHint   = "Delete it if it says what the code does"
	askHint         = "the user will be asked"
	resubmittedHint = "submitted it again after a self-check"
)

type result struct {
	code   int
	stdout string
	stderr string
}

type claudeOutput struct {
	HookSpecificOutput struct {
		PermissionDecision string `json:"permissionDecision"`
	} `json:"hookSpecificOutput"`
	SystemMessage string `json:"systemMessage"`
}

type antigravityOutput struct {
	Decision    string  `json:"decision"`
	Reason      *string `json:"reason"`
	InjectSteps []struct {
		EphemeralMessage string `json:"ephemeralMessage"`
	} `json:"injectSteps"`
}

type opencodeToolCall struct {
	Args struct {
		PatchText string `json:"patchText"`
		Command   string `json:"command"`
	} `json:"args"`
}

type commentEdit struct {
	path     string
	replaced string
	added    string
}

func newComment(replaced, added string) commentEdit {
	return commentEdit{path: commentedPath, replaced: replaced, added: added}
}

type sandbox struct {
	repo    string
	cwd     string
	stubLog string
	env     []string
}

func newSandbox(t *testing.T) *sandbox {
	t.Helper()

	repo := t.TempDir()
	stubDir := t.TempDir()
	box := &sandbox{repo: repo, cwd: repo, stubLog: filepath.Join(stubDir, "calls.log")}

	for _, tool := range []string{"go", "golangci-lint", "go-arch-lint"} {
		writeFile(t, filepath.Join(stubDir, tool), stubScript, 0o755)
	}

	box.env = append(environWithoutGit(),
		"PATH="+stubDir+string(os.PathListSeparator)+os.Getenv("PATH"),
		"STUB_LOG="+box.stubLog,
		"STUB_FAIL=",
		// Agents run hooks under a UTF-8 locale, where macOS awk fails on a split multibyte
		// character; C.UTF-8 exists on both macOS and Linux runners.
		"LC_ALL=C.UTF-8",
		"GIT_CONFIG_GLOBAL=/dev/null",
		"GIT_CONFIG_NOSYSTEM=1",
		"GIT_AUTHOR_NAME=Test", "GIT_AUTHOR_EMAIL=test@example.com",
		"GIT_COMMITTER_NAME=Test", "GIT_COMMITTER_EMAIL=test@example.com",
	)
	box.git(t, "init", "--quiet", "--initial-branch=main")
	writeFile(t, filepath.Join(repo, "README.md"), "# test\n", 0o644)
	box.git(t, "add", ".")
	box.git(t, "commit", "--quiet", "-m", "chore: init")
	box.git(t, "update-ref", "refs/remotes/origin/main", "HEAD")
	box.git(t, "switch", "--quiet", "-c", "feature")

	return box
}

func environWithoutGit() []string {
	return slices.DeleteFunc(os.Environ(), func(entry string) bool {
		return strings.HasPrefix(entry, "GIT_")
	})
}

func (s *sandbox) git(t *testing.T, args ...string) {
	t.Helper()

	cmd := exec.CommandContext(t.Context(), "git", args...) //nolint:gosec // G204: git arguments written by the tests
	cmd.Dir = s.repo
	cmd.Env = s.env

	out, err := cmd.CombinedOutput()
	require.NoError(t, err, string(out))
}

func (s *sandbox) write(t *testing.T, path, content string) {
	t.Helper()

	full := filepath.Join(s.repo, path)
	require.NoError(t, os.MkdirAll(filepath.Dir(full), 0o750))
	writeFile(t, full, content, 0o644)
}

func (s *sandbox) addWorktree(t *testing.T, dir string) {
	t.Helper()

	s.git(t, "worktree", "add", "--quiet", "-b", worktreeBranch, dir)
}

func (s *sandbox) failStub(call string) {
	s.env = append(s.env, "STUB_FAIL="+call)
}

func (s *sandbox) stubCalls(t *testing.T) []string {
	t.Helper()

	log, err := os.ReadFile(s.stubLog)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}

	require.NoError(t, err)

	return strings.Split(strings.TrimSpace(string(log)), "\n")
}

func (s *sandbox) in(dir string) *sandbox {
	moved := *s
	moved.cwd = dir

	return &moved
}

func (s *sandbox) run(t *testing.T, stdin, script string, args ...string) result {
	t.Helper()

	path, err := filepath.Abs(script)
	require.NoError(t, err)

	var stdout, stderr bytes.Buffer

	cmd := exec.CommandContext(t.Context(), path, args...) //nolint:gosec // G204: the scripts under test
	cmd.Dir = s.cwd
	cmd.Env = s.env
	cmd.Stdin = strings.NewReader(stdin)
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	var exitErr *exec.ExitError
	if err := cmd.Run(); err != nil && !errors.As(err, &exitErr) {
		require.NoError(t, err)
	}

	return result{code: cmd.ProcessState.ExitCode(), stdout: stdout.String(), stderr: stderr.String()}
}

func (s *sandbox) guardComments(t *testing.T, edit commentEdit, flags ...string) result {
	t.Helper()

	replacedFile := filepath.Join(t.TempDir(), "replaced")
	writeFile(t, replacedFile, edit.replaced, 0o644)
	args := append(slices.Clone(flags), commentSession, edit.path, replacedFile)

	return s.run(t, edit.added, "guard-go-comments.sh", args...)
}

func (s *sandbox) adapter(t *testing.T, system, event, fixture string) result {
	t.Helper()

	return s.run(t, s.fixture(t, system, fixture), filepath.Join("adapters", system+".sh"), event)
}

func (s *sandbox) fixture(t *testing.T, system, name string) string {
	t.Helper()

	raw, err := os.ReadFile(filepath.Join("testdata", system, name)) //nolint:gosec // G304: fixtures named by the tests
	require.NoError(t, err)

	return strings.ReplaceAll(string(raw), repoPlaceholder, s.repo)
}

func writeFile(t *testing.T, path, content string, mode os.FileMode) {
	t.Helper()

	require.NoError(t, os.WriteFile(path, []byte(content), mode))
}

func decode[T any](t *testing.T, raw string) T {
	t.Helper()

	var decoded T
	require.NoError(t, json.Unmarshal([]byte(raw), &decoded))

	return decoded
}

func TestClaudeAdapter_PreEdit(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name        string
		fixture     string
		wantCode    int
		wantStderr  string
		wantAskJSON bool
	}{
		{
			name:       "denies generator output",
			fixture:    "pre-edit-sqlcgen.json",
			wantCode:   exitDeny,
			wantStderr: "make generate-sql",
		},
		{
			name: "denies a file with a generated header", fixture: "pre-edit-generated-header.json",
			wantCode: exitDeny, wantStderr: "generated-code header",
		},
		{
			name: "denies hand-writing a generated header", fixture: "pre-write-forged-header.json",
			wantCode: exitDeny, wantStderr: "only generators may write one",
		},
		{
			name:        "asks before editing a guardrail",
			fixture:     "pre-edit-lefthook.json",
			wantCode:    exitPass,
			wantAskJSON: true,
		},
		{name: "passes an ordinary file", fixture: "pre-edit-domain.json", wantCode: exitPass},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			box := newSandbox(t)
			box.write(t, "internal/domain/value/state_enum_gen.go", generatedHeader)

			got := box.adapter(t, "claude", "pre-edit", tt.fixture)

			assert.Equal(t, tt.wantCode, got.code, got.stderr)
			assert.Contains(t, got.stderr, tt.wantStderr)

			if !tt.wantAskJSON {
				assert.Empty(t, got.stdout)

				return
			}

			output := decode[claudeOutput](t, got.stdout)
			assert.Equal(t, "ask", output.HookSpecificOutput.PermissionDecision)
		})
	}
}

func TestClaudeAdapter_PreEditComment(t *testing.T) {
	t.Parallel()

	box := newSandbox(t)

	first := box.adapter(t, "claude", "pre-edit", "pre-edit-go-comment.json")
	second := box.adapter(t, "claude", "pre-edit", "pre-edit-go-comment.json")

	assert.Equal(t, exitDeny, first.code)
	assert.Contains(t, first.stderr, restatement)
	assert.Contains(t, first.stderr, askHint)
	assert.Equal(t, exitPass, second.code, second.stderr)
	assert.Equal(t, "ask", decode[claudeOutput](t, second.stdout).HookSpecificOutput.PermissionDecision)
}

func TestClaudeAdapter_PreBash(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		fixture    string
		wantCode   int
		wantStderr string
	}{
		{name: "passes a read-only command", fixture: "pre-bash-status.json", wantCode: exitPass},
		{
			name:       "denies a force-push",
			fixture:    "pre-bash-force-push.json",
			wantCode:   exitDeny,
			wantStderr: "Force-pushing",
		},
		{
			name:       "denies a heredoc written to a file",
			fixture:    "pre-bash-heredoc-write.json",
			wantCode:   exitDeny,
			wantStderr: "edit tools",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			box := newSandbox(t)

			got := box.adapter(t, "claude", "pre-bash", tt.fixture)

			assert.Equal(t, tt.wantCode, got.code, got.stderr)
			assert.Contains(t, got.stderr, tt.wantStderr)
		})
	}

	t.Run("passes a bare push from a linked worktree on a branch", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		box.git(t, "switch", "--quiet", "main")
		box.addWorktree(t, filepath.Join(box.repo, worktreeDir))

		got := box.adapter(t, "claude", "pre-bash", "pre-bash-worktree-push.json")

		assert.Equal(t, exitPass, got.code, got.stderr)
	})
}

func TestClaudeAdapter_PostEdit(t *testing.T) {
	t.Parallel()

	t.Run("skips files that are not Go", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)

		got := box.adapter(t, "claude", "post-edit", "post-write-readme.json")

		assert.Equal(t, exitPass, got.code)
		assert.Empty(t, box.stubCalls(t))
	})

	t.Run("formats the file, then vets and lints its package", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		box.write(t, "pkg/clip/clip.go", goFile)

		got := box.adapter(t, "claude", "post-edit", "post-edit-go.json")

		assert.Equal(t, exitPass, got.code, got.stderr)
		assert.Equal(t, []string{
			"golangci-lint fmt pkg/clip/clip.go",
			"go vet -tags feature,e2e ./pkg/clip",
			"golangci-lint run --allow-serial-runners ./pkg/clip",
		}, box.stubCalls(t))
	})

	t.Run("checks a file in a linked worktree from that worktree", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		box.addWorktree(t, filepath.Join(box.repo, worktreeDir))
		box.write(t, worktreeDir+"/pkg/clip/clip.go", goFile)

		got := box.adapter(t, "claude", "post-edit", "post-edit-worktree-go.json")

		assert.Equal(t, exitPass, got.code, got.stderr)
		assert.Equal(t, []string{
			"golangci-lint fmt pkg/clip/clip.go",
			"go vet -tags feature,e2e ./pkg/clip",
			"golangci-lint run --allow-serial-runners ./pkg/clip",
		}, box.stubCalls(t))
	})

	for _, step := range []string{"go vet", "golangci-lint run"} {
		t.Run("reports "+step+" findings to the agent", func(t *testing.T) {
			t.Parallel()
			box := newSandbox(t)
			box.write(t, "pkg/clip/clip.go", goFile)
			box.failStub(step)

			got := box.adapter(t, "claude", "post-edit", "post-edit-go.json")

			assert.Equal(t, exitDeny, got.code)
			assert.Contains(t, got.stderr, step+" failed")
		})
	}
}

func TestClaudeAdapter_Stop(t *testing.T) {
	t.Parallel()

	t.Run("passes without Go changes and runs nothing", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)

		got := box.adapter(t, "claude", "stop", "stop.json")

		assert.Equal(t, exitPass, got.code)
		assert.Empty(t, box.stubCalls(t))
	})

	t.Run("checks changed packages and skips an unchanged diff", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		box.write(t, "pkg/clip/clip.go", goFile)

		first := box.adapter(t, "claude", "stop", "stop.json")
		second := box.adapter(t, "claude", "stop", "stop.json")

		assert.Equal(t, exitPass, first.code, first.stderr)
		assert.Equal(t, exitPass, second.code, second.stderr)
		assert.Equal(t, []string{
			"go build ./...",
			"go-arch-lint check",
			"golangci-lint run --allow-serial-runners ./pkg/clip",
			"go test -short -race ./pkg/clip",
		}, box.stubCalls(t))
	})

	t.Run("leaves tagged test packages out of go test", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		box.write(t, "test/feature/capture_test.go", "//go:build feature\n\npackage feature_test\n")

		got := box.adapter(t, "claude", "stop", "stop.json")

		assert.Equal(t, exitPass, got.code, got.stderr)
		assert.NotContains(t, box.stubCalls(t), "go test -short -race ./test/feature")
	})

	t.Run("blocks a failing build until the cap, then lets the agent stop", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		box.write(t, "pkg/clip/clip.go", goFile)
		box.failStub("go build")

		for range maxBlocks {
			blocked := box.adapter(t, "claude", "stop", "stop.json")
			require.Equal(t, exitDeny, blocked.code)
			assert.Contains(t, blocked.stderr, "go build failed")
		}

		released := box.adapter(t, "claude", "stop", "stop.json")

		assert.Equal(t, exitPass, released.code)
		assert.Contains(t, decode[claudeOutput](t, released.stdout).SystemMessage, "go build failed")
	})
}

func TestAntigravityAdapter_Pre(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		fixture      string
		wantDecision string
		wantReason   string
	}{
		{
			name:         "denies generator output",
			fixture:      "pre-write-sqlcgen.json",
			wantDecision: "deny",
			wantReason:   "make generate-sql",
		},
		{
			name:         "asks before editing a guardrail",
			fixture:      "pre-replace-mise.json",
			wantDecision: "ask",
			wantReason:   "toolchain",
		},
		{name: "answers ask for a clean command", fixture: "pre-run-command-status.json", wantDecision: "ask"},
		{
			name:         "denies a destructive command",
			fixture:      "pre-run-command-reset.json",
			wantDecision: "deny",
			wantReason:   "reset --hard",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			box := newSandbox(t)

			got := box.adapter(t, "antigravity", "pre", tt.fixture)

			require.Equal(t, exitPass, got.code, got.stderr)

			decision := decode[antigravityOutput](t, got.stdout)
			assert.Equal(t, tt.wantDecision, decision.Decision)

			if tt.wantReason == "" {
				assert.Nil(t, decision.Reason)

				return
			}

			require.NotNil(t, decision.Reason)
			assert.Contains(t, *decision.Reason, tt.wantReason)
		})
	}
}

func TestAntigravityAdapter_PreComment(t *testing.T) {
	t.Parallel()

	box := newSandbox(t)

	first := decode[antigravityOutput](t, box.adapter(t, "antigravity", "pre", "pre-replace-go-comment.json").stdout)
	second := decode[antigravityOutput](t, box.adapter(t, "antigravity", "pre", "pre-replace-go-comment.json").stdout)

	assert.Equal(t, "deny", first.Decision)
	require.NotNil(t, first.Reason)
	assert.Contains(t, *first.Reason, restatement)
	assert.Equal(t, "ask", second.Decision)
	require.NotNil(t, second.Reason)
	assert.Contains(t, *second.Reason, resubmittedHint)
}

func TestAntigravityAdapter_PostThenPreInvocation(t *testing.T) {
	t.Parallel()

	box := newSandbox(t)
	box.write(t, "pkg/clip/clip.go", goFile)
	box.failStub("go vet")

	post := box.adapter(t, "antigravity", "post", "post-replace-go.json")
	injected := box.adapter(t, "antigravity", "pre-invocation", "pre-invocation.json")
	drained := box.adapter(t, "antigravity", "pre-invocation", "pre-invocation.json")

	assert.JSONEq(t, "{}", post.stdout)

	steps := decode[antigravityOutput](t, injected.stdout).InjectSteps
	require.Len(t, steps, 1)
	assert.Contains(t, steps[0].EphemeralMessage, "go vet failed")
	assert.JSONEq(t, "{}", drained.stdout)
}

func TestAntigravityAdapter_Stop(t *testing.T) {
	t.Parallel()

	box := newSandbox(t)
	box.write(t, "pkg/clip/clip.go", goFile)
	box.failStub("golangci-lint run")

	got := box.adapter(t, "antigravity", "stop", "stop.json")

	decision := decode[antigravityOutput](t, got.stdout)
	assert.Equal(t, "continue", decision.Decision)
	require.NotNil(t, decision.Reason)
	assert.Contains(t, *decision.Reason, "golangci-lint failed")
}

func TestOpenCodeFixtures(t *testing.T) {
	t.Parallel()

	t.Run("patch-paths lists every path an apply_patch touches", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		call := decode[opencodeToolCall](t, box.fixture(t, "opencode", "apply-patch.json"))

		got := box.run(t, call.Args.PatchText, "patch-paths.sh")

		assert.Equal(t, strings.Join([]string{
			"internal/domain/snippet.go",
			"internal/domain/tag.go",
			"internal/domain/old.go",
			"internal/adapters/sqlite/sqlcgen/old.go",
			"internal/domain/unused.go",
		}, "\n")+"\n", got.stdout)
	})

	t.Run("guard-command denies a bash call that skips hooks", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		call := decode[opencodeToolCall](t, box.fixture(t, "opencode", "bash-no-verify.json"))

		got := box.run(t, call.Args.Command, "guard-command.sh")

		assert.Equal(t, exitDeny, got.code)
		assert.Contains(t, got.stderr, "--no-verify")
	})
}

func TestOpenCodeAdapter_PreEdit(t *testing.T) {
	t.Parallel()

	t.Run("denies a new comment once, then passes it without asking", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)

		first := box.adapter(t, "opencode", "pre-edit", "edit-go-comment.json")
		second := box.adapter(t, "opencode", "pre-edit", "edit-go-comment.json")

		assert.Equal(t, exitDeny, first.code)
		assert.Contains(t, first.stderr, restatement)
		assert.NotContains(t, first.stderr, askHint)
		assert.Equal(t, exitPass, second.code, second.stderr)
	})

	t.Run("checks each file of an apply_patch on its own", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)

		got := box.adapter(t, "opencode", "pre-edit", "apply-patch-go-comment.json")

		assert.Equal(t, exitDeny, got.code)
		assert.Contains(t, got.stderr, "internal/domain/tag.go:\n  // Tag is a tag.")
		assert.NotContains(t, got.stderr, "snippet.go")
	})
}

func TestGuardGoComments(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		path     string
		replaced string
		added    string
		wantCode int
	}{
		{name: "denies a new line comment", path: commentedPath, added: restatement, wantCode: exitDeny},
		{name: "denies a new block comment", path: commentedPath, added: "/* Trim. */", wantCode: exitDeny},
		{
			name:     "denies a new trailing comment",
			path:     commentedPath,
			added:    "name = trim(name) // trims",
			wantCode: exitDeny,
		},
		{
			name:     "denies a second copy of an existing comment",
			path:     commentedPath,
			replaced: restatement,
			added:    restatement + "\n" + restatement,
			wantCode: exitDeny,
		},
		{
			name:     "passes a comment the edit keeps",
			path:     commentedPath,
			replaced: "\t// Keep.\n\treturn err",
			added:    "\t// Keep.\n\treturn nil",
			wantCode: exitPass,
		},
		{
			name:     "passes a comment moved within the edit",
			path:     commentedPath,
			replaced: "a()\n// Keep.\nb()",
			added:    "// Keep.\nb()\na()",
			wantCode: exitPass,
		},
		{name: "passes a go directive", path: commentedPath, added: "//go:generate go-enum", wantCode: exitPass},
		{name: "passes a tool directive", path: commentedPath, added: "//sumtype:decl", wantCode: exitPass},
		{name: "denies a spaced label", path: commentedPath, added: "// note: trims", wantCode: exitDeny},
		{name: "denies a URL", path: commentedPath, added: "//https://example.com", wantCode: exitDeny},
		{name: "passes a go-enum declaration", path: commentedPath, added: "// ENUM(auto, dark).", wantCode: exitPass},
		{
			name:     "passes a nolint directive with its reason",
			path:     commentedPath,
			added:    "run(cmd) //nolint:gosec // G204: fixed arguments",
			wantCode: exitPass,
		},
		{
			name:     "passes an example's output",
			path:     "pkg/clip/example_test.go",
			added:    "// Output: x",
			wantCode: exitPass,
		},
		{name: "passes a slash in a string", path: commentedPath, added: `s := "a // b"`, wantCode: exitPass},
		{name: "passes doc.go", path: "internal/domain/doc.go", added: "// Package domain is…", wantCode: exitPass},
		{name: "passes a file that is not Go", path: "README.md", added: restatement, wantCode: exitPass},
		{
			name:     "passes a generated file",
			path:     "internal/domain/value/state_enum_gen.go",
			added:    restatement,
			wantCode: exitPass,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			box := newSandbox(t)
			box.write(t, "internal/domain/value/state_enum_gen.go", generatedHeader)

			got := box.guardComments(t, commentEdit{path: tt.path, replaced: tt.replaced, added: tt.added})

			assert.Equal(t, tt.wantCode, got.code, got.stderr)
		})
	}

	t.Run("asks the user when the same comment comes back", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)

		first := box.guardComments(t, newComment("", restatement))
		second := box.guardComments(t, newComment("return nil", "return err\n"+restatement))

		assert.Equal(t, exitDeny, first.code)
		assert.Contains(t, first.stderr, selfCheckHint)
		assert.Equal(t, exitAsk, second.code)
		assert.Contains(t, second.stderr, resubmittedHint)
	})

	t.Run("denies a different comment after an approved one", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)

		box.guardComments(t, newComment("", restatement))
		got := box.guardComments(t, newComment("", "// Another."))

		assert.Equal(t, exitDeny, got.code)
	})

	t.Run("passes the resubmission without asking when asking is unavailable", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)

		box.guardComments(t, newComment("", restatement), "--without-ask")
		got := box.guardComments(t, newComment("", restatement), "--without-ask")

		assert.Equal(t, exitPass, got.code, got.stderr)
	})
}

func TestGuardPath(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		path     string
		wantCode int
	}{
		{name: "denies nested mocks", path: "internal/app/snippet/mocks_test.go", wantCode: exitDeny},
		{name: "denies root mocks", path: "mocks_test.go", wantCode: exitDeny},
		{name: "denies go-enum output", path: "internal/domain/value/sort_enum.go", wantCode: exitDeny},
		{name: "denies go.sum", path: "go.sum", wantCode: exitDeny},
		{name: "denies the generated OpenCode rules", path: "opencode.json", wantCode: exitDeny},
		{
			name:     "denies the generated Language list",
			path:     "internal/domain/value/languages_gen.go",
			wantCode: exitDeny,
		},
		{name: "asks for a workflow", path: ".github/workflows/ci.yml", wantCode: exitAsk},
		{name: "asks for an agent script", path: "scripts/agent/guard-path.sh", wantCode: exitAsk},
		{name: "passes a migration", path: "db/migrations/0001_snippets.sql", wantCode: exitPass},
		{name: "passes a path outside the repo", path: "/etc/hosts", wantCode: exitPass},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			box := newSandbox(t)

			got := box.run(t, "", "guard-path.sh", tt.path)

			assert.Equal(t, tt.wantCode, got.code, got.stderr)
		})
	}

	t.Run("denies generator output in a linked worktree", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		worktree := filepath.Join(t.TempDir(), "wt")
		box.addWorktree(t, worktree)

		got := box.run(t, "", "guard-path.sh", filepath.Join(worktree, "go.sum"))

		assert.Equal(t, exitDeny, got.code, got.stderr)
	})

	t.Run("passes a path in another clone", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		other := newSandbox(t)

		got := box.run(t, "", "guard-path.sh", filepath.Join(other.repo, "go.sum"))

		assert.Equal(t, exitPass, got.code, got.stderr)
	})
}

func TestGuardCommand(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		command  string
		wantCode int
	}{
		{
			name:     "passes a commit whose message looks like shell",
			command:  `git commit -m "a -> b; --no-verify"`,
			wantCode: exitPass,
		},
		{name: "passes a push to a branch", command: "git add . && git push -u origin feature", wantCode: exitPass},
		{name: "passes stderr redirected to stdout", command: "go test ./... 2>&1 | tail -5", wantCode: exitPass},
		{
			name:     "passes writes to /dev/null and /tmp",
			command:  "echo x >/dev/null; echo y > /tmp/out",
			wantCode: exitPass,
		},
		{name: "passes writes to TMPDIR", command: `echo x >> "$TMPDIR/out"`, wantCode: exitPass},
		{name: "passes a heredoc read by a command", command: "wc -l <<'EOF'\na > b\nEOF", wantCode: exitPass},
		{name: "passes sed without in-place", command: "sed -n 1,5p main.go", wantCode: exitPass},
		{
			name:     "passes an interpreter that only reads",
			command:  `python3 -c 'print(open("go.mod").read())'`,
			wantCode: exitPass,
		},
		{name: "passes reading core.hooksPath", command: "git config --get core.hooksPath", wantCode: exitPass},
		{name: "passes unstaging the whole tree", command: "git restore --staged .", wantCode: exitPass},
		{
			name:     "passes a commit whose message mentions LEFTHOOK",
			command:  `git commit -m "docs: deny LEFTHOOK=0"`,
			wantCode: exitPass,
		},
		{name: "passes non-ASCII text", command: `printf '%s\n' "` + nonASCIIText + `"`, wantCode: exitPass},
		{
			name:     "denies a redirect after non-ASCII text",
			command:  "echo " + nonASCIIText + " > notes.txt",
			wantCode: exitDeny,
		},
		{name: "denies LEFTHOOK=0 before a command", command: "LEFTHOOK=0 git commit -m x", wantCode: exitDeny},
		{name: "denies exporting LEFTHOOK", command: "export LEFTHOOK=false && git push", wantCode: exitDeny},
		{
			name:     "denies LEFTHOOK_EXCLUDE through env",
			command:  "env LEFTHOOK_EXCLUDE=lint git push",
			wantCode: exitDeny,
		},
		{
			name:     "denies LEFTHOOK_CONFIG",
			command:  "LEFTHOOK_CONFIG=/tmp/none.yml git commit -m x",
			wantCode: exitDeny,
		},
		{name: "passes a message attached to commit -m", command: `git commit -m"Add login"`, wantCode: exitPass},
		{name: "passes a commit -C value starting with n", command: "git commit -Cnightly", wantCode: exitPass},
		{name: "passes a message after a cluster ending in -m", command: `git commit -am "-n"`, wantCode: exitPass},
		{name: "passes a push -o value containing f", command: "git push -oforce origin feature", wantCode: exitPass},
		{name: "passes a clean -e value containing f", command: "git clean -n -efixtures", wantCode: exitPass},
		{name: "denies commit -n", command: "git commit -nm wip", wantCode: exitDeny},
		{name: "denies commit -an", command: "git commit -an -m wip", wantCode: exitDeny},
		{name: "denies commit -n after a message", command: "git commit -m wip -n", wantCode: exitDeny},
		{
			name:     "denies push -f after a push option",
			command:  "git push -o ci.skip -f origin feature",
			wantCode: exitDeny,
		},
		{name: "denies clean -f after an exclude", command: "git clean -e vendor -f", wantCode: exitDeny},
		{name: "denies commit -n after an empty message", command: `git commit -m "" -n`, wantCode: exitDeny},
		{
			name:     "denies commit -n after a message of dropped characters",
			command:  `git commit -m "!?" -n`,
			wantCode: exitDeny,
		},
		{
			name:     "denies push -f after an empty push option",
			command:  `git push -o "" -f origin feature`,
			wantCode: exitDeny,
		},
		{name: "denies clean -f after an empty exclude", command: `git clean -e "" -f`, wantCode: exitDeny},
		{name: "denies --no-verify", command: "git push --no-verify", wantCode: exitDeny},
		{
			name:     "denies overriding core.hooksPath",
			command:  "git -c core.hooksPath=/dev/null commit -m x",
			wantCode: exitDeny,
		},
		{name: "denies setting core.hooksPath", command: "git config core.hooksPath .nohooks", wantCode: exitDeny},
		{name: "denies push -f", command: "git push -f origin feature", wantCode: exitDeny},
		{name: "denies a +refspec", command: "git push origin +feature", wantCode: exitDeny},
		{name: "denies a push to main", command: "git push origin HEAD:main", wantCode: exitDeny},
		{name: "denies reset --hard", command: "git reset --hard", wantCode: exitDeny},
		{name: "denies clean -f", command: "git clean -fdx", wantCode: exitDeny},
		{name: "denies a whole-tree checkout", command: "git checkout -- .", wantCode: exitDeny},
		{name: "denies a whole-tree restore", command: "git restore .", wantCode: exitDeny},
		{name: "denies stash drop", command: "git stash drop", wantCode: exitDeny},
		{name: "denies stash clear", command: "git -C . stash clear", wantCode: exitDeny},
		{name: "passes sed with i inside a script cluster", command: "sed -es/i/j/ main.go", wantCode: exitPass},
		{name: "passes sed with i inside a script file cluster", command: "sed -nfi.sed main.go", wantCode: exitPass},
		{name: "passes perl -0777 without in-place", command: "perl -0777 -ne 'print' main.go", wantCode: exitPass},
		{name: "passes perl with i inside -e code", command: "perl -e'print 1' main.go", wantCode: exitPass},
		{
			name:     "passes perl with i inside a module name",
			command:  "perl -Mstrict -ne 'print' main.go",
			wantCode: exitPass,
		},
		{name: "passes perl with i inside -C flags", command: "perl -Ci -ne 'print' main.go", wantCode: exitPass},
		{name: "denies sed -i", command: "sed -i '' 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies sed -i.bak", command: "sed -i.bak 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies sed -ni", command: "sed -ni 's/a/b/p' main.go", wantCode: exitDeny},
		{name: "denies sed -Ei", command: "sed -Ei '' 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies sed -zsi", command: "sed -zsi 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies BSD sed -I", command: "sed -I '' 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies BSD sed -nI", command: "sed -nI '' 's/a/b/p' main.go", wantCode: exitDeny},
		{name: "denies sed --in-place=.bak", command: "sed --in-place=.bak 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies perl -pi", command: "perl -pi -e 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies perl -0pi", command: "perl -0pi -e 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies perl -0777pi", command: "perl -0777pi -e 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies perl -0x1Fpi", command: "perl -0x1Fpi -e 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies perl -pi.bak", command: "perl -pi.bak -e 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies perl -ni", command: "perl -ni -e 'print' main.go", wantCode: exitDeny},
		{name: "denies perl -pie", command: "perl -pie 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies perl -l0pi", command: "perl -l0pi -e 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies perl -CSDpi", command: "perl -CSDpi -e 's/a/b/' main.go", wantCode: exitDeny},
		{name: "denies perl -i after a module", command: "perl -Mstrict -pi -e 's/a/b/' main.go", wantCode: exitDeny},
		{name: "passes a sed -e script that starts with -i", command: "sed -n -e '-i' main.go", wantCode: exitPass},
		{name: "denies sed -i after an empty script", command: `sed -e "" -i main.go`, wantCode: exitDeny},
		{name: "denies perl -i after empty code", command: `perl -pe "" -i main.go`, wantCode: exitDeny},
		{name: "denies awk -i inplace", command: "awk -i inplace 1 main.go", wantCode: exitDeny},
		{name: "denies a redirect into the repo", command: "echo x > main.go", wantCode: exitDeny},
		{name: "denies tee into the repo", command: "echo x | tee -a main.go", wantCode: exitDeny},
		{
			name:     "denies an interpreter writing a file",
			command:  "python3 - <<'EOF'\nopen('main.go', 'w').write('x')\nEOF",
			wantCode: exitDeny,
		},
		{name: "passes a copy out of the repo to /tmp", command: "cp main.go /tmp/main.go", wantCode: exitPass},
		{name: "passes a move to TMPDIR", command: `mv main.go "$TMPDIR/main.go"`, wantCode: exitPass},
		{name: "passes a copy outside the repo", command: "cp -r internal ../backup", wantCode: exitPass},
		{name: "passes git mv", command: "git mv main.go app.go", wantCode: exitPass},
		{name: "passes go install", command: "go install ./cmd/tuisnip", wantCode: exitPass},
		{name: "passes rsync to a remote host", command: "rsync -a . host:backup/", wantCode: exitPass},
		{name: "passes dd to /dev/null", command: "dd if=main.go of=/dev/null", wantCode: exitPass},
		{name: "passes patch --dry-run", command: "patch --dry-run -p1 < /tmp/fix.diff", wantCode: exitPass},
		{name: "passes git apply --check", command: "git apply --check /tmp/fix.diff", wantCode: exitPass},
		{
			name:     "denies a copy from /tmp into the repo",
			command:  `echo "// x" > /tmp/a.go && cp /tmp/a.go internal/domain/a.go`,
			wantCode: exitDeny,
		},
		{name: "denies a copy into the repo root", command: "cp /tmp/a.go .", wantCode: exitDeny},
		{name: "denies a copy with -t into the repo", command: "cp -t internal /tmp/a.go", wantCode: exitDeny},
		{name: "denies a move into the repo", command: "sudo mv /tmp/a.go main.go", wantCode: exitDeny},
		{name: "denies install into the repo", command: "install -m 644 /tmp/a.go main.go", wantCode: exitDeny},
		{name: "denies a symlink into the repo", command: "ln -s /tmp/a.go main.go", wantCode: exitDeny},
		{name: "denies dd into the repo", command: "dd if=/tmp/a.go of=main.go", wantCode: exitDeny},
		{name: "denies rsync into the repo", command: "rsync -a /tmp/src/ internal/", wantCode: exitDeny},
		{name: "denies patch in the repo", command: "patch -p1 < /tmp/fix.diff", wantCode: exitDeny},
		{name: "denies git apply", command: "git apply /tmp/fix.diff", wantCode: exitDeny},
		{
			name:     "denies git apply --check --apply",
			command:  "git apply --check --apply /tmp/fix.diff",
			wantCode: exitDeny,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			box := newSandbox(t)

			got := box.run(t, tt.command, "guard-command.sh")

			assert.Equal(t, tt.wantCode, got.code, got.stderr)
		})
	}

	t.Run("denies a bare push from main", func(t *testing.T) {
		t.Parallel()
		box := newSandbox(t)
		box.git(t, "switch", "--quiet", "main")

		got := box.run(t, "git push", "guard-command.sh")

		assert.Equal(t, exitDeny, got.code)
	})

	t.Run("denies writes into the clone after cd out of it", func(t *testing.T) {
		t.Parallel()

		for _, target := range []string{"main.go", ".git/hooks/pre-push"} {
			t.Run(target, func(t *testing.T) {
				t.Parallel()
				box := newSandbox(t)
				outside := t.TempDir()
				// An absolute path into the sandbox lies under /tmp or $TMPDIR, where writes are allowed.
				relative, err := filepath.Rel(outside, filepath.Join(box.repo, target))
				require.NoError(t, err)

				got := box.run(t, "cd "+outside+" && cp /tmp/a.go "+relative, "guard-command.sh")

				assert.Equal(t, exitDeny, got.code, got.stderr)
			})
		}
	})

	t.Run("judges a bare push by the checkout it runs in", func(t *testing.T) {
		t.Parallel()

		pushTests := []struct {
			name       string
			inWorktree bool
			command    string
			wantCode   int
		}{
			{name: "passes after cd into a worktree on a branch", command: "cd {{WT}} && git push", wantCode: exitPass},
			{name: "passes with git -C on a worktree on a branch", command: "git -C {{WT}} push", wantCode: exitPass},
			{
				name:       "denies after cd into the checkout on main",
				inWorktree: true,
				command:    "cd {{REPO}} && git push",
				wantCode:   exitDeny,
			},
			{
				name:       "denies with git -C on the checkout on main",
				inWorktree: true,
				command:    "git -C {{REPO}} push",
				wantCode:   exitDeny,
			},
			{
				name:     "denies a push after a git -C command",
				command:  "git -C {{WT}} status && git push",
				wantCode: exitDeny,
			},
		}
		for _, tt := range pushTests {
			t.Run(tt.name, func(t *testing.T) {
				t.Parallel()
				box := newSandbox(t)
				box.git(t, "switch", "--quiet", "main")
				worktree := filepath.Join(t.TempDir(), "wt")
				box.addWorktree(t, worktree)

				command := strings.NewReplacer(worktreePlaceholder, worktree, repoPlaceholder, box.repo).
					Replace(tt.command)
				if tt.inWorktree {
					box = box.in(worktree)
				}

				got := box.run(t, command, "guard-command.sh")

				assert.Equal(t, tt.wantCode, got.code, got.stderr)
			})
		}
	})
}
