// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.5

// Built By: go install

package config

import (
	"fmt"
	"strings"
)

const (
	// BindingQuit is a Binding of type quit.
	BindingQuit Binding = "quit"
	// BindingHelp is a Binding of type help.
	BindingHelp Binding = "help"
	// BindingSearch is a Binding of type search.
	BindingSearch Binding = "search"
	// BindingZoom is a Binding of type zoom.
	BindingZoom Binding = "zoom"
	// BindingNewSnippet is a Binding of type new_snippet.
	BindingNewSnippet Binding = "new_snippet"
	// BindingCapture is a Binding of type capture.
	BindingCapture Binding = "capture"
	// BindingFocusNext is a Binding of type focus_next.
	BindingFocusNext Binding = "focus_next"
	// BindingFocusPrev is a Binding of type focus_prev.
	BindingFocusPrev Binding = "focus_prev"
	// BindingFocusRight is a Binding of type focus_right.
	BindingFocusRight Binding = "focus_right"
	// BindingFocusLeft is a Binding of type focus_left.
	BindingFocusLeft Binding = "focus_left"
	// BindingFocusFolders is a Binding of type focus_folders.
	BindingFocusFolders Binding = "focus_folders"
	// BindingFocusTags is a Binding of type focus_tags.
	BindingFocusTags Binding = "focus_tags"
	// BindingFocusList is a Binding of type focus_list.
	BindingFocusList Binding = "focus_list"
	// BindingFocusSnippet is a Binding of type focus_snippet.
	BindingFocusSnippet Binding = "focus_snippet"
	// BindingOpen is a Binding of type open.
	BindingOpen Binding = "open"
	// BindingBack is a Binding of type back.
	BindingBack Binding = "back"
	// BindingDown is a Binding of type down.
	BindingDown Binding = "down"
	// BindingUp is a Binding of type up.
	BindingUp Binding = "up"
	// BindingTop is a Binding of type top.
	BindingTop Binding = "top"
	// BindingBottom is a Binding of type bottom.
	BindingBottom Binding = "bottom"
	// BindingPageDown is a Binding of type page_down.
	BindingPageDown Binding = "page_down"
	// BindingPageUp is a Binding of type page_up.
	BindingPageUp Binding = "page_up"
	// BindingNewFolder is a Binding of type new_folder.
	BindingNewFolder Binding = "new_folder"
	// BindingNewTag is a Binding of type new_tag.
	BindingNewTag Binding = "new_tag"
	// BindingRename is a Binding of type rename.
	BindingRename Binding = "rename"
	// BindingDelete is a Binding of type delete.
	BindingDelete Binding = "delete"
	// BindingMove is a Binding of type move.
	BindingMove Binding = "move"
	// BindingCollapse is a Binding of type collapse.
	BindingCollapse Binding = "collapse"
	// BindingCopy is a Binding of type copy.
	BindingCopy Binding = "copy"
	// BindingEdit is a Binding of type edit.
	BindingEdit Binding = "edit"
	// BindingOpenInEditor is a Binding of type open_in_editor.
	BindingOpenInEditor Binding = "open_in_editor"
	// BindingDuplicate is a Binding of type duplicate.
	BindingDuplicate Binding = "duplicate"
	// BindingCycleSort is a Binding of type cycle_sort.
	BindingCycleSort Binding = "cycle_sort"
	// BindingWrap is a Binding of type wrap.
	BindingWrap Binding = "wrap"
	// BindingSave is a Binding of type save.
	BindingSave Binding = "save"
	// BindingCancel is a Binding of type cancel.
	BindingCancel Binding = "cancel"
	// BindingNextField is a Binding of type next_field.
	BindingNextField Binding = "next_field"
	// BindingPrevField is a Binding of type prev_field.
	BindingPrevField Binding = "prev_field"
	// BindingOpenField is a Binding of type open_field.
	BindingOpenField Binding = "open_field"
	// BindingPickLanguage is a Binding of type pick_language.
	BindingPickLanguage Binding = "pick_language"
	// BindingEditTags is a Binding of type edit_tags.
	BindingEditTags Binding = "edit_tags"
	// BindingLeave is a Binding of type leave.
	BindingLeave Binding = "leave"
	// BindingIndent is a Binding of type indent.
	BindingIndent Binding = "indent"
	// BindingDedent is a Binding of type dedent.
	BindingDedent Binding = "dedent"
	// BindingAccept is a Binding of type accept.
	BindingAccept Binding = "accept"
	// BindingShowAllLanguages is a Binding of type show_all_languages.
	BindingShowAllLanguages Binding = "show_all_languages"
	// BindingYes is a Binding of type yes.
	BindingYes Binding = "yes"
	// BindingNo is a Binding of type no.
	BindingNo Binding = "no"
)

var ErrInvalidBinding = fmt.Errorf("not a valid Binding, try [%s]", strings.Join(_BindingNames, ", "))

var _BindingNames = []string{
	string(BindingQuit),
	string(BindingHelp),
	string(BindingSearch),
	string(BindingZoom),
	string(BindingNewSnippet),
	string(BindingCapture),
	string(BindingFocusNext),
	string(BindingFocusPrev),
	string(BindingFocusRight),
	string(BindingFocusLeft),
	string(BindingFocusFolders),
	string(BindingFocusTags),
	string(BindingFocusList),
	string(BindingFocusSnippet),
	string(BindingOpen),
	string(BindingBack),
	string(BindingDown),
	string(BindingUp),
	string(BindingTop),
	string(BindingBottom),
	string(BindingPageDown),
	string(BindingPageUp),
	string(BindingNewFolder),
	string(BindingNewTag),
	string(BindingRename),
	string(BindingDelete),
	string(BindingMove),
	string(BindingCollapse),
	string(BindingCopy),
	string(BindingEdit),
	string(BindingOpenInEditor),
	string(BindingDuplicate),
	string(BindingCycleSort),
	string(BindingWrap),
	string(BindingSave),
	string(BindingCancel),
	string(BindingNextField),
	string(BindingPrevField),
	string(BindingOpenField),
	string(BindingPickLanguage),
	string(BindingEditTags),
	string(BindingLeave),
	string(BindingIndent),
	string(BindingDedent),
	string(BindingAccept),
	string(BindingShowAllLanguages),
	string(BindingYes),
	string(BindingNo),
}

// BindingNames returns a list of possible string values of Binding.
func BindingNames() []string {
	tmp := make([]string, len(_BindingNames))
	copy(tmp, _BindingNames)
	return tmp
}

// String implements the Stringer interface.
func (x Binding) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Binding) IsValid() bool {
	_, err := ParseBinding(string(x))
	return err == nil
}

var _BindingValue = map[string]Binding{
	"quit":               BindingQuit,
	"help":               BindingHelp,
	"search":             BindingSearch,
	"zoom":               BindingZoom,
	"new_snippet":        BindingNewSnippet,
	"capture":            BindingCapture,
	"focus_next":         BindingFocusNext,
	"focus_prev":         BindingFocusPrev,
	"focus_right":        BindingFocusRight,
	"focus_left":         BindingFocusLeft,
	"focus_folders":      BindingFocusFolders,
	"focus_tags":         BindingFocusTags,
	"focus_list":         BindingFocusList,
	"focus_snippet":      BindingFocusSnippet,
	"open":               BindingOpen,
	"back":               BindingBack,
	"down":               BindingDown,
	"up":                 BindingUp,
	"top":                BindingTop,
	"bottom":             BindingBottom,
	"page_down":          BindingPageDown,
	"page_up":            BindingPageUp,
	"new_folder":         BindingNewFolder,
	"new_tag":            BindingNewTag,
	"rename":             BindingRename,
	"delete":             BindingDelete,
	"move":               BindingMove,
	"collapse":           BindingCollapse,
	"copy":               BindingCopy,
	"edit":               BindingEdit,
	"open_in_editor":     BindingOpenInEditor,
	"duplicate":          BindingDuplicate,
	"cycle_sort":         BindingCycleSort,
	"wrap":               BindingWrap,
	"save":               BindingSave,
	"cancel":             BindingCancel,
	"next_field":         BindingNextField,
	"prev_field":         BindingPrevField,
	"open_field":         BindingOpenField,
	"pick_language":      BindingPickLanguage,
	"edit_tags":          BindingEditTags,
	"leave":              BindingLeave,
	"indent":             BindingIndent,
	"dedent":             BindingDedent,
	"accept":             BindingAccept,
	"show_all_languages": BindingShowAllLanguages,
	"yes":                BindingYes,
	"no":                 BindingNo,
}

// ParseBinding attempts to convert a string to a Binding.
func ParseBinding(name string) (Binding, error) {
	if x, ok := _BindingValue[name]; ok {
		return x, nil
	}
	return Binding(""), fmt.Errorf("%s is %w", name, ErrInvalidBinding)
}

// MarshalText implements the text marshaller method.
func (x Binding) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Binding) UnmarshalText(text []byte) error {
	tmp, err := ParseBinding(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x Binding) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
