// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.5

// Built By: go install

package config

import (
	"fmt"
	"strings"
)

const (
	// ClipboardBackendAuto is a ClipboardBackend of type auto.
	ClipboardBackendAuto ClipboardBackend = "auto"
	// ClipboardBackendNative is a ClipboardBackend of type native.
	ClipboardBackendNative ClipboardBackend = "native"
	// ClipboardBackendOsc52 is a ClipboardBackend of type osc52.
	ClipboardBackendOsc52 ClipboardBackend = "osc52"
)

var ErrInvalidClipboardBackend = fmt.Errorf("not a valid ClipboardBackend, try [%s]", strings.Join(_ClipboardBackendNames, ", "))

var _ClipboardBackendNames = []string{
	string(ClipboardBackendAuto),
	string(ClipboardBackendNative),
	string(ClipboardBackendOsc52),
}

// ClipboardBackendNames returns a list of possible string values of ClipboardBackend.
func ClipboardBackendNames() []string {
	tmp := make([]string, len(_ClipboardBackendNames))
	copy(tmp, _ClipboardBackendNames)
	return tmp
}

// String implements the Stringer interface.
func (x ClipboardBackend) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ClipboardBackend) IsValid() bool {
	_, err := ParseClipboardBackend(string(x))
	return err == nil
}

var _ClipboardBackendValue = map[string]ClipboardBackend{
	"auto":   ClipboardBackendAuto,
	"native": ClipboardBackendNative,
	"osc52":  ClipboardBackendOsc52,
}

// ParseClipboardBackend attempts to convert a string to a ClipboardBackend.
func ParseClipboardBackend(name string) (ClipboardBackend, error) {
	if x, ok := _ClipboardBackendValue[name]; ok {
		return x, nil
	}
	return ClipboardBackend(""), fmt.Errorf("%s is %w", name, ErrInvalidClipboardBackend)
}

// MarshalText implements the text marshaller method.
func (x ClipboardBackend) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ClipboardBackend) UnmarshalText(text []byte) error {
	tmp, err := ParseClipboardBackend(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x ClipboardBackend) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
