// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.5

// Built By: go install

package config

import (
	"fmt"
	"strings"
)

const (
	// ScopeGlobal is a Scope of type global.
	ScopeGlobal Scope = "global"
	// ScopeFolders is a Scope of type folders.
	ScopeFolders Scope = "folders"
	// ScopeTags is a Scope of type tags.
	ScopeTags Scope = "tags"
	// ScopeSnippetList is a Scope of type snippet_list.
	ScopeSnippetList Scope = "snippet_list"
	// ScopeSnippetPane is a Scope of type snippet_pane.
	ScopeSnippetPane Scope = "snippet_pane"
	// ScopeEditor is a Scope of type editor.
	ScopeEditor Scope = "editor"
	// ScopeContent is a Scope of type content.
	ScopeContent Scope = "content"
	// ScopeSearch is a Scope of type search.
	ScopeSearch Scope = "search"
	// ScopePicker is a Scope of type picker.
	ScopePicker Scope = "picker"
	// ScopeConfirm is a Scope of type confirm.
	ScopeConfirm Scope = "confirm"
)

var ErrInvalidScope = fmt.Errorf("not a valid Scope, try [%s]", strings.Join(_ScopeNames, ", "))

var _ScopeNames = []string{
	string(ScopeGlobal),
	string(ScopeFolders),
	string(ScopeTags),
	string(ScopeSnippetList),
	string(ScopeSnippetPane),
	string(ScopeEditor),
	string(ScopeContent),
	string(ScopeSearch),
	string(ScopePicker),
	string(ScopeConfirm),
}

// ScopeNames returns a list of possible string values of Scope.
func ScopeNames() []string {
	tmp := make([]string, len(_ScopeNames))
	copy(tmp, _ScopeNames)
	return tmp
}

// String implements the Stringer interface.
func (x Scope) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Scope) IsValid() bool {
	_, err := ParseScope(string(x))
	return err == nil
}

var _ScopeValue = map[string]Scope{
	"global":       ScopeGlobal,
	"folders":      ScopeFolders,
	"tags":         ScopeTags,
	"snippet_list": ScopeSnippetList,
	"snippet_pane": ScopeSnippetPane,
	"editor":       ScopeEditor,
	"content":      ScopeContent,
	"search":       ScopeSearch,
	"picker":       ScopePicker,
	"confirm":      ScopeConfirm,
}

// ParseScope attempts to convert a string to a Scope.
func ParseScope(name string) (Scope, error) {
	if x, ok := _ScopeValue[name]; ok {
		return x, nil
	}
	return Scope(""), fmt.Errorf("%s is %w", name, ErrInvalidScope)
}

// MarshalText implements the text marshaller method.
func (x Scope) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Scope) UnmarshalText(text []byte) error {
	tmp, err := ParseScope(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x Scope) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
