// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.5

// Built By: go install

package config

import (
	"fmt"
	"strings"
)

const (
	// ThemeAuto is a Theme of type auto.
	ThemeAuto Theme = "auto"
	// ThemeLight is a Theme of type light.
	ThemeLight Theme = "light"
	// ThemeDark is a Theme of type dark.
	ThemeDark Theme = "dark"
)

var ErrInvalidTheme = fmt.Errorf("not a valid Theme, try [%s]", strings.Join(_ThemeNames, ", "))

var _ThemeNames = []string{
	string(ThemeAuto),
	string(ThemeLight),
	string(ThemeDark),
}

// ThemeNames returns a list of possible string values of Theme.
func ThemeNames() []string {
	tmp := make([]string, len(_ThemeNames))
	copy(tmp, _ThemeNames)
	return tmp
}

// String implements the Stringer interface.
func (x Theme) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Theme) IsValid() bool {
	_, err := ParseTheme(string(x))
	return err == nil
}

var _ThemeValue = map[string]Theme{
	"auto":  ThemeAuto,
	"light": ThemeLight,
	"dark":  ThemeDark,
}

// ParseTheme attempts to convert a string to a Theme.
func ParseTheme(name string) (Theme, error) {
	if x, ok := _ThemeValue[name]; ok {
		return x, nil
	}
	return Theme(""), fmt.Errorf("%s is %w", name, ErrInvalidTheme)
}

// MarshalText implements the text marshaller method.
func (x Theme) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Theme) UnmarshalText(text []byte) error {
	tmp, err := ParseTheme(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x Theme) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
