// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.5

// Built By: go install

package domain

import (
	"errors"
	"fmt"
)

const (
	// CopyDeliveryPlaced is a CopyDelivery of type placed.
	CopyDeliveryPlaced CopyDelivery = "placed"
	// CopyDeliverySentToTerminal is a CopyDelivery of type sent_to_terminal.
	CopyDeliverySentToTerminal CopyDelivery = "sent_to_terminal"
)

var ErrInvalidCopyDelivery = errors.New("not a valid CopyDelivery")

// String implements the Stringer interface.
func (x CopyDelivery) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CopyDelivery) IsValid() bool {
	_, err := ParseCopyDelivery(string(x))
	return err == nil
}

var _CopyDeliveryValue = map[string]CopyDelivery{
	"placed":           CopyDeliveryPlaced,
	"sent_to_terminal": CopyDeliverySentToTerminal,
}

// ParseCopyDelivery attempts to convert a string to a CopyDelivery.
func ParseCopyDelivery(name string) (CopyDelivery, error) {
	if x, ok := _CopyDeliveryValue[name]; ok {
		return x, nil
	}
	return CopyDelivery(""), fmt.Errorf("%s is %w", name, ErrInvalidCopyDelivery)
}

// MarshalText implements the text marshaller method.
func (x CopyDelivery) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *CopyDelivery) UnmarshalText(text []byte) error {
	tmp, err := ParseCopyDelivery(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x CopyDelivery) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
