// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.5

// Built By: go install

package domain

import (
	"errors"
	"fmt"
)

const (
	// FieldTitle is a Field of type title.
	FieldTitle Field = "title"
	// FieldDescription is a Field of type description.
	FieldDescription Field = "description"
	// FieldContent is a Field of type content.
	FieldContent Field = "content"
	// FieldLanguage is a Field of type language.
	FieldLanguage Field = "language"
	// FieldFolderName is a Field of type folder_name.
	FieldFolderName Field = "folder_name"
	// FieldTagName is a Field of type tag_name.
	FieldTagName Field = "tag_name"
)

var ErrInvalidField = errors.New("not a valid Field")

// String implements the Stringer interface.
func (x Field) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Field) IsValid() bool {
	_, err := ParseField(string(x))
	return err == nil
}

var _FieldValue = map[string]Field{
	"title":       FieldTitle,
	"description": FieldDescription,
	"content":     FieldContent,
	"language":    FieldLanguage,
	"folder_name": FieldFolderName,
	"tag_name":    FieldTagName,
}

// ParseField attempts to convert a string to a Field.
func ParseField(name string) (Field, error) {
	if x, ok := _FieldValue[name]; ok {
		return x, nil
	}
	return Field(""), fmt.Errorf("%s is %w", name, ErrInvalidField)
}

// MarshalText implements the text marshaller method.
func (x Field) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Field) UnmarshalText(text []byte) error {
	tmp, err := ParseField(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x Field) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
