// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.5

// Built By: go install

package domain

import (
	"errors"
	"fmt"
)

const (
	// SortOrderTitle is a SortOrder of type title.
	SortOrderTitle SortOrder = "title"
	// SortOrderUpdated is a SortOrder of type updated.
	SortOrderUpdated SortOrder = "updated"
	// SortOrderCreated is a SortOrder of type created.
	SortOrderCreated SortOrder = "created"
)

var ErrInvalidSortOrder = errors.New("not a valid SortOrder")

// String implements the Stringer interface.
func (x SortOrder) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SortOrder) IsValid() bool {
	_, err := ParseSortOrder(string(x))
	return err == nil
}

var _SortOrderValue = map[string]SortOrder{
	"title":   SortOrderTitle,
	"updated": SortOrderUpdated,
	"created": SortOrderCreated,
}

// ParseSortOrder attempts to convert a string to a SortOrder.
func ParseSortOrder(name string) (SortOrder, error) {
	if x, ok := _SortOrderValue[name]; ok {
		return x, nil
	}
	return SortOrder(""), fmt.Errorf("%s is %w", name, ErrInvalidSortOrder)
}

// MarshalText implements the text marshaller method.
func (x SortOrder) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *SortOrder) UnmarshalText(text []byte) error {
	tmp, err := ParseSortOrder(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x SortOrder) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
